export class BVGStyle {
    private L;
    private l;
    private w;
    private F;
    private f;
    private r;
    private c;
    private j;
    private m;
    private a;
    private d;
    needsFill: boolean;
    needsStroke: boolean;
    fillColor: number;
    fillAlpha: number;
    lineColor: number;
    lineAlpha: number;
    lineWidth: number;
    lineCap: CapsStyle;
    lineJoin: JointStyle;
    miterLimit: number;
    fillRule: FillRule;
    lineDash: number[];
    merge(style: BVGStyle): void;
    compute(): void;
    clone(): BVGStyle;
}
import { CapsStyle } from "../display/CapsStyle";
import { FillRule } from "../display/FillRule";
import { JointStyle } from "../display/JointStyle";
