// See https://github.com/jashkenas/underscore/blob/master/underscore-node.mjs for reference
// Note: currently missing `toPath`, `isMap`, `isSet`, `isWeakMap`, `isWeakSet`, `restArguments` and the default is split onto a new line
export {
    after,
    allKeys,
    before,
    bind,
    bindAll,
    chain,
    chunk,
    clone,
    compact,
    compose,
    constant,
    contains,
    contains as include,
    contains as includes,
    countBy,
    create,
    debounce,
    defaults,
    defer,
    delay,
    difference,
    each,
    each as forEach,
    escape,
    every,
    every as all,
    extend,
    extendOwn,
    extendOwn as assign,
    filter,
    filter as select,
    find,
    find as detect,
    findIndex,
    findKey,
    findLastIndex,
    findWhere,
    first,
    first as head,
    first as take,
    flatten,
    functions,
    functions as methods,
    get,
    groupBy,
    has,
    identity,
    indexBy,
    indexOf,
    initial,
    intersection,
    invert,
    invoke,
    isArguments,
    isArray,
    isArrayBuffer,
    isBoolean,
    isDataView,
    isDate,
    isElement,
    isEmpty,
    isEqual,
    isError,
    isFinite,
    isFunction,
    isMatch,
    isNaN,
    isNull,
    isNumber,
    isObject,
    isRegExp,
    isString,
    isSymbol,
    isTypedArray,
    isUndefined,
    iteratee,
    keys,
    last,
    lastIndexOf,
    map,
    map as collect,
    mapObject,
    matcher,
    matcher as matches,
    max,
    memoize,
    min,
    mixin,
    negate,
    noop,
    now,
    object,
    omit,
    once,
    pairs,
    partial,
    partition,
    pick,
    pluck,
    property,
    propertyOf,
    random,
    range,
    reduce,
    reduce as foldl,
    reduce as inject,
    reduceRight,
    reduceRight as foldr,
    reject,
    rest,
    rest as drop,
    rest as tail,
    result,
    sample,
    shuffle,
    size,
    some,
    some as any,
    sortBy,
    sortedIndex,
    tap,
    template,
    templateSettings,
    throttle,
    times,
    toArray,
    unescape,
    union,
    uniq,
    uniq as unique,
    uniqueId,
    unzip,
    unzip as transpose,
    values,
    VERSION,
    where,
    without,
    wrap,
    zip,
} from "./index.js";
import _ from "./index.js";
export default _;
