import { AbstractCrudObject } from './../abstract-crud-object';
import AbstractObject from './../abstract-object';
import Cursor from './../cursor';
export default class ProductSet extends AbstractCrudObject {
    static get Fields(): Record<string, any>;
    getAutomotiveModels(fields: string[], params?: Record<string, any>): Promise<Cursor>;
    getAutomotiveModels(fields: string[], params: Record<string, any> | undefined, fetchFirstPage: false): Cursor;
    getAutomotiveModels(fields: string[], params?: Record<string, any>, fetchFirstPage?: boolean): Cursor | Promise<Cursor>;
    getDestinations(fields: string[], params?: Record<string, any>): Promise<Cursor>;
    getDestinations(fields: string[], params: Record<string, any> | undefined, fetchFirstPage: false): Cursor;
    getDestinations(fields: string[], params?: Record<string, any>, fetchFirstPage?: boolean): Cursor | Promise<Cursor>;
    getFlights(fields: string[], params?: Record<string, any>): Promise<Cursor>;
    getFlights(fields: string[], params: Record<string, any> | undefined, fetchFirstPage: false): Cursor;
    getFlights(fields: string[], params?: Record<string, any>, fetchFirstPage?: boolean): Cursor | Promise<Cursor>;
    getHomeListings(fields: string[], params?: Record<string, any>): Promise<Cursor>;
    getHomeListings(fields: string[], params: Record<string, any> | undefined, fetchFirstPage: false): Cursor;
    getHomeListings(fields: string[], params?: Record<string, any>, fetchFirstPage?: boolean): Cursor | Promise<Cursor>;
    getHotels(fields: string[], params?: Record<string, any>): Promise<Cursor>;
    getHotels(fields: string[], params: Record<string, any> | undefined, fetchFirstPage: false): Cursor;
    getHotels(fields: string[], params?: Record<string, any>, fetchFirstPage?: boolean): Cursor | Promise<Cursor>;
    getMediaTitles(fields: string[], params?: Record<string, any>): Promise<Cursor>;
    getMediaTitles(fields: string[], params: Record<string, any> | undefined, fetchFirstPage: false): Cursor;
    getMediaTitles(fields: string[], params?: Record<string, any>, fetchFirstPage?: boolean): Cursor | Promise<Cursor>;
    getProducts(fields: string[], params?: Record<string, any>): Promise<Cursor>;
    getProducts(fields: string[], params: Record<string, any> | undefined, fetchFirstPage: false): Cursor;
    getProducts(fields: string[], params?: Record<string, any>, fetchFirstPage?: boolean): Cursor | Promise<Cursor>;
    getVehicleOffers(fields: string[], params?: Record<string, any>): Promise<Cursor>;
    getVehicleOffers(fields: string[], params: Record<string, any> | undefined, fetchFirstPage: false): Cursor;
    getVehicleOffers(fields: string[], params?: Record<string, any>, fetchFirstPage?: boolean): Cursor | Promise<Cursor>;
    getVehicles(fields: string[], params?: Record<string, any>): Promise<Cursor>;
    getVehicles(fields: string[], params: Record<string, any> | undefined, fetchFirstPage: false): Cursor;
    getVehicles(fields: string[], params?: Record<string, any>, fetchFirstPage?: boolean): Cursor | Promise<Cursor>;
    delete(fields: string[], params?: Record<string, any>): Promise<AbstractObject>;
    get(fields: string[], params?: Record<string, any>): Promise<ProductSet>;
    update(fields: string[], params?: Record<string, any>): Promise<ProductSet>;
}
