import { AbstractCrudObject } from "./../abstract-crud-object";
import AbstractObject from "./../abstract-object";
import Cursor from "./../cursor";
import StoreCatalogSettings from "./store-catalog-settings";
import ProductCatalogCategory from "./product-catalog-category";
import CPASLsbImageBank from "./cpas-lsb-image-bank";
import HomeListing from "./home-listing";
import Hotel from "./hotel";
import ProductFeed from "./product-feed";
import ProductGroup from "./product-group";
import ProductSet from "./product-set";
import ProductItem from "./product-item";
import Vehicle from "./vehicle";
/**
 * ProductCatalog
 * @see {@link https://developers.facebook.com/docs/marketing-api/}
 */
export default class ProductCatalog extends AbstractCrudObject {
    static get Fields(): Readonly<{
        ad_account_to_collaborative_ads_share_settings: "ad_account_to_collaborative_ads_share_settings";
        agency_collaborative_ads_share_settings: "agency_collaborative_ads_share_settings";
        business: "business";
        catalog_store: "catalog_store";
        commerce_merchant_settings: "commerce_merchant_settings";
        creator_user: "creator_user";
        da_display_settings: "da_display_settings";
        default_image_url: "default_image_url";
        fallback_image_url: "fallback_image_url";
        feed_count: "feed_count";
        id: "id";
        is_catalog_segment: "is_catalog_segment";
        is_local_catalog: "is_local_catalog";
        name: "name";
        owner_business: "owner_business";
        product_count: "product_count";
        store_catalog_settings: "store_catalog_settings";
        user_access_expire_time: "user_access_expire_time";
        vertical: "vertical";
    }>;
    static get AdditionalVerticalOption(): Readonly<{
        local_da_catalog: "LOCAL_DA_CATALOG";
        local_products: "LOCAL_PRODUCTS";
    }>;
    static get Vertical(): Readonly<{
        adoptable_pets: "adoptable_pets";
        commerce: "commerce";
        destinations: "destinations";
        flights: "flights";
        generic: "generic";
        home_listings: "home_listings";
        hotels: "hotels";
        jobs: "jobs";
        local_service_businesses: "local_service_businesses";
        offer_items: "offer_items";
        offline_commerce: "offline_commerce";
        transactable_items: "transactable_items";
        vehicles: "vehicles";
    }>;
    static get PermittedRoles(): Readonly<{
        admin: "ADMIN";
        advertiser: "ADVERTISER";
    }>;
    static get PermittedTasks(): Readonly<{
        aa_analyze: "AA_ANALYZE";
        advertise: "ADVERTISE";
        manage: "MANAGE";
        manage_ar: "MANAGE_AR";
    }>;
    static get Tasks(): Readonly<{
        aa_analyze: "AA_ANALYZE";
        advertise: "ADVERTISE";
        manage: "MANAGE";
        manage_ar: "MANAGE_AR";
    }>;
    static get Standard(): Readonly<{
        google: "google";
    }>;
    static get ItemSubType(): Readonly<{
        appliances: "APPLIANCES";
        baby_feeding: "BABY_FEEDING";
        baby_transport: "BABY_TRANSPORT";
        beauty: "BEAUTY";
        bedding: "BEDDING";
        cameras: "CAMERAS";
        cell_phones_and_smart_watches: "CELL_PHONES_AND_SMART_WATCHES";
        cleaning_supplies: "CLEANING_SUPPLIES";
        clothing: "CLOTHING";
        clothing_accessories: "CLOTHING_ACCESSORIES";
        computers_and_tablets: "COMPUTERS_AND_TABLETS";
        diapering_and_potty_training: "DIAPERING_AND_POTTY_TRAINING";
        electronics_accessories: "ELECTRONICS_ACCESSORIES";
        furniture: "FURNITURE";
        health: "HEALTH";
        home_goods: "HOME_GOODS";
        jewelry: "JEWELRY";
        nursery: "NURSERY";
        printers_and_scanners: "PRINTERS_AND_SCANNERS";
        projectors: "PROJECTORS";
        shoes_and_footwear: "SHOES_AND_FOOTWEAR";
        software: "SOFTWARE";
        toys: "TOYS";
        tvs_and_monitors: "TVS_AND_MONITORS";
        video_game_consoles_and_video_games: "VIDEO_GAME_CONSOLES_AND_VIDEO_GAMES";
        watches: "WATCHES";
    }>;
    deleteAgencies(params?: Record<string, any>): Promise<any>;
    getAgencies(fields: Array<string>, params?: Record<string, any>, fetchFirstPage?: boolean): Cursor | Promise<any>;
    createAgency(fields: Array<string>, params?: Record<string, any>, pathOverride?: string | null | undefined): Promise<ProductCatalog>;
    deleteAssignedUsers(params?: Record<string, any>): Promise<any>;
    getAssignedUsers(fields: Array<string>, params?: Record<string, any>, fetchFirstPage?: boolean): Cursor | Promise<any>;
    createAssignedUser(fields: Array<string>, params?: Record<string, any>, pathOverride?: string | null | undefined): Promise<ProductCatalog>;
    getAutomotiveModels(fields: Array<string>, params?: Record<string, any>, fetchFirstPage?: boolean): Cursor | Promise<any>;
    createBatch(fields: Array<string>, params?: Record<string, any>, pathOverride?: string | null | undefined): Promise<ProductCatalog>;
    createCatalogStore(fields: Array<string>, params?: Record<string, any>, pathOverride?: string | null | undefined): Promise<StoreCatalogSettings>;
    getCategories(fields: Array<string>, params?: Record<string, any>, fetchFirstPage?: boolean): Cursor | Promise<any>;
    createCategory(fields: Array<string>, params?: Record<string, any>, pathOverride?: string | null | undefined): Promise<ProductCatalogCategory>;
    getCheckBatchRequestStatus(fields: Array<string>, params?: Record<string, any>, fetchFirstPage?: boolean): Cursor | Promise<any>;
    getCollaborativeAdsLsbImageBank(fields: Array<string>, params?: Record<string, any>, fetchFirstPage?: boolean): Cursor | Promise<any>;
    getCollaborativeAdsShareSettings(fields: Array<string>, params?: Record<string, any>, fetchFirstPage?: boolean): Cursor | Promise<any>;
    createCpasLsbImageBank(fields: Array<string>, params?: Record<string, any>, pathOverride?: string | null | undefined): Promise<CPASLsbImageBank>;
    getCreatorAssetCreatives(fields: Array<string>, params?: Record<string, any>, fetchFirstPage?: boolean): Cursor | Promise<any>;
    getDataSources(fields: Array<string>, params?: Record<string, any>, fetchFirstPage?: boolean): Cursor | Promise<any>;
    getDestinations(fields: Array<string>, params?: Record<string, any>, fetchFirstPage?: boolean): Cursor | Promise<any>;
    getDiagnostics(fields: Array<string>, params?: Record<string, any>, fetchFirstPage?: boolean): Cursor | Promise<any>;
    getEventStats(fields: Array<string>, params?: Record<string, any>, fetchFirstPage?: boolean): Cursor | Promise<any>;
    deleteExternalEventSources(params?: Record<string, any>): Promise<any>;
    getExternalEventSources(fields: Array<string>, params?: Record<string, any>, fetchFirstPage?: boolean): Cursor | Promise<any>;
    createExternalEventSource(fields: Array<string>, params?: Record<string, any>, pathOverride?: string | null | undefined): Promise<ProductCatalog>;
    getFlights(fields: Array<string>, params?: Record<string, any>, fetchFirstPage?: boolean): Cursor | Promise<any>;
    getHomeListings(fields: Array<string>, params?: Record<string, any>, fetchFirstPage?: boolean): Cursor | Promise<any>;
    createHomeListing(fields: Array<string>, params?: Record<string, any>, pathOverride?: string | null | undefined): Promise<HomeListing>;
    getHotelRoomsBatch(fields: Array<string>, params?: Record<string, any>, fetchFirstPage?: boolean): Cursor | Promise<any>;
    createHotelRoomsBatch(fields: Array<string>, params?: Record<string, any>, pathOverride?: string | null | undefined): Promise<ProductCatalog>;
    getHotels(fields: Array<string>, params?: Record<string, any>, fetchFirstPage?: boolean): Cursor | Promise<any>;
    createHotel(fields: Array<string>, params?: Record<string, any>, pathOverride?: string | null | undefined): Promise<Hotel>;
    createItemsBatch(fields: Array<string>, params?: Record<string, any>, pathOverride?: string | null | undefined): Promise<ProductCatalog>;
    createLocalizedItemsBatch(fields: Array<string>, params?: Record<string, any>, pathOverride?: string | null | undefined): Promise<ProductCatalog>;
    getPricingVariablesBatch(fields: Array<string>, params?: Record<string, any>, fetchFirstPage?: boolean): Cursor | Promise<any>;
    createPricingVariablesBatch(fields: Array<string>, params?: Record<string, any>, pathOverride?: string | null | undefined): Promise<ProductCatalog>;
    getProductFeeds(fields: Array<string>, params?: Record<string, any>, fetchFirstPage?: boolean): Cursor | Promise<any>;
    createProductFeed(fields: Array<string>, params?: Record<string, any>, pathOverride?: string | null | undefined): Promise<ProductFeed>;
    getProductGroups(fields: Array<string>, params?: Record<string, any>, fetchFirstPage?: boolean): Cursor | Promise<any>;
    createProductGroup(fields: Array<string>, params?: Record<string, any>, pathOverride?: string | null | undefined): Promise<ProductGroup>;
    getProductSets(fields: Array<string>, params?: Record<string, any>, fetchFirstPage?: boolean): Cursor | Promise<any>;
    createProductSet(fields: Array<string>, params?: Record<string, any>, pathOverride?: string | null | undefined): Promise<ProductSet>;
    getProductSetsBatch(fields: Array<string>, params?: Record<string, any>, fetchFirstPage?: boolean): Cursor | Promise<any>;
    getProducts(fields: Array<string>, params?: Record<string, any>, fetchFirstPage?: boolean): Cursor | Promise<any>;
    createProduct(fields: Array<string>, params?: Record<string, any>, pathOverride?: string | null | undefined): Promise<ProductItem>;
    getVehicleOffers(fields: Array<string>, params?: Record<string, any>, fetchFirstPage?: boolean): Cursor | Promise<any>;
    getVehicles(fields: Array<string>, params?: Record<string, any>, fetchFirstPage?: boolean): Cursor | Promise<any>;
    createVehicle(fields: Array<string>, params?: Record<string, any>, pathOverride?: string | null | undefined): Promise<Vehicle>;
    createVersionItemsBatch(fields: Array<string>, params?: Record<string, any>, pathOverride?: string | null | undefined): Promise<ProductCatalog>;
    delete(fields: Array<string>, params?: Record<string, any>): AbstractObject;
    get(fields: Array<string>, params?: Record<string, any>): ProductCatalog;
    update(fields: Array<string>, params?: Record<string, any>): ProductCatalog;
}
