export const N: "\n";
export const TAB: "\t";
export const F: "\f";
export const R: "\r";
export const EQ: "=";
export const QUOTEMARK: "\"";
export const SPACE: " ";
export const OPEN_BRAKET: "[";
export const CLOSE_BRAKET: "]";
export const SLASH: "/";
export const BACKSLASH: "\\";
