/// <reference path="../node/node.d.ts" />
/// <reference path="nodemailer.d.ts" />
declare var nodemailer: Nodemailer;
declare var fs: any;
declare var pathlib: any;
declare var transport: Transport;
declare var message: MailComposer;
declare var smptTransport1: Transport;
declare var smtpTransport2: Transport;
