/// 
import { DashboardRow } from './row/row_model';
export class DashboardModel {
    id: any;
    title: any;
    autoUpdate: any;
    description: any;
    tags: any;
    style: any;
    timezone: any;
    editable: any;
    graphTooltip: any;
    rows: DashboardRow[];
    time: any;
    timepicker: any;
    hideControls: any;
    templating: any;
    annotations: any;
    refresh: any;
    snapshot: any;
    schemaVersion: number;
    version: number;
    revision: number;
    links: any;
    gnetId: any;
    meta: any;
    events: any;
    editMode: boolean;
    constructor(data: any, meta?: any);
    private initMeta(meta);
    getSaveModelClone(): any;
    addEmptyRow(): void;
    private ensureListExist(data);
    getNextPanelId(): number;
    forEachPanel(callback: any): void;
    getPanelById(id: any): any;
    addPanel(panel: any, row: any): void;
    removeRow(row: any, force?: any): void;
    toggleEditMode(): void;
    setPanelFocus(id: any): void;
    updateSubmenuVisibility(): void;
    getPanelInfoById(panelId: any): any;
    duplicatePanel(panel: any, row: any): any;
    formatDate(date: any, format: any): any;
    destroy(): void;
    cycleGraphTooltip(): void;
    sharedTooltipModeEnabled(): boolean;
    sharedCrosshairModeOnly(): boolean;
    getRelativeTime(date: any): any;
    getNextQueryLetter(panel: any): any;
    isTimezoneUtc(): boolean;
    getTimezone(): any;
    private updateSchema(old);
}
