// Type definitions for webextension-polyfill 0.8
// Project: https://github.com/mozilla/webextension-polyfill
// Definitions by: Santo Pfingsten <https://github.com/Lusito>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped
// Generated using https://github.com/Lusito/webextension-polyfill-ts

// Generated from Mozilla sources. Do not manually edit!

import { ActivityLog } from "./namespaces/activityLog";
import { Alarms } from "./namespaces/alarms";
import { Bookmarks } from "./namespaces/bookmarks";
import { Action } from "./namespaces/action";
import { BrowserAction } from "./namespaces/browserAction";
import { BrowserSettings } from "./namespaces/browserSettings";
import { BrowsingData } from "./namespaces/browsingData";
import { CaptivePortal } from "./namespaces/captivePortal";
import { Clipboard } from "./namespaces/clipboard";
import { Commands } from "./namespaces/commands";
import { ContentScripts } from "./namespaces/contentScripts";
import { ContextualIdentities } from "./namespaces/contextualIdentities";
import { Cookies } from "./namespaces/cookies";
import { DeclarativeContent } from "./namespaces/declarativeContent";
import { Devtools } from "./namespaces/devtools";
import { Dns } from "./namespaces/dns";
import { Downloads } from "./namespaces/downloads";
import { Events } from "./namespaces/events";
import { Experiments } from "./namespaces/experiments";
import { Extension } from "./namespaces/extension";
import { ExtensionTypes } from "./namespaces/extensionTypes";
import { Find } from "./namespaces/find";
import { GeckoProfiler } from "./namespaces/geckoProfiler";
import { History } from "./namespaces/history";
import { I18n } from "./namespaces/i18n";
import { Identity } from "./namespaces/identity";
import { Idle } from "./namespaces/idle";
import { Management } from "./namespaces/management";
import { Manifest } from "./namespaces/manifest";
import { ContextMenus } from "./namespaces/contextMenus";
import { Menus } from "./namespaces/menus";
import { NetworkStatus } from "./namespaces/networkStatus";
import { NormandyAddonStudy } from "./namespaces/normandyAddonStudy";
import { Notifications } from "./namespaces/notifications";
import { Omnibox } from "./namespaces/omnibox";
import { PageAction } from "./namespaces/pageAction";
import { Permissions } from "./namespaces/permissions";
import { Pkcs11 } from "./namespaces/pkcs11";
import { Privacy } from "./namespaces/privacy";
import { Proxy } from "./namespaces/proxy";
import { Runtime } from "./namespaces/runtime";
import { Search } from "./namespaces/search";
import { Sessions } from "./namespaces/sessions";
import { SidebarAction } from "./namespaces/sidebarAction";
import { Storage } from "./namespaces/storage";
import { Tabs } from "./namespaces/tabs";
import { Theme } from "./namespaces/theme";
import { TopSites } from "./namespaces/topSites";
import { Types } from "./namespaces/types";
import { Urlbar } from "./namespaces/urlbar";
import { UserScripts } from "./namespaces/userScripts";
import { WebNavigation } from "./namespaces/webNavigation";
import { WebRequest } from "./namespaces/webRequest";
import { Windows } from "./namespaces/windows";
import { Scripting } from "./namespaces/scripting";
export { ActivityLog } from "./namespaces/activityLog";
export { Alarms } from "./namespaces/alarms";
export { Bookmarks } from "./namespaces/bookmarks";
export { Action } from "./namespaces/action";
export { BrowserAction } from "./namespaces/browserAction";
export { BrowserSettings } from "./namespaces/browserSettings";
export { BrowserSettingsColorManagement } from "./namespaces/browserSettings_colorManagement";
export { BrowsingData } from "./namespaces/browsingData";
export { CaptivePortal } from "./namespaces/captivePortal";
export { Clipboard } from "./namespaces/clipboard";
export { Commands } from "./namespaces/commands";
export { ContentScripts } from "./namespaces/contentScripts";
export { ContextualIdentities } from "./namespaces/contextualIdentities";
export { Cookies } from "./namespaces/cookies";
export { DeclarativeContent } from "./namespaces/declarativeContent";
export { Devtools } from "./namespaces/devtools";
export { DevtoolsInspectedWindow } from "./namespaces/devtools_inspectedWindow";
export { DevtoolsNetwork } from "./namespaces/devtools_network";
export { DevtoolsPanels } from "./namespaces/devtools_panels";
export { Dns } from "./namespaces/dns";
export { Downloads } from "./namespaces/downloads";
export { Events } from "./namespaces/events";
export { Experiments } from "./namespaces/experiments";
export { Extension } from "./namespaces/extension";
export { ExtensionTypes } from "./namespaces/extensionTypes";
export { Find } from "./namespaces/find";
export { GeckoProfiler } from "./namespaces/geckoProfiler";
export { History } from "./namespaces/history";
export { I18n } from "./namespaces/i18n";
export { Identity } from "./namespaces/identity";
export { Idle } from "./namespaces/idle";
export { Management } from "./namespaces/management";
export { Manifest } from "./namespaces/manifest";
export { ContextMenus } from "./namespaces/contextMenus";
export { Menus } from "./namespaces/menus";
export { NetworkStatus } from "./namespaces/networkStatus";
export { NormandyAddonStudy } from "./namespaces/normandyAddonStudy";
export { Notifications } from "./namespaces/notifications";
export { Omnibox } from "./namespaces/omnibox";
export { PageAction } from "./namespaces/pageAction";
export { Permissions } from "./namespaces/permissions";
export { Pkcs11 } from "./namespaces/pkcs11";
export { Privacy } from "./namespaces/privacy";
export { PrivacyNetwork } from "./namespaces/privacy_network";
export { PrivacyServices } from "./namespaces/privacy_services";
export { PrivacyWebsites } from "./namespaces/privacy_websites";
export { Proxy } from "./namespaces/proxy";
export { Runtime } from "./namespaces/runtime";
export { Search } from "./namespaces/search";
export { Sessions } from "./namespaces/sessions";
export { SidebarAction } from "./namespaces/sidebarAction";
export { Storage } from "./namespaces/storage";
export { Tabs } from "./namespaces/tabs";
export { Theme } from "./namespaces/theme";
export { TopSites } from "./namespaces/topSites";
export { Types } from "./namespaces/types";
export { Urlbar } from "./namespaces/urlbar";
export { UserScripts } from "./namespaces/userScripts";
export { WebNavigation } from "./namespaces/webNavigation";
export { WebRequest } from "./namespaces/webRequest";
export { Windows } from "./namespaces/windows";
export { Scripting } from "./namespaces/scripting";

export interface Browser {
    activityLog: ActivityLog.Static;
    alarms: Alarms.Static;
    bookmarks: Bookmarks.Static;
    action: Action.Static;
    browserAction: BrowserAction.Static;
    browserSettings: BrowserSettings.Static;
    browsingData: BrowsingData.Static;
    captivePortal: CaptivePortal.Static;
    clipboard: Clipboard.Static;
    commands: Commands.Static;
    contentScripts: ContentScripts.Static;
    contextualIdentities: ContextualIdentities.Static;
    cookies: Cookies.Static;
    declarativeContent: DeclarativeContent.Static;
    devtools: Devtools.Static;
    dns: Dns.Static;
    downloads: Downloads.Static;
    events: Events.Static;
    experiments: Experiments.Static;
    extension: Extension.Static;
    extensionTypes: ExtensionTypes.Static;
    find: Find.Static;
    geckoProfiler: GeckoProfiler.Static;
    history: History.Static;
    i18n: I18n.Static;
    identity: Identity.Static;
    idle: Idle.Static;
    management: Management.Static;
    manifest: Manifest.Static;
    contextMenus: ContextMenus.Static;
    menus: Menus.Static;
    networkStatus: NetworkStatus.Static;
    normandyAddonStudy: NormandyAddonStudy.Static;
    notifications: Notifications.Static;
    omnibox: Omnibox.Static;
    pageAction: PageAction.Static;
    permissions: Permissions.Static;
    pkcs11: Pkcs11.Static;
    privacy: Privacy.Static;
    proxy: Proxy.Static;
    runtime: Runtime.Static;
    search: Search.Static;
    sessions: Sessions.Static;
    sidebarAction: SidebarAction.Static;
    storage: Storage.Static;
    tabs: Tabs.Static;
    theme: Theme.Static;
    topSites: TopSites.Static;
    types: Types.Static;
    urlbar: Urlbar.Static;
    userScripts: UserScripts.Static;
    webNavigation: WebNavigation.Static;
    webRequest: WebRequest.Static;
    windows: Windows.Static;
    scripting: Scripting.Static;
}

declare const browser: Browser;

export default browser;
