export const ALTER_SCHEMA: number;
export const FILE_SYNCHRONIZER: number;
export const DISCARD_DATABASE_CACHES: number;
export const ENGINE_SHUTDOWN: number;
export const CHANGE_USER_PASSWORD: number;
export const EXTERNAL_ACCESS: number;
export const MANAGE_PERMISSIONS: number;
export const VIEW_TECHNICAL_INFO: number;
export const SYSTEM_UPDATE: number;
