// TypeScript Version: 2.1
import _GoAlert from "./alert";
import _GoAlignmentAlign from "./alignment-align";
import _GoAlignmentAlignedTo from "./alignment-aligned-to";
import _GoAlignmentUnalign from "./alignment-unalign";
import _GoArrowDown from "./arrow-down";
import _GoArrowLeft from "./arrow-left";
import _GoArrowRight from "./arrow-right";
import _GoArrowSmallDown from "./arrow-small-down";
import _GoArrowSmallLeft from "./arrow-small-left";
import _GoArrowSmallRight from "./arrow-small-right";
import _GoArrowSmallUp from "./arrow-small-up";
import _GoArrowUp from "./arrow-up";
import _GoBeer from "./beer";
import _GoBook from "./book";
import _GoBookmark from "./bookmark";
import _GoBriefcase from "./briefcase";
import _GoBroadcast from "./broadcast";
import _GoBrowser from "./browser";
import _GoBug from "./bug";
import _GoCalendar from "./calendar";
import _GoCheck from "./check";
import _GoChecklist from "./checklist";
import _GoChevronDown from "./chevron-down";
import _GoChevronLeft from "./chevron-left";
import _GoChevronRight from "./chevron-right";
import _GoChevronUp from "./chevron-up";
import _GoCircleSlash from "./circle-slash";
import _GoCircuitBoard from "./circuit-board";
import _GoClippy from "./clippy";
import _GoClock from "./clock";
import _GoCloudDownload from "./cloud-download";
import _GoCloudUpload from "./cloud-upload";
import _GoCode from "./code";
import _GoColorMode from "./color-mode";
import _GoCommentDiscussion from "./comment-discussion";
import _GoComment from "./comment";
import _GoCreditCard from "./credit-card";
import _GoDash from "./dash";
import _GoDashboard from "./dashboard";
import _GoDatabase from "./database";
import _GoDeviceCameraVideo from "./device-camera-video";
import _GoDeviceCamera from "./device-camera";
import _GoDeviceDesktop from "./device-desktop";
import _GoDeviceMobile from "./device-mobile";
import _GoDiffAdded from "./diff-added";
import _GoDiffIgnored from "./diff-ignored";
import _GoDiffModified from "./diff-modified";
import _GoDiffRemoved from "./diff-removed";
import _GoDiffRenamed from "./diff-renamed";
import _GoDiff from "./diff";
import _GoEllipsis from "./ellipsis";
import _GoEye from "./eye";
import _GoFileBinary from "./file-binary";
import _GoFileCode from "./file-code";
import _GoFileDirectory from "./file-directory";
import _GoFileMedia from "./file-media";
import _GoFilePdf from "./file-pdf";
import _GoFileSubmodule from "./file-submodule";
import _GoFileSymlinkDirectory from "./file-symlink-directory";
import _GoFileSymlinkFile from "./file-symlink-file";
import _GoFileText from "./file-text";
import _GoFileZip from "./file-zip";
import _GoFlame from "./flame";
import _GoFold from "./fold";
import _GoGear from "./gear";
import _GoGift from "./gift";
import _GoGistSecret from "./gist-secret";
import _GoGist from "./gist";
import _GoGitBranch from "./git-branch";
import _GoGitCommit from "./git-commit";
import _GoGitCompare from "./git-compare";
import _GoGitMerge from "./git-merge";
import _GoGitPullRequest from "./git-pull-request";
import _GoGlobe from "./globe";
import _GoGraph from "./graph";
import _GoHeart from "./heart";
import _GoHistory from "./history";
import _GoHome from "./home";
import _GoHorizontalRule from "./horizontal-rule";
import _GoHourglass from "./hourglass";
import _GoHubot from "./hubot";
import _GoInbox from "./inbox";
import _GoInfo from "./info";
import _GoIssueClosed from "./issue-closed";
import _GoIssueOpened from "./issue-opened";
import _GoIssueReopened from "./issue-reopened";
import _GoJersey from "./jersey";
import _GoJumpDown from "./jump-down";
import _GoJumpLeft from "./jump-left";
import _GoJumpRight from "./jump-right";
import _GoJumpUp from "./jump-up";
import _GoKey from "./key";
import _GoKeyboard from "./keyboard";
import _GoLaw from "./law";
import _GoLightBulb from "./light-bulb";
import _GoLinkExternal from "./link-external";
import _GoLink from "./link";
import _GoListOrdered from "./list-ordered";
import _GoListUnordered from "./list-unordered";
import _GoLocation from "./location";
import _GoLock from "./lock";
import _GoLogoGithub from "./logo-github";
import _GoMailRead from "./mail-read";
import _GoMailReply from "./mail-reply";
import _GoMail from "./mail";
import _GoMarkGithub from "./mark-github";
import _GoMarkdown from "./markdown";
import _GoMegaphone from "./megaphone";
import _GoMention from "./mention";
import _GoMicroscope from "./microscope";
import _GoMilestone from "./milestone";
import _GoMirror from "./mirror";
import _GoMortarBoard from "./mortar-board";
import _GoMoveDown from "./move-down";
import _GoMoveLeft from "./move-left";
import _GoMoveRight from "./move-right";
import _GoMoveUp from "./move-up";
import _GoMute from "./mute";
import _GoNoNewline from "./no-newline";
import _GoOctoface from "./octoface";
import _GoOrganization from "./organization";
import _GoPackage from "./package";
import _GoPaintcan from "./paintcan";
import _GoPencil from "./pencil";
import _GoPerson from "./person";
import _GoPin from "./pin";
import _GoPlaybackFastForward from "./playback-fast-forward";
import _GoPlaybackPause from "./playback-pause";
import _GoPlaybackPlay from "./playback-play";
import _GoPlaybackRewind from "./playback-rewind";
import _GoPlug from "./plug";
import _GoPlus from "./plus";
import _GoPodium from "./podium";
import _GoPrimitiveDot from "./primitive-dot";
import _GoPrimitiveSquare from "./primitive-square";
import _GoPulse from "./pulse";
import _GoPuzzle from "./puzzle";
import _GoQuestion from "./question";
import _GoQuote from "./quote";
import _GoRadioTower from "./radio-tower";
import _GoRepoClone from "./repo-clone";
import _GoRepoForcePush from "./repo-force-push";
import _GoRepoForked from "./repo-forked";
import _GoRepoPull from "./repo-pull";
import _GoRepoPush from "./repo-push";
import _GoRepo from "./repo";
import _GoRocket from "./rocket";
import _GoRss from "./rss";
import _GoRuby from "./ruby";
import _GoScreenFull from "./screen-full";
import _GoScreenNormal from "./screen-normal";
import _GoSearch from "./search";
import _GoServer from "./server";
import _GoSettings from "./settings";
import _GoSignIn from "./sign-in";
import _GoSignOut from "./sign-out";
import _GoSplit from "./split";
import _GoSquirrel from "./squirrel";
import _GoStar from "./star";
import _GoSteps from "./steps";
import _GoStop from "./stop";
import _GoSync from "./sync";
import _GoTag from "./tag";
import _GoTelescope from "./telescope";
import _GoTerminal from "./terminal";
import _GoThreeBars from "./three-bars";
import _GoTools from "./tools";
import _GoTrashcan from "./trashcan";
import _GoTriangleDown from "./triangle-down";
import _GoTriangleLeft from "./triangle-left";
import _GoTriangleRight from "./triangle-right";
import _GoTriangleUp from "./triangle-up";
import _GoUnfold from "./unfold";
import _GoUnmute from "./unmute";
import _GoVersions from "./versions";
import _GoX from "./x";
import _GoZap from "./zap";
export var GoAlert: typeof _GoAlert;
export var GoAlignmentAlign: typeof _GoAlignmentAlign;
export var GoAlignmentAlignedTo: typeof _GoAlignmentAlignedTo;
export var GoAlignmentUnalign: typeof _GoAlignmentUnalign;
export var GoArrowDown: typeof _GoArrowDown;
export var GoArrowLeft: typeof _GoArrowLeft;
export var GoArrowRight: typeof _GoArrowRight;
export var GoArrowSmallDown: typeof _GoArrowSmallDown;
export var GoArrowSmallLeft: typeof _GoArrowSmallLeft;
export var GoArrowSmallRight: typeof _GoArrowSmallRight;
export var GoArrowSmallUp: typeof _GoArrowSmallUp;
export var GoArrowUp: typeof _GoArrowUp;
export var GoBeer: typeof _GoBeer;
export var GoBook: typeof _GoBook;
export var GoBookmark: typeof _GoBookmark;
export var GoBriefcase: typeof _GoBriefcase;
export var GoBroadcast: typeof _GoBroadcast;
export var GoBrowser: typeof _GoBrowser;
export var GoBug: typeof _GoBug;
export var GoCalendar: typeof _GoCalendar;
export var GoCheck: typeof _GoCheck;
export var GoChecklist: typeof _GoChecklist;
export var GoChevronDown: typeof _GoChevronDown;
export var GoChevronLeft: typeof _GoChevronLeft;
export var GoChevronRight: typeof _GoChevronRight;
export var GoChevronUp: typeof _GoChevronUp;
export var GoCircleSlash: typeof _GoCircleSlash;
export var GoCircuitBoard: typeof _GoCircuitBoard;
export var GoClippy: typeof _GoClippy;
export var GoClock: typeof _GoClock;
export var GoCloudDownload: typeof _GoCloudDownload;
export var GoCloudUpload: typeof _GoCloudUpload;
export var GoCode: typeof _GoCode;
export var GoColorMode: typeof _GoColorMode;
export var GoCommentDiscussion: typeof _GoCommentDiscussion;
export var GoComment: typeof _GoComment;
export var GoCreditCard: typeof _GoCreditCard;
export var GoDash: typeof _GoDash;
export var GoDashboard: typeof _GoDashboard;
export var GoDatabase: typeof _GoDatabase;
export var GoDeviceCameraVideo: typeof _GoDeviceCameraVideo;
export var GoDeviceCamera: typeof _GoDeviceCamera;
export var GoDeviceDesktop: typeof _GoDeviceDesktop;
export var GoDeviceMobile: typeof _GoDeviceMobile;
export var GoDiffAdded: typeof _GoDiffAdded;
export var GoDiffIgnored: typeof _GoDiffIgnored;
export var GoDiffModified: typeof _GoDiffModified;
export var GoDiffRemoved: typeof _GoDiffRemoved;
export var GoDiffRenamed: typeof _GoDiffRenamed;
export var GoDiff: typeof _GoDiff;
export var GoEllipsis: typeof _GoEllipsis;
export var GoEye: typeof _GoEye;
export var GoFileBinary: typeof _GoFileBinary;
export var GoFileCode: typeof _GoFileCode;
export var GoFileDirectory: typeof _GoFileDirectory;
export var GoFileMedia: typeof _GoFileMedia;
export var GoFilePdf: typeof _GoFilePdf;
export var GoFileSubmodule: typeof _GoFileSubmodule;
export var GoFileSymlinkDirectory: typeof _GoFileSymlinkDirectory;
export var GoFileSymlinkFile: typeof _GoFileSymlinkFile;
export var GoFileText: typeof _GoFileText;
export var GoFileZip: typeof _GoFileZip;
export var GoFlame: typeof _GoFlame;
export var GoFold: typeof _GoFold;
export var GoGear: typeof _GoGear;
export var GoGift: typeof _GoGift;
export var GoGistSecret: typeof _GoGistSecret;
export var GoGist: typeof _GoGist;
export var GoGitBranch: typeof _GoGitBranch;
export var GoGitCommit: typeof _GoGitCommit;
export var GoGitCompare: typeof _GoGitCompare;
export var GoGitMerge: typeof _GoGitMerge;
export var GoGitPullRequest: typeof _GoGitPullRequest;
export var GoGlobe: typeof _GoGlobe;
export var GoGraph: typeof _GoGraph;
export var GoHeart: typeof _GoHeart;
export var GoHistory: typeof _GoHistory;
export var GoHome: typeof _GoHome;
export var GoHorizontalRule: typeof _GoHorizontalRule;
export var GoHourglass: typeof _GoHourglass;
export var GoHubot: typeof _GoHubot;
export var GoInbox: typeof _GoInbox;
export var GoInfo: typeof _GoInfo;
export var GoIssueClosed: typeof _GoIssueClosed;
export var GoIssueOpened: typeof _GoIssueOpened;
export var GoIssueReopened: typeof _GoIssueReopened;
export var GoJersey: typeof _GoJersey;
export var GoJumpDown: typeof _GoJumpDown;
export var GoJumpLeft: typeof _GoJumpLeft;
export var GoJumpRight: typeof _GoJumpRight;
export var GoJumpUp: typeof _GoJumpUp;
export var GoKey: typeof _GoKey;
export var GoKeyboard: typeof _GoKeyboard;
export var GoLaw: typeof _GoLaw;
export var GoLightBulb: typeof _GoLightBulb;
export var GoLinkExternal: typeof _GoLinkExternal;
export var GoLink: typeof _GoLink;
export var GoListOrdered: typeof _GoListOrdered;
export var GoListUnordered: typeof _GoListUnordered;
export var GoLocation: typeof _GoLocation;
export var GoLock: typeof _GoLock;
export var GoLogoGithub: typeof _GoLogoGithub;
export var GoMailRead: typeof _GoMailRead;
export var GoMailReply: typeof _GoMailReply;
export var GoMail: typeof _GoMail;
export var GoMarkGithub: typeof _GoMarkGithub;
export var GoMarkdown: typeof _GoMarkdown;
export var GoMegaphone: typeof _GoMegaphone;
export var GoMention: typeof _GoMention;
export var GoMicroscope: typeof _GoMicroscope;
export var GoMilestone: typeof _GoMilestone;
export var GoMirror: typeof _GoMirror;
export var GoMortarBoard: typeof _GoMortarBoard;
export var GoMoveDown: typeof _GoMoveDown;
export var GoMoveLeft: typeof _GoMoveLeft;
export var GoMoveRight: typeof _GoMoveRight;
export var GoMoveUp: typeof _GoMoveUp;
export var GoMute: typeof _GoMute;
export var GoNoNewline: typeof _GoNoNewline;
export var GoOctoface: typeof _GoOctoface;
export var GoOrganization: typeof _GoOrganization;
export var GoPackage: typeof _GoPackage;
export var GoPaintcan: typeof _GoPaintcan;
export var GoPencil: typeof _GoPencil;
export var GoPerson: typeof _GoPerson;
export var GoPin: typeof _GoPin;
export var GoPlaybackFastForward: typeof _GoPlaybackFastForward;
export var GoPlaybackPause: typeof _GoPlaybackPause;
export var GoPlaybackPlay: typeof _GoPlaybackPlay;
export var GoPlaybackRewind: typeof _GoPlaybackRewind;
export var GoPlug: typeof _GoPlug;
export var GoPlus: typeof _GoPlus;
export var GoPodium: typeof _GoPodium;
export var GoPrimitiveDot: typeof _GoPrimitiveDot;
export var GoPrimitiveSquare: typeof _GoPrimitiveSquare;
export var GoPulse: typeof _GoPulse;
export var GoPuzzle: typeof _GoPuzzle;
export var GoQuestion: typeof _GoQuestion;
export var GoQuote: typeof _GoQuote;
export var GoRadioTower: typeof _GoRadioTower;
export var GoRepoClone: typeof _GoRepoClone;
export var GoRepoForcePush: typeof _GoRepoForcePush;
export var GoRepoForked: typeof _GoRepoForked;
export var GoRepoPull: typeof _GoRepoPull;
export var GoRepoPush: typeof _GoRepoPush;
export var GoRepo: typeof _GoRepo;
export var GoRocket: typeof _GoRocket;
export var GoRss: typeof _GoRss;
export var GoRuby: typeof _GoRuby;
export var GoScreenFull: typeof _GoScreenFull;
export var GoScreenNormal: typeof _GoScreenNormal;
export var GoSearch: typeof _GoSearch;
export var GoServer: typeof _GoServer;
export var GoSettings: typeof _GoSettings;
export var GoSignIn: typeof _GoSignIn;
export var GoSignOut: typeof _GoSignOut;
export var GoSplit: typeof _GoSplit;
export var GoSquirrel: typeof _GoSquirrel;
export var GoStar: typeof _GoStar;
export var GoSteps: typeof _GoSteps;
export var GoStop: typeof _GoStop;
export var GoSync: typeof _GoSync;
export var GoTag: typeof _GoTag;
export var GoTelescope: typeof _GoTelescope;
export var GoTerminal: typeof _GoTerminal;
export var GoThreeBars: typeof _GoThreeBars;
export var GoTools: typeof _GoTools;
export var GoTrashcan: typeof _GoTrashcan;
export var GoTriangleDown: typeof _GoTriangleDown;
export var GoTriangleLeft: typeof _GoTriangleLeft;
export var GoTriangleRight: typeof _GoTriangleRight;
export var GoTriangleUp: typeof _GoTriangleUp;
export var GoUnfold: typeof _GoUnfold;
export var GoUnmute: typeof _GoUnmute;
export var GoVersions: typeof _GoVersions;
export var GoX: typeof _GoX;
export var GoZap: typeof _GoZap;