export let ERROR: number;
export let UNBLOCKED: number;
export let SERVER_WAITING_FOR_CLIENT_ACKNOWLEDGMENT: number;
export let CLIENT_WAITING_FOR_SERVER_ACKNOWLEDGMENT: number;
export let SERVER_WAITING_FOR_RESULT: number;
export let CLIENT_WAITING_FOR_RESULT_CONFIRMATION: number;
export let SERVER_WAITING_FOR_UNBLOCKED_STATE: number;
export let CLIENT_WAITING_FOR_PROCESS_RETRY: number;
export let ABORT: number;
