export const ERROR: number;
export const UNBLOCKED: number;
export const SERVER_WAITING_FOR_CLIENT_ACKNOWLEDGMENT: number;
export const CLIENT_WAITING_FOR_SERVER_ACKNOWLEDGMENT: number;
export const SERVER_WAITING_FOR_RESULT: number;
export const CLIENT_WAITING_FOR_RESULT_CONFIRMATION: number;
export const SERVER_WAITING_FOR_UNBLOCKED_STATE: number;
export const CLIENT_WAITING_FOR_PROCESS_RETRY: number;
export const ABORT: number;
