export type exports = string;
declare let STRING: string;
declare let CHAR: string;
declare let DATE: string;
declare let INT32: string;
declare let INT64: string;
declare let NUMBER: string;
declare let ARRAY: string;
declare let MEMO: string;
declare let COMBO: string;
declare let MASTER_DETAIL: string;
declare let BOOLEAN: string;
declare let PHONE: string;
declare let FILE: string;
declare let PASSWORD: string;
declare let TIME: string;
declare let DATETIME: string;
declare let CEP: string;
declare let LATITUDE: string;
declare let LONGITUDE: string;
declare let ANGLE: string;
declare let GRID: string;
declare let INTEGER: string;
export {};
