export type exports = string;
declare let EQUALITY: string;
declare let INEQUALITY: string;
declare let GREATER_THAN: string;
declare let LESS_THAN: string;
declare let GREATER_THAN_OR_EQUAL: string;
declare let LESS_THAN_OR_EQUAL: string;
declare let LIKE: string;
declare let EXISTS: string;
declare let NOT_EXISTS: string;
export {};
