export type exports = string;
declare const EQUALITY: string;
declare const INEQUALITY: string;
declare const GREATER_THAN: string;
declare const LESS_THAN: string;
declare const GREATER_THAN_OR_EQUAL: string;
declare const LESS_THAN_OR_EQUAL: string;
declare const LIKE: string;
declare const EXISTS: string;
declare const NOT_EXISTS: string;
export {};
