// Original file: https://json.schemastore.org/xs-app.json
// Online converter: https://bcherny.github.io/json-schema-to-typescript-browser/
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type SourceSchema =
    | string
    | {
        path: string;
        matchCase?: boolean;
    };
export type ScopesSchema =
    | string
    | [string, ...string[]]
    | {
        GET?: ScopeTemplate;
        POST?: ScopeTemplate;
        HEAD?: ScopeTemplate;
        PUT?: ScopeTemplate;
        DELETE?: ScopeTemplate;
        TRACE?: ScopeTemplate;
        PATCH?: ScopeTemplate;
        OPTIONS?: ScopeTemplate;
        CONNECT?: ScopeTemplate;
        default?: ScopeTemplate;
    };
export type ScopeTemplate = string | [string, ...string[]];

export type HttpMethod = "DELETE" | "GET" | "HEAD" | "OPTIONS" | "POST" | "PUT" | "TRACE" | "PATCH";

export type ErrorPageEntry =
    | { status: number | [number, ...number[]]; file: string; path?: never }
    | { status: number | [number, ...number[]]; path: string; file?: never };

export interface CorsConfig {
    uriPattern: SourceSchema;
    hostPattern?: string;
    allowedOrigin: Array<{ host: string; protocol?: string; port?: number }>;
    allowedMethods?: HttpMethod[];
    allowedHeaders?: string[];
    allowedCredentials?: boolean;
    exposeHeaders?: string[];
    maxAge?: number;
}

/**
 * Application Router Configuration Schema
 */
export interface ComSapXsappSchema_82 {
    welcomeFile?: string;
    authenticationMethod?: "none" | "route";
    stateProtection?: boolean;
    sessionTimeout?: number;
    pluginMetadataEndpoint?: string;
    routes?: Array<{
        source: SourceSchema;
        httpMethods?: [
            HttpMethod,
            ...HttpMethod[],
        ];
        target?: string;
        destination?: string;
        setBackendSessionCookies?: boolean;
        localDir?: string;
        csrfProtection?: boolean;
        preferLocal?: boolean;
        service?: string;
        endpoint?: string;
        authenticationType?: "xsuaa" | "ias" | "basic" | "none";
        identityProvider?: string;
        dynamicIdentityProvider?: boolean;
        scope?: ScopesSchema;
        replace?: {
            pathSuffixes: string[];
            vars?: string[];
            services?: {
                [k: string]: unknown;
            };
        };
        cacheControl?: string;
    }>;
    responseHeaders?: Array<{
        name: string;
        value: string;
    }>;
    destinations?: {
        [k: string]: {
            logoutPath?: string;
            logoutMethod?: "PUT" | "POST" | "GET";
        };
    };
    services?: {
        [k: string]: {
            endpoint?: string;
            logoutPath?: string;
            logoutMethod?: "PUT" | "POST" | "GET";
        };
    };
    logout?: {
        backChannelLogoutEndpoint?: string;
        logoutEndpoint?: string;
        logoutPage?: string;
        logoutMethod?: "POST" | "GET";
        csrfProtection?: boolean;
    };
    login?: {
        callbackEndpoint: string;
    };
    whitelistService?: {
        endpoint: string;
    };
    compression?: {
        enabled?: boolean;
        minSize?: number;
        compressResponseMixedTypeContent?: boolean;
    };
    websockets?: {
        enabled: boolean;
    };
    errorPage?: ErrorPageEntry[];
    cors?: CorsConfig[];
}
