export class StreamManagerException extends Error {}
export class ClientException extends StreamManagerException {}
export class ConnectFailedException extends ClientException {}
export class InvalidRequestException extends StreamManagerException {}
export class MessageStoreReadErrorException extends StreamManagerException {}
export class NotEnoughMessagesException extends StreamManagerException {}
export class RequestPayloadTooLargeException extends StreamManagerException {}
export class ResourceNotFoundException extends StreamManagerException {}
export class ResponsePayloadTooLargeException extends StreamManagerException {}
export class ServerOutOfMemoryException extends StreamManagerException {}
export class ServerTimeoutException extends StreamManagerException {}
export class UnauthorizedException extends StreamManagerException {}
export class UnknownFailureException extends StreamManagerException {}
export class UpdateFailedException extends StreamManagerException {}
export class UnknownOperationException extends StreamManagerException {}
export class UpdateNotAllowedException extends InvalidRequestException {}
export class ValidationException extends ClientException {}
