/// <reference path="./mozilla-spidermonkey-parser-api.d.ts" />

var literal:spiderMonkeyParserAPI.Syntax.Literal = {
    loc: {
        source: null,
        start: {
            line: 1,
            column: 10
        },
        end: {
            line: 1,
            column: 12
        }
    },
    type: "Literal",
    value: 42
};

// generated by http://esprima.org/demo/parse.html?code=%22use%20strict%22%3B%0A%0Afunction%20Test%20()%20%7B%0A%7D%0A%0ATest.prototype.hello%20%3D%20function(word)%20%7B%0A%09word%20%3D%20word%20%7C%7C%20%22TypeScript%22%3B%0A%09return%20word%3B%0A%7D%3B%0A
var program:spiderMonkeyParserAPI.Syntax.Program = {
    "type": "Program",
    "body": [
        <spiderMonkeyParserAPI.Syntax.Expression>{
            "type": "ExpressionStatement",
            "expression": <spiderMonkeyParserAPI.Syntax.Literal>{
                "type": "Literal",
                "value": "use strict",
                "raw": "\"use strict\""
            }
        },
        <spiderMonkeyParserAPI.Syntax.FunctionDeclaration>{
            "type": "FunctionDeclaration",
            "id": <spiderMonkeyParserAPI.Syntax.Identifier>{
                "type": "Identifier",
                "name": "Test"
            },
            "params": [],
            "defaults": [],
            "body": <spiderMonkeyParserAPI.Syntax.BlockStatement>{
                "type": "BlockStatement",
                "body": []
            },
            "rest": null,
            "generator": false,
            "expression": false
        },
        <spiderMonkeyParserAPI.Syntax.Expression>{
            "type": "ExpressionStatement",
            "expression": <spiderMonkeyParserAPI.Syntax.AssignmentExpression>{
                "type": "AssignmentExpression",
                "operator": "=",
                "left": <spiderMonkeyParserAPI.Syntax.MemberExpression>{
                    "type": "MemberExpression",
                    "computed": false,
                    "object": <spiderMonkeyParserAPI.Syntax.MemberExpression>{
                        "type": "MemberExpression",
                        "computed": false,
                        "object": <spiderMonkeyParserAPI.Syntax.Identifier>{
                            "type": "Identifier",
                            "name": "Test"
                        },
                        "property": <spiderMonkeyParserAPI.Syntax.Identifier>{
                            "type": "Identifier",
                            "name": "prototype"
                        }
                    },
                    "property": <spiderMonkeyParserAPI.Syntax.Identifier>{
                        "type": "Identifier",
                        "name": "hello"
                    }
                },
                "right": <spiderMonkeyParserAPI.Syntax.FunctionExpression>{
                    "type": "FunctionExpression",
                    "id": null,
                    "params": [
                        <spiderMonkeyParserAPI.Syntax.Identifier>{
                            "type": "Identifier",
                            "name": "word"
                        }
                    ],
                    "defaults": [],
                    "body": <spiderMonkeyParserAPI.Syntax.BlockStatement>{
                        "type": "BlockStatement",
                        "body": [
                            <spiderMonkeyParserAPI.Syntax.Expression>{
                                "type": "ExpressionStatement",
                                "expression": <spiderMonkeyParserAPI.Syntax.AssignmentExpression>{
                                    "type": "AssignmentExpression",
                                    "operator": "=",
                                    "left": <spiderMonkeyParserAPI.Syntax.Identifier>{
                                        "type": "Identifier",
                                        "name": "word"
                                    },
                                    "right": <spiderMonkeyParserAPI.Syntax.LogicalExpression>{
                                        "type": "LogicalExpression",
                                        "operator": "||",
                                        "left": <spiderMonkeyParserAPI.Syntax.Identifier>{
                                            "type": "Identifier",
                                            "name": "word"
                                        },
                                        "right": <spiderMonkeyParserAPI.Syntax.Literal>{
                                            "type": "Literal",
                                            "value": "TypeScript",
                                            "raw": "\"TypeScript\""
                                        }
                                    }
                                }
                            },
                            <spiderMonkeyParserAPI.Syntax.ReturnStatement>{
                                "type": "ReturnStatement",
                                "argument": {
                                    "type": "Identifier",
                                    "name": "word"
                                }
                            }
                        ]
                    },
                    "rest": null,
                    "generator": false,
                    "expression": false
                }
            }
        }
    ]
};
