import { Application } from "./api/application/application";
import Fin from "./api/fin";
import { _Frame as Frame } from "./api/frame/frame";
import { ChannelClient } from "./api/interappbus/channel/client";
import { ChannelProvider } from "./api/interappbus/channel/provider";
import { _Notification as Notification } from "./api/notification/notification";
import System from "./api/system/system";
import { View } from "./api/view/view";
import { _Window as Window } from "./api/window/window";
import { ConnectConfig } from "./transport/wire";
export declare function connect(config: ConnectConfig): Promise<Fin>;
export declare function launch(config: ConnectConfig): Promise<number>;
export { Identity } from "./identity";
export { Application, ChannelClient, ChannelProvider, Fin, Frame, Notification, System, View, Window };
