// Type definitions for webgme v2.6.0 
// Project: https://webgme.org
// Definitions by: Fred Eisele <https://github.com/phreed>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped

/// <reference types="node" />

/// <reference path="webgme-util.d.ts" />
/// <reference path="webgme-blob.d.ts" />
/// <reference path="webgme-core.d.ts" />
/// <reference path="webgme-config.d.ts" />
/// <reference path="webgme-v1.d.ts" />

/**
### 2.6.0 Changelog (https://webgme.org)

#### TODO:

Add

- [x] _.first as an alias of _.head

*/
// Generated by typings
// Based on examination of
// Example: https://github.com/typed-typings/env-node/blob/master/0.12/node.d.ts
// Source: https://raw.githubusercontent.com/phreed/typed-npm-webgme/master/webgme.d.ts
// Documentation: https://editor.webgme.org/docs/source/index.html

declare module 'blob/BlobMetadata' {
    export default class BlobMetadata implements Blob.BlobMetadata {
        constructor();
        name: string;
        size: number;
        mime: string;
        context: Core.DataObject;
        contentType: string;
    }
}

declare module 'blob/util' {
    export default class Util implements Blob.Util {
        constructor();
    }
}

declare module "plugin/PluginBase" {
    export = Core.PluginBase;
}

declare module "plugin/PluginConfig" {
    export = Config.PluginConfig;
}

declare module "webgme/config/config.default" {
    export = Config.config;
}

declare module "common/util/canon" {
    export = Util.CANON;
}

declare module "common/util/assert" {
    export = Util.ASSERT;
}
