import vCardsJS = require("vcards-js");

const vCard = vCardsJS();
vCard.firstName = "Eric";
vCard.middleName = "J";
vCard.lastName = "Nesser";
vCard.uid = "69531f4a-c34d-4a1e-8922-bd38a9476a53";
vCard.organization = "ACME Corporation";
vCard.photo.attachFromUrl("https://avatars2.githubusercontent.com/u/5659221?v=3&s=460", "JPEG");
vCard.workPhone = "312-555-1212";
vCard.birthday = new Date(1985, 0, 1);
vCard.title = "Software Developer";
vCard.url = "https://github.com/enesser";
vCard.workUrl = "https://acme-corporation/enesser";
vCard.note = "Notes on Eric";
vCard.nickname = "Scarface";
vCard.namePrefix = "Mr.";
vCard.nameSuffix = "JR";
vCard.gender = "M";
vCard.anniversary = new Date(2004, 0, 1);
vCard.role = "Software Development";
vCard.homePhone = "312-555-1313";
vCard.cellPhone = "312-555-1414";
vCard.pagerPhone = "312-555-1515";
vCard.homeFax = "312-555-1616";
vCard.workFax = "312-555-1717";
vCard.email = "e.nesser@emailhost.tld";
vCard.workEmail = "e.nesser@acme-corporation.tld";
vCard.logo.attachFromUrl("https://avatars2.githubusercontent.com/u/5659221?v=3&s=460", "JPEG");
vCard.source = "http://mywebpage/myvcard.vcf";
vCard.homeAddress.label = "Home Address";
vCard.homeAddress.street = "123 Main Street";
vCard.homeAddress.city = "Chicago";
vCard.homeAddress.stateProvince = "IL";
vCard.homeAddress.postalCode = "12345";
vCard.homeAddress.countryRegion = "United States of America";
vCard.workAddress.label = "Work Address";
vCard.workAddress.street = "123 Corporate Loop\nSuite 500";
vCard.workAddress.city = "Los Angeles";
vCard.workAddress.stateProvince = "CA";
vCard.workAddress.postalCode = "54321";
vCard.workAddress.countryRegion = "United States of America";
vCard.socialUrls["facebook"] = "https://...";
vCard.socialUrls["linkedIn"] = "https://...";
vCard.socialUrls["twitter"] = "https://...";
vCard.socialUrls["flickr"] = "https://...";
vCard.socialUrls["custom"] = "https://...";
vCard.photo.embedFromFile("photo.jpg");
vCard.logo.embedFromFile("logo.jpg");
vCard.version = "3.0";
vCard.saveToFile("./eric-nesser.vcf");
vCard.email = ["e.nesser@emailhost.tld", "e.nesser@emailhost2.tld", "e.nesser@emailhost3.tld"];
vCard.cellPhone = ["312-555-1414", "312-555-1415", "312-555-1416"];
vCard.workEmail = ["e.nesser@emailhost.tld", "e.nesser@emailhost2.tld", "e.nesser@emailhost3.tld"];
