import Complex from "complex.js";

Complex.ZERO;
Complex.PI;
Complex.E;
Complex.I;
Complex.INFINITY;
Complex.EPSILON;
Complex.ONE;
Complex.NAN;

new Complex(1, 0);
new Complex(Complex.I);
new Complex(1, 0).abs();
new Complex(1, 0).acos();
new Complex(1, 0).acot();
new Complex(1, 0).acoth();
new Complex(1, 0).acsc();
new Complex(1, 0).acsch();
new Complex(1, 0).add(1, 2);
new Complex(1, 0).add(Complex.I);
new Complex(1, 0).arg();
new Complex(1, 0).asec();
new Complex(1, 0).asech();
new Complex(1, 0).asin();
new Complex(1, 0).asinh();
new Complex(1, 0).atan();
new Complex(1, 0).atanh();
new Complex(1, 0).ceil(5);
new Complex(1, 0).clone();
new Complex(1, 0).conjugate();
new Complex(1, 0).cos();
new Complex(1, 0).cosh();
new Complex(1, 0).cot();
new Complex(1, 0).coth();
new Complex(1, 0).csc();
new Complex(1, 0).csch();
new Complex(1, 0).div(3, 1);
new Complex(1, 0).div(Complex.I);
new Complex(1, 0).equals(5, 3);
new Complex(1, 0).equals(new Complex(5, 3));
new Complex(1, 0).exp();
new Complex(1, 0).floor(6);
new Complex(1, 0).inverse();
new Complex(1, 0).isFinite();
new Complex(1, 0).isInfinite();
new Complex(1, 0).isNaN();
new Complex(1, 0).isZero();
new Complex(1, 0).log();
new Complex(1, 0).mul(3, 1);
new Complex(1, 0).mul(Complex.I);
new Complex(1, 0).neg();
new Complex(1, 0).pow(1, 2);
new Complex(1, 0).pow(Complex.I);
new Complex(1, 0).round(3);
new Complex(1, 0).sec();
new Complex(1, 0).sech();
new Complex(1, 0).sign();
new Complex(1, 0).sin();
new Complex(1, 0).sinh();
new Complex(1, 0).sqrt();
new Complex(1, 0).sub(5, 1);
new Complex(1, 0).sub(Complex.I);
new Complex(1, 0).tan();
new Complex(1, 0).tanh();
new Complex(1, 0).toString();
new Complex(1, 0).toVector();
new Complex(1, 0).valueOf();
