import type { JavaClass } from "./JavaClass";
// https://ghidra.re/ghidra_docs/api/ghidra/program/model/address/AddressSpace.html
export interface AddressSpace extends JavaClass {
    add(addr: Address, displacement: number): Address;
    addNoWrap(addr: Address, displacement: number): Address;
    addWrap(addr: Address, displacement: number): Address;
    addWrapSpace(addr: Address, displacement: number): Address;
    getAddress(byteOffset: number): Address;
    getAddress(offset: number, isAddressableWordOffset: boolean): Address;
    getAddress(addrString: string): Address;
    getAddress(addrString: string, caseSensitive: boolean): Address;
    getAddressableUnitSize(): number;
    getAddressableWordOffset(byteOffset: number): number;
    getAddressInThisSpaceOnly(byteOffset: number): Address;
    getMaxAddress(): Address;
    getMinAddress(): Address;
    getName(): string;
    getOverlayAddress(addr: Address): Address;
    getPhysicalSpace(): AddressSpace;
    getPonumbererSize(): number;
    getSize(): number;
    getSpaceID(): number;
    getTruncatedAddress(offset: number, isAddressableWordOffset: boolean): Address;
    getType(): number;
    getUnique(): number;
    hasMappedRegisters(): boolean;
    hasSignedOffset(): boolean;
    isConstantSpace(): boolean;
    isExternalSpace(): boolean;
    isHashSpace(): boolean;
    isLoadedMemorySpace(): boolean;
    isMemorySpace(): boolean;
    isNonLoadedMemorySpace(): boolean;
    isOverlaySpace(): boolean;
    isRegisterSpace(): boolean;
    isStackSpace(): boolean;
    isSuccessor(addr1: Address, addr2: Address): boolean;
    isUniqueSpace(): boolean;
    isValidRange(byteOffset: number, length: number): boolean;
    isVariableSpace(): boolean;
    makeValidOffset(offset: number): number;
    showSpaceName(): boolean;
    subtract(addr: Address, displacement: number): Address;
    subtract(addr1: Address, addr2: Address): number;
    subtractNoWrap(addr: Address, displacement: number): Address;
    subtractWrap(addr: Address, displacement: number): Address;
    subtractWrapSpace(addr: Address, displacement: number): Address;
    truncateAddressableWordOffset(wordOffset: number): number;
    truncateOffset(byteOffset: number): number;
}

// https://ghidra.re/ghidra_docs/api/ghidra/program/model/address/Address.html
export interface Address extends JavaClass {
    add(displacement: number): Address;
    addNoWrap(displacement: number): Address;
    addNoWrap(displacement: bigint): Address;
    addWrap(displacement: number): Address;
    addWrapSpace(displacement: number): Address;
    equals(o: any): boolean;
    getAddress(addrString: string): Address;
    getAddressableWordOffset(): number;
    getAddressSpace(): AddressSpace;
    getNewAddress(byteOffset: number): Address;
    getNewAddress(offset: number, isAddressableWordOffset: boolean): Address;
    getNewTruncatedAddress(offset: number, isAddressableWordOffset: boolean): Address;
    getOffset(): number;
    getOffsetAsbigint(): bigint;
    getPhysicalAddress(): Address;
    getPointerSize(): number;
    getSize(): number;
    getUnsignedOffset(): number;
    hashCode(): number;
    hasSameAddressSpace(addr: Address): boolean;
    isConstantAddress(): boolean;
    isExternalAddress(): boolean;
    isHashAddress(): boolean;
    isLoadedMemoryAddress(): boolean;
    isMemoryAddress(): boolean;
    isNonLoadedMemoryAddress(): boolean;
    isRegisterAddress(): boolean;
    isStackAddress(): boolean;
    isSuccessor(addr: Address): boolean;
    isUniqueAddress(): boolean;
    isVariableAddress(): boolean;
    max(a: Address, b: Address): Address;
    min(a: Address, b: Address): Address;
    next(): Address;
    previous(): Address;
    subtract(displacement: number): Address;
    subtract(addr: Address): number;
    subtractNoWrap(displacement: number): Address;
    subtractWrap(displacement: number): Address;
    subtractWrapSpace(displacement: number): Address;
    toString(): string;
    toString(showAddressSpace: boolean): string;
    toString(showAddressSpace: boolean, pad: boolean): string;
    toString(showAddressSpace: boolean, minNumDigits: number): string;
    toString(prefix: string): string;
    // compareTo(addr: Address): number; // inherited from Comparable
}
