// auto generated Enums

export enum EAppInfoSection {
    Unknown = 0,
    All = 1,
    First = 2,
    Common = 2,
    Extended = 3,
    Config = 4,
    Stats = 5,
    Install = 6,
    Depots = 7,
    VAC = 8,
    VAC_UNUSED = 8,
    DRM = 9,
    DRM_UNUSED = 9,
    UFS = 10,
    OGG = 11,
    Items = 12,
    ItemsUNUSED = 12,
    Policies = 13,
    SysReqs = 14,
    Community = 15,
    Store = 16,
    Localization = 17,
    Broadcastgamedata = 18,
    Computed = 19,
    Albummetadata = 20,
}
