declare const EChatAction: {
	"InviteChat": 1,
	"Kick": 2,
	"Ban": 3,
	"UnBan": 4,
	"StartVoiceSpeak": 5,
	"EndVoiceSpeak": 6,
	"LockChat": 7,
	"UnlockChat": 8,
	"CloseChat": 9,
	"SetJoinable": 10,
	"SetUnjoinable": 11,
	"SetOwner": 12,
	"SetInvisibleToFriends": 13,
	"SetVisibleToFriends": 14,
	"SetModerated": 15,
	"SetUnmoderated": 16,

	// Value-to-name mapping for convenience
	"1": "InviteChat",
	"2": "Kick",
	"3": "Ban",
	"4": "UnBan",
	"5": "StartVoiceSpeak",
	"6": "EndVoiceSpeak",
	"7": "LockChat",
	"8": "UnlockChat",
	"9": "CloseChat",
	"10": "SetJoinable",
	"11": "SetUnjoinable",
	"12": "SetOwner",
	"13": "SetInvisibleToFriends",
	"14": "SetVisibleToFriends",
	"15": "SetModerated",
	"16": "SetUnmoderated",
};

export = EChatAction;
