// auto generated Enums

export enum EControllerElementType {
    None = -1,
    Thumb = 0,
    ButtonSteam = 1,
    JoystickLeft = 2,
    ButtonJoystickLeft = 3,
    JoystickRight = 4,
    ButtonJoystickRight = 5,
    DPad = 6,
    ButtonA = 7,
    ButtonB = 8,
    ButtonX = 9,
    ButtonY = 10,
    ButtonSelect = 11,
    ButtonStart = 12,
    ButtonTriggerLeft = 13,
    ButtonTriggerRight = 14,
    ButtonBumperLeft = 15,
    ButtonBumperRight = 16,
    ButtonMacro0 = 17,
    ButtonMacro1 = 18,
    ButtonMacro2 = 19,
    ButtonMacro3 = 20,
    ButtonMacro4 = 21,
    ButtonMacro5 = 22,
    ButtonMacro6 = 23,
    ButtonMacro7 = 24,
    TrackpadCenter = 25,
    TrackpadLeft = 26,
    TrackpadRight = 27,
    Keyboard = 28,
    MagnifyingGlass = 29,
    ButtonMacro1Finger = 30,
    ButtonMacro2Finger = 31,
    RecordInput = 32,
    PlaybackInput = 33,
    Paste = 34,
    Max = 35,
}
