declare const EDisplayStatus: {
	"Invalid": 0,
	"Launching": 1,
	"Uninstalling": 2,
	"Installing": 3,
	"Running": 4,
	"Validating": 5,
	"Updating": 6,
	"Downloading": 7,
	"Synchronizing": 8,
	"ReadyToInstall": 9,
	"ReadyToPreload": 10,
	"ReadyToLaunch": 11,
	"RegionRestricted": 12,
	"PresaleOnly": 13,
	"InvalidPlatform": 14,
	"ParentalBlocked": 15, // removed
	"PreloadOnly": 16, // obsolete
	"PreloadComplete": 16,
	"BorrowerLocked": 17,
	"UpdatePaused": 18,
	"UpdateQueued": 19,
	"UpdateRequired": 20,
	"UpdateDisabled": 21,
	"DownloadPaused": 22,
	"DownloadQueued": 23,
	"DownloadRequired": 24,
	"DownloadDisabled": 25,
	"LicensePending": 26,
	"LicenseExpired": 27,
	"AvailForFree": 28,
	"AvailToBorrow": 29,
	"AvailGuestPass": 30,
	"Purchase": 31,

	// Value-to-name mapping for convenience
	"0": "Invalid",
	"1": "Launching",
	"2": "Uninstalling",
	"3": "Installing",
	"4": "Running",
	"5": "Validating",
	"6": "Updating",
	"7": "Downloading",
	"8": "Synchronizing",
	"9": "ReadyToInstall",
	"10": "ReadyToPreload",
	"11": "ReadyToLaunch",
	"12": "RegionRestricted",
	"13": "PresaleOnly",
	"14": "InvalidPlatform",
	"15": "ParentalBlocked",
	"16": "PreloadComplete",
	"17": "BorrowerLocked",
	"18": "UpdatePaused",
	"19": "UpdateQueued",
	"20": "UpdateRequired",
	"21": "UpdateDisabled",
	"22": "DownloadPaused",
	"23": "DownloadQueued",
	"24": "DownloadRequired",
	"25": "DownloadDisabled",
	"26": "LicensePending",
	"27": "LicenseExpired",
	"28": "AvailForFree",
	"29": "AvailToBorrow",
	"30": "AvailGuestPass",
	"31": "Purchase",
};

export = EDisplayStatus;
