declare const EFrameAccumulatedStat: {
	"FPS": 0,
	"CaptureDurationMS": 1,
	"ConvertDurationMS": 2,
	"EncodeDurationMS": 3,
	"SteamDurationMS": 4,
	"ServerDurationMS": 5,
	"NetworkDurationMS": 6,
	"DecodeDurationMS": 7,
	"DisplayDurationMS": 8,
	"ClientDurationMS": 9,
	"FrameDurationMS": 10,
	"InputLatencyMS": 11,
	"GameLatencyMS": 12,
	"RoundTripLatencyMS": 13,
	"PingTimeMS": 14,
	"ServerBitrateKbitPerSec": 15,
	"ClientBitrateKbitPerSec": 16,
	"LinkBandwidthKbitPerSec": 17,
	"PacketLossPercentage": 18,

	// Value-to-name mapping for convenience
	"0": "FPS",
	"1": "CaptureDurationMS",
	"2": "ConvertDurationMS",
	"3": "EncodeDurationMS",
	"4": "SteamDurationMS",
	"5": "ServerDurationMS",
	"6": "NetworkDurationMS",
	"7": "DecodeDurationMS",
	"8": "DisplayDurationMS",
	"9": "ClientDurationMS",
	"10": "FrameDurationMS",
	"11": "InputLatencyMS",
	"12": "GameLatencyMS",
	"13": "RoundTripLatencyMS",
	"14": "PingTimeMS",
	"15": "ServerBitrateKbitPerSec",
	"16": "ClientBitrateKbitPerSec",
	"17": "LinkBandwidthKbitPerSec",
	"18": "PacketLossPercentage",
};

export = EFrameAccumulatedStat;
