declare const EPublishedFileQueryType: {
	"RankedByVote": 0,
	"RankedByPublicationDate": 1,
	"AcceptedForGameRankedByAcceptanceDate": 2,
	"RankedByTrend": 3,
	"FavoritedByFriendsRankedByPublicationDate": 4,
	"CreatedByFriendsRankedByPublicationDate": 5,
	"RankedByNumTimesReported": 6,
	"CreatedByFollowedUsersRankedByPublicationDate": 7,
	"NotYetRated": 8,
	"RankedByTotalUniqueSubscriptions": 9,
	"RankedByTotalVotesAsc": 10,
	"RankedByVotesUp": 11,
	"RankedByTextSearch": 12,
	"RankedByPlaytimeTrend": 13,
	"RankedByTotalPlaytime": 14,
	"RankedByAveragePlaytimeTrend": 15,
	"RankedByLifetimeAveragePlaytime": 16,
	"RankedByPlaytimeSessionsTrend": 17,
	"RankedByLifetimePlaytimeSessions": 18,
	"RankedByInappropriateContentRating": 19,

	// Value-to-name mapping for convenience
	"0": "RankedByVote",
	"1": "RankedByPublicationDate",
	"2": "AcceptedForGameRankedByAcceptanceDate",
	"3": "RankedByTrend",
	"4": "FavoritedByFriendsRankedByPublicationDate",
	"5": "CreatedByFriendsRankedByPublicationDate",
	"6": "RankedByNumTimesReported",
	"7": "CreatedByFollowedUsersRankedByPublicationDate",
	"8": "NotYetRated",
	"9": "RankedByTotalUniqueSubscriptions",
	"10": "RankedByTotalVotesAsc",
	"11": "RankedByVotesUp",
	"12": "RankedByTextSearch",
	"13": "RankedByPlaytimeTrend",
	"14": "RankedByTotalPlaytime",
	"15": "RankedByAveragePlaytimeTrend",
	"16": "RankedByLifetimeAveragePlaytime",
	"17": "RankedByPlaytimeSessionsTrend",
	"18": "RankedByLifetimePlaytimeSessions",
	"19": "RankedByInappropriateContentRating",
};

export = EPublishedFileQueryType;
