// auto generated Enums

export enum ESteamDatagramMsgID {
    Invalid = 0,
    RouterPingRequest = 1,
    RouterPingReply = 2,
    GameserverPingRequest = 3,
    LegacyGameserverPingReply = 4,
    GameserverSessionRequest = 5,
    GameserverSessionEstablished = 6,
    NoSession = 7,
    Diagnostic = 8,
    DataClientToRouter = 9,
    DataRouterToServer = 10,
    DataServerToRouter = 11,
    DataRouterToClient = 12,
    Stats = 13,
    ClientPingSampleRequest = 14,
    ClientPingSampleReply = 15,
    ClientToRouterSwitchedPrimary = 16,
    RelayHealth = 17,
    ConnectRequest = 18,
    ConnectOK = 19,
    ConnectionClosed = 20,
    NoConnection = 21,
    RelayToRelayPingRequest = 22,
    RelayToRelayPingReply = 23,
    P2PSessionRequest = 24,
    P2PSessionEstablished = 25,
    P2PStatsClient = 26,
    P2PStatsRelay = 27,
    P2PBadRoute = 28,
    GameserverPingReply = 29,
    GameserverRegistration = 30,
}
