declare const ESteamDatagramMsgID: {
	"Invalid": 0,
	"RouterPingRequest": 1,
	"RouterPingReply": 2,
	"GameserverPingRequest": 3,
	"LegacyGameserverPingReply": 4,
	"GameserverSessionRequest": 5,
	"GameserverSessionEstablished": 6,
	"NoSession": 7,
	"Diagnostic": 8,
	"DataClientToRouter": 9,
	"DataRouterToServer": 10,
	"DataServerToRouter": 11,
	"DataRouterToClient": 12,
	"Stats": 13,
	"ClientPingSampleRequest": 14,
	"ClientPingSampleReply": 15,
	"ClientToRouterSwitchedPrimary": 16,
	"RelayHealth": 17,
	"ConnectRequest": 18,
	"ConnectOK": 19,
	"ConnectionClosed": 20,
	"NoConnection": 21,
	"RelayToRelayPingRequest": 22,
	"RelayToRelayPingReply": 23,
	"P2PSessionRequest": 24,
	"P2PSessionEstablished": 25,
	"P2PStatsClient": 26,
	"P2PStatsRelay": 27,
	"P2PBadRoute": 28,
	"GameserverPingReply": 29,
	"GameserverRegistration": 30,

	// Value-to-name mapping for convenience
	"0": "Invalid",
	"1": "RouterPingRequest",
	"2": "RouterPingReply",
	"3": "GameserverPingRequest",
	"4": "LegacyGameserverPingReply",
	"5": "GameserverSessionRequest",
	"6": "GameserverSessionEstablished",
	"7": "NoSession",
	"8": "Diagnostic",
	"9": "DataClientToRouter",
	"10": "DataRouterToServer",
	"11": "DataServerToRouter",
	"12": "DataRouterToClient",
	"13": "Stats",
	"14": "ClientPingSampleRequest",
	"15": "ClientPingSampleReply",
	"16": "ClientToRouterSwitchedPrimary",
	"17": "RelayHealth",
	"18": "ConnectRequest",
	"19": "ConnectOK",
	"20": "ConnectionClosed",
	"21": "NoConnection",
	"22": "RelayToRelayPingRequest",
	"23": "RelayToRelayPingReply",
	"24": "P2PSessionRequest",
	"25": "P2PSessionEstablished",
	"26": "P2PStatsClient",
	"27": "P2PStatsRelay",
	"28": "P2PBadRoute",
	"29": "GameserverPingReply",
	"30": "GameserverRegistration",
};

export = ESteamDatagramMsgID;
