declare const EStreamFrameEvent: {
	"InputEventStart": 0,
	"InputEventSend": 1,
	"InputEventRecv": 2,
	"InputEventQueued": 3,
	"InputEventHandled": 4,
	"Start": 5,
	"CaptureBegin": 6,
	"CaptureEnd": 7,
	"ConvertBegin": 8,
	"ConvertEnd": 9,
	"EncodeBegin": 10,
	"EncodeEnd": 11,
	"Send": 12,
	"Recv": 13,
	"DecodeBegin": 14,
	"DecodeEnd": 15,
	"UploadBegin": 16,
	"UploadEnd": 17,
	"Complete": 18,

	// Value-to-name mapping for convenience
	"0": "InputEventStart",
	"1": "InputEventSend",
	"2": "InputEventRecv",
	"3": "InputEventQueued",
	"4": "InputEventHandled",
	"5": "Start",
	"6": "CaptureBegin",
	"7": "CaptureEnd",
	"8": "ConvertBegin",
	"9": "ConvertEnd",
	"10": "EncodeBegin",
	"11": "EncodeEnd",
	"12": "Send",
	"13": "Recv",
	"14": "DecodeBegin",
	"15": "DecodeEnd",
	"16": "UploadBegin",
	"17": "UploadEnd",
	"18": "Complete",
};

export = EStreamFrameEvent;
