export import Chinese = require("./Chinese");
export import English = require("./English");
export import French = require("./French");
export import German = require("./German");
export import Dutch = require("./Dutch");
export import Norwegian = require("./Norwegian");
export import Pirate = require("./Pirate");
export import Ukrainian = require("./Ukrainian");
export import Polish = require("./Polish");
export import Spanish = require("./Spanish");
export import Russian = require("./Russian");
export import Portuguese = require("./Portuguese");
export import Language = require("./Language");
export default English;
