import belter = require('belter');

belter.getUserAgent();
belter.isDevice('userAgent');
belter.isWebView();
belter.isStandAlone();
belter.isFacebookWebView('userAgent');
belter.isFirefoxIOS('userAgent');
belter.isEdgeIOS('userAgent');
belter.isOperaMini('userAgent');
belter.isAndroid('userAgent');
belter.isIos('userAgent');
belter.isGoogleSearchApp('userAgent');
belter.isQQBrowser('userAgent');
belter.isIosWebview('userAgent');
belter.isAndroidWebview('userAgent');
belter.isIE();
belter.isIECompHeader();
belter.isElectron();
belter.isIEIntranet();
belter.isMacOsCna();
belter.supportsPopups('userAgent');
belter.isChrome('userAgent');
belter.isSafari('userAgent');
