import * as charcodes from 'charcodes';

charcodes.backSpace; // $ExpectType 8
charcodes.tab; // $ExpectType 9
charcodes.lineFeed; // $ExpectType 10
charcodes.carriageReturn; // $ExpectType 13
charcodes.shiftOut; // $ExpectType 14
charcodes.space; // $ExpectType 32
charcodes.exclamationMark; // $ExpectType 33
charcodes.quotationMark; // $ExpectType 34
charcodes.numberSign; // $ExpectType 35
charcodes.dollarSign; // $ExpectType 36
charcodes.percentSign; // $ExpectType 37
charcodes.ampersand; // $ExpectType 38
charcodes.apostrophe; // $ExpectType 39
charcodes.leftParenthesis; // $ExpectType 40
charcodes.rightParenthesis; // $ExpectType 41
charcodes.asterisk; // $ExpectType 42
charcodes.plusSign; // $ExpectType 43
charcodes.comma; // $ExpectType 44
charcodes.dash; // $ExpectType 45
charcodes.dot; // $ExpectType 46
charcodes.slash; // $ExpectType 47
charcodes.digit0; // $ExpectType 48
charcodes.digit1; // $ExpectType 49
charcodes.digit2; // $ExpectType 50
charcodes.digit3; // $ExpectType 51
charcodes.digit4; // $ExpectType 52
charcodes.digit5; // $ExpectType 53
charcodes.digit6; // $ExpectType 54
charcodes.digit7; // $ExpectType 55
charcodes.digit8; // $ExpectType 56
charcodes.digit9; // $ExpectType 57
charcodes.colon; // $ExpectType 58
charcodes.semicolon; // $ExpectType 59
charcodes.lessThan; // $ExpectType 60
charcodes.equalsTo; // $ExpectType 61
charcodes.greaterThan; // $ExpectType 62
charcodes.questionMark; // $ExpectType 63
charcodes.atSign; // $ExpectType 64
charcodes.uppercaseA; // $ExpectType 65
charcodes.uppercaseB; // $ExpectType 66
charcodes.uppercaseC; // $ExpectType 67
charcodes.uppercaseD; // $ExpectType 68
charcodes.uppercaseE; // $ExpectType 69
charcodes.uppercaseF; // $ExpectType 70
charcodes.uppercaseG; // $ExpectType 71
charcodes.uppercaseH; // $ExpectType 72
charcodes.uppercaseI; // $ExpectType 73
charcodes.uppercaseJ; // $ExpectType 74
charcodes.uppercaseK; // $ExpectType 75
charcodes.uppercaseL; // $ExpectType 76
charcodes.uppercaseM; // $ExpectType 77
charcodes.uppercaseN; // $ExpectType 78
charcodes.uppercaseO; // $ExpectType 79
charcodes.uppercaseP; // $ExpectType 80
charcodes.uppercaseQ; // $ExpectType 81
charcodes.uppercaseR; // $ExpectType 82
charcodes.uppercaseS; // $ExpectType 83
charcodes.uppercaseT; // $ExpectType 84
charcodes.uppercaseU; // $ExpectType 85
charcodes.uppercaseV; // $ExpectType 86
charcodes.uppercaseW; // $ExpectType 87
charcodes.uppercaseX; // $ExpectType 88
charcodes.uppercaseY; // $ExpectType 89
charcodes.uppercaseZ; // $ExpectType 90
charcodes.leftSquareBracket; // $ExpectType 91
charcodes.backslash; // $ExpectType 92
charcodes.rightSquareBracket; // $ExpectType 93
charcodes.caret; // $ExpectType 94
charcodes.underscore; // $ExpectType 95
charcodes.graveAccent; // $ExpectType 96
charcodes.lowercaseA; // $ExpectType 97
charcodes.lowercaseB; // $ExpectType 98
charcodes.lowercaseC; // $ExpectType 99
charcodes.lowercaseD; // $ExpectType 100
charcodes.lowercaseE; // $ExpectType 101
charcodes.lowercaseF; // $ExpectType 102
charcodes.lowercaseG; // $ExpectType 103
charcodes.lowercaseH; // $ExpectType 104
charcodes.lowercaseI; // $ExpectType 105
charcodes.lowercaseJ; // $ExpectType 106
charcodes.lowercaseK; // $ExpectType 107
charcodes.lowercaseL; // $ExpectType 108
charcodes.lowercaseM; // $ExpectType 109
charcodes.lowercaseN; // $ExpectType 110
charcodes.lowercaseO; // $ExpectType 111
charcodes.lowercaseP; // $ExpectType 112
charcodes.lowercaseQ; // $ExpectType 113
charcodes.lowercaseR; // $ExpectType 114
charcodes.lowercaseS; // $ExpectType 115
charcodes.lowercaseT; // $ExpectType 116
charcodes.lowercaseU; // $ExpectType 117
charcodes.lowercaseV; // $ExpectType 118
charcodes.lowercaseW; // $ExpectType 119
charcodes.lowercaseX; // $ExpectType 120
charcodes.lowercaseY; // $ExpectType 121
charcodes.lowercaseZ; // $ExpectType 122
charcodes.leftCurlyBrace; // $ExpectType 123
charcodes.verticalBar; // $ExpectType 124
charcodes.rightCurlyBrace; // $ExpectType 125
charcodes.tilde; // $ExpectType 126
charcodes.nonBreakingSpace; // $ExpectType 160
charcodes.oghamSpaceMark; // $ExpectType 5760
charcodes.lineSeparator; // $ExpectType 8232
charcodes.paragraphSeparator; // $ExpectType 8233
charcodes.isDigit(5); // $ExpectType boolean
