import ExtendedDeviceInfo from './extended-device-info';
export default class AppData {
    _application_tracking_enabled: boolean;
    _advertiser_tracking_enabled: boolean;
    _campaign_ids: string;
    _consider_views: boolean;
    _extinfo: ExtendedDeviceInfo;
    _include_dwell_data: boolean;
    _include_video_data: boolean;
    _install_referrer: string;
    _installer_package: string;
    _receipt_data: string;
    _url_schemes: string;
    _windows_attribution_id: string;
    constructor(application_tracking_enabled: boolean, advertiser_tracking_enabled: boolean, campaign_ids: string, consider_views: boolean, extinfo: ExtendedDeviceInfo, include_dwell_data: boolean, include_video_data: boolean, install_referrer: string, installer_package: string, receipt_data: string, url_schemes: string, windows_attribution_id: string);
    get application_tracking_enabled(): boolean;
    set application_tracking_enabled(application_tracking_enabled: boolean);
    setApplicationTrackingEnabled(application_tracking_enabled: boolean): AppData;
    get advertiser_tracking_enabled(): boolean;
    set advertiser_tracking_enabled(advertiser_tracking_enabled: boolean);
    setAdvertiserTrackingEnabled(advertiser_tracking_enabled: boolean): AppData;
    get campaign_ids(): string;
    set campaign_ids(campaign_ids: string);
    setCampaignIds(campaign_ids: string): AppData;
    get consider_views(): boolean;
    set consider_views(consider_views: boolean);
    setConsiderViews(consider_views: boolean): AppData;
    get extinfo(): ExtendedDeviceInfo;
    set extinfo(extinfo: ExtendedDeviceInfo);
    setExtinfo(extinfo: ExtendedDeviceInfo): AppData;
    get include_dwell_data(): boolean;
    set include_dwell_data(include_dwell_data: boolean);
    setIncludeDwellData(include_dwell_data: boolean): AppData;
    get include_video_data(): boolean;
    set include_video_data(include_video_data: boolean);
    setIncludeVideoData(include_video_data: boolean): AppData;
    get install_referrer(): string;
    set install_referrer(install_referrer: string);
    setInstallReferrer(install_referrer: string): AppData;
    get installer_package(): string;
    set installer_package(installer_package: string);
    setInstallerPackage(installer_package: string): AppData;
    get receipt_data(): string;
    set receipt_data(receipt_data: string);
    setReceiptData(receipt_data: string): AppData;
    get url_schemes(): string;
    set url_schemes(url_schemes: string);
    setUrlSchemes(url_schemes: string): AppData;
    get windows_attribution_id(): string;
    set windows_attribution_id(windows_attribution_id: string);
    setWindowsAttributionId(windows_attribution_id: string): AppData;
    normalize(): Record<any, any>;
    toJson(): Record<any, any>;
}
