export default class ExtendedDeviceInfo {
    _ext_info_version: string;
    _app_package_name: string;
    _short_version: string;
    _long_version: string;
    _os_version: string;
    _device_model_name: string;
    _locale: string;
    _timezone_abbreviation: string;
    _carrier: string;
    _screen_width: number;
    _screen_height: number;
    _screen_density: string;
    _cpu_core_count: number;
    _total_disk_space_gb: number;
    _free_disk_space_gb: number;
    _device_time_zone: string;
    constructor(ext_info_version: string, app_package_name: string, short_version: string, long_version: string, os_version: string, device_model_name: string, locale: string, timezone_abbreviation: string, carrier: string, screen_width: number, screen_height: number, screen_density: string, cpu_core_count: number, total_disk_space_gb: number, free_disk_space_gb: number, device_time_zone: string);
    get ext_info_version(): string;
    set ext_info_version(ext_info_version: string);
    setExtInfoVersion(ext_info_version: string): ExtendedDeviceInfo;
    get app_package_name(): string;
    set app_package_name(app_package_name: string);
    setAppPackageName(app_package_name: string): ExtendedDeviceInfo;
    get short_version(): string;
    set short_version(short_version: string);
    setShortVersion(short_version: string): ExtendedDeviceInfo;
    get long_version(): string;
    set long_version(long_version: string);
    setLongVersion(long_version: string): ExtendedDeviceInfo;
    get os_version(): string;
    set os_version(os_version: string);
    setOsVersion(os_version: string): ExtendedDeviceInfo;
    get device_model_name(): string;
    set device_model_name(device_model_name: string);
    setDeviceModelName(device_model_name: string): ExtendedDeviceInfo;
    get locale(): string;
    set locale(locale: string);
    setLocale(locale: string): ExtendedDeviceInfo;
    get timezone_abbreviation(): string;
    set timezone_abbreviation(timezone_abbreviation: string);
    setTimezoneAbbreviation(timezone_abbreviation: string): ExtendedDeviceInfo;
    get carrier(): string;
    set carrier(carrier: string);
    setCarrier(carrier: string): ExtendedDeviceInfo;
    get screen_width(): number;
    set screen_width(screen_width: number);
    setScreenWidth(screen_width: number): ExtendedDeviceInfo;
    get screen_height(): number;
    set screen_height(screen_height: number);
    setScreenHeight(screen_height: number): ExtendedDeviceInfo;
    get screen_density(): string;
    set screen_density(screen_density: string);
    setScreenDensity(screen_density: string): ExtendedDeviceInfo;
    get cpu_core_count(): number;
    set cpu_core_count(cpu_core_count: number);
    setCpuCoreCount(cpu_core_count: number): ExtendedDeviceInfo;
    get total_disk_space_gb(): number;
    set total_disk_space_gb(total_disk_space_gb: number);
    setTotalDiskSpaceGb(total_disk_space_gb: number): ExtendedDeviceInfo;
    get free_disk_space_gb(): number;
    set free_disk_space_gb(free_disk_space_gb: number);
    setFreeDiskSpaceGb(free_disk_space_gb: number): ExtendedDeviceInfo;
    get device_time_zone(): string;
    set device_time_zone(device_time_zone: string);
    setDeviceTimeZone(device_time_zone: string): ExtendedDeviceInfo;
    normalize(): Record<any, any>;
    toJson(): Record<any, any>;
}
