export type exports = number;
declare let JAN: number;
declare let FEB: number;
declare let MAR: number;
declare let APR: number;
declare let MAY: number;
declare let JUN: number;
declare let JUL: number;
declare let AUG: number;
declare let SEP: number;
declare let OCT: number;
declare let NOV: number;
declare let DEC: number;
export {};
