export namespace version {
    const version: any;
}
import * as bv from "./bv/index.js";
import * as jd from "./astro/jd.js";
import * as math from "./math.js";
import * as mercator from "./mercator.js";
import * as utils from "./utils/shared.js";
import { input } from "./input/input.js";
import * as layer from "./layer/index.js";
import * as terrain from "./terrain/index.js";
export const Control: typeof control.Control;
import * as control from "./control/index.js";
import * as webgl from "./webgl/index.js";
import { wgs84 } from "./ellipsoid/index.js";
import { Camera } from "./camera/index.js";
import { Ellipsoid } from "./ellipsoid/index.js";
import { PlanetCamera } from "./camera/index.js";
import { Globe } from "./Globe.js";
import { LightSource } from "./light/LightSource.js";
export const EntityCollection: typeof entity.EntityCollection;
export const Handler: typeof webgl.Handler;
import { Clock } from "./Clock.js";
import { Events } from "./Events.js";
import { Extent } from "./Extent.js";
import { LonLat } from "./LonLat.js";
import * as scene from "./scene/index.js";
import { RenderNode } from "./scene/RenderNode.js";
import { Mat3 } from "./math/index.js";
import { Mat4 } from "./math/index.js";
import { Plane } from "./math/index.js";
import { Vec2 } from "./math/index.js";
import { Vec3 } from "./math/index.js";
import { Vec4 } from "./math/index.js";
import * as entity from "./entity/index.js";
export const Entity: typeof entity.Entity;
import { Geoid } from "./terrain/Geoid.js";
import { Popup } from "./Popup.js";
export { bv, jd, math, mercator, utils, input, layer, terrain, control, webgl, wgs84, Camera, Ellipsoid, PlanetCamera, Globe, LightSource, Clock, Events, Extent, LonLat, scene, RenderNode, Mat3, Mat4, Plane, Vec2, Vec3, Vec4, entity, Geoid, Popup };
