export = ViewDefField;
declare function ViewDefField(
    name: string,
    type: string,
    size: number | null,
    ...args: any[]
): void;
declare class ViewDefField {
    constructor(name: string, type: string, size: number | null, ...args: any[]);
    private superInit_;
    private inheritedClassDefEvents_;
    private superRegisterEvents_;
    notifyObjectPropertyChange_: any;
    private typesThatNotSupportUnderscoreAtName_;
    private init_;
    cssStyle: Record<string, string>;
    private protectState_;
    private unprotectState_;
    private defaultAdapterDescriptor_;
    private unrestrictedOn_;
    private registerEvents_;
    duplicationHandling: number;
    private propertiesToAssign_;
    private propertiesToAssignWithDeepClone_;
    private ownControlledProperties_;
    resyncPending: boolean;
    private logger_;
    showGlobalActions: boolean;
    visible: boolean;
    duplicateMode: string;
    tableViewable: boolean;
    formViewable: boolean;
    requiredDataSetFields: string;
    private arRequiredDataSetFields;
    alignment: string;
    height: string | number;
    private height_;
    rows: number;
    width: string | number;
    private width_;
    enterKeyAction: typeof EnterKeyAction | string;
    tableViewLabel: string;
    controlType: string;
    private controlType_;
    treeParentFieldName: string;
    treeChildFieldName: string;
    treeRootValues: any;
    private maxSize;
    private maxFiles;
    private canLocate;
    changed: boolean;
    private changeable;
    private totalContent;
    zoomMaxHeight: number | string;
    zoomMaxWidth: number | string;
    tableViewWidth: string | number;
    private tableViewWidth_;
    parent: Grid | ViewDef;
    editable: boolean;
    isCalculated: boolean;
    hasEvent(eventName: string): boolean;
    saveInputAsDefault: boolean;
    emptyResultMessage: string;
    labelPosition: string;
    negativeInRed: boolean;
    column: number;
    breakLine: boolean;
    hasInformedControl: boolean;
    allowMultipleInsert: boolean;
    wrap: boolean;
    private classDef;
    private lastMasterFieldValues;
    private tableViewIndex;
    private inSetValue;
    private _index;
    detailIndexFieldNames: string;
    detailDescendingIndexFieldNames: string;
    masterDetailMaxRecordCount: number;
    private _createEvent;
    onOpenKey: Event;
    onCalculate: Event;
    onGetTreeIcon: Event;
    onFocus: Event;
    private onBlur;
    onLookupMultipleInsert: Event;
    onDefineGrid: Event;
    links: LinkSet;
    private links_;
    private getIsDataSetField;
    private _getClassDef;
    thumbnail: CellThumbnail;
    hasLookupDisplayEvent(): boolean;
    hasLinks: boolean;
    hasVisibleThumbnail(): boolean;
    canHaveGlobalActions(): boolean;
    getGlobalActionClassKey(opt_key?: number): number;
    getGlobalActionRegisterKey(opt_key?: number): number | null;
    link: Link;
    linkParametersValuesFieldNames: any[];
    private _originalAssignTo;
    assignTo(field: any, ...args: any[]): void;
    private originalChangeFieldType_;
    protected changeFieldType_(type: any, fieldName: any, ...args: any[]): void;
    private tableViewable_;
    readOnly: boolean;
    private superGetIsDataBaseField_;
    getIsDataBaseField(): boolean;
    viewMode: number;
    aggregate: FieldAggregator;
    isGrid(): boolean;
    isTree(): boolean;
    isKey(): boolean;
    isMasterDetail(): boolean;
}
declare namespace ViewDefField {
    export { VM_THUMBNAIL, VM_LIST, FieldAggregator, Event, ViewDef, Grid, Link };
}
import EnterKeyAction = require('./EnterKeyAction.js');
import LinkSet = require('../anchor/LinkSet.js');
import CellThumbnail = require('./CellThumbnail.js');
declare let VM_THUMBNAIL: number;
declare let VM_LIST: number;
type FieldAggregator = import('../field-aggregator/FieldAggregator');
type Event = import('@nginstack/engine/lib/event/Event');
type ViewDef = import('./ViewDef');
type Grid = import('../grid/Grid');
type Link = import('../anchor/Link');
