import * as React from 'react';

const testCases = [
    <span />,
    <span accessKey="s" />,
    <span className="klass" />,
    <span contentEditable />,
    <span contextMenu="menuId" />,
    <span dir="rtl" />,
    <span draggable />,
    <span hidden />,
    <span id="s" />,
    <span lang="art-x-tokipona" />,
    <input placeholder="placeholder" />,
    <span slot="my-text" />,
    <span spellCheck />,
    <span tabIndex={0} />,
    <span title="title" />,
    <span role="button" />,
    <span autoCapitalize="off" />,
    <span autoCapitalize="none" />,
    <span autoCapitalize="on" />,
    <span autoCapitalize="words" />,
    <span autoCapitalize="sentences" />,
    <span autoCorrect="off" />,
    <span autoCorrect="on" />,
    <span translate="no" />,
    <span translate="yes" />,
    <svg><image crossOrigin="anonymous" /></svg>,
    <details open={true} onToggle={() => {}} />,
    <input value={['one', 'two'] as ReadonlyArray<string>} />,
    <input value={['one', 'two'] as string[]} />,
    <input value={['one', 'two']} />
];
