import solverjs = require('solverjs');

solverjs.getFib(8);
solverjs.getGcd(12, 24);
solverjs.printFib(8);
solverjs.sumAllDigit(123);
solverjs.reverseNumber(935);
solverjs.isArmstrong(153);
solverjs.sumOfN(5);
solverjs.fac(5);
solverjs.pow(4, 2);
solverjs.len(1234);
solverjs.isPrime(2);
solverjs.isCoPrime(13, 34);
solverjs.isKishnamurthyNumber(145);
solverjs.avg([5, 6, 8, 9, 3]);
solverjs.mod(-145);
solverjs.wordCount('alsdjf lasjfd lsjf', ' ');
solverjs.isLeap(2021);
solverjs.lcm(12, 3);
solverjs.hcf(72, 23);
solverjs.ascii('A');
solverjs.reverse('abcde');
solverjs.isPalindrome('abcba');
solverjs.permutation('abc');
solverjs.alternativeStringArrange('abcde', 'xyz');
solverjs.phoneValidator('+910011223344');
solverjs.phoneExtractor('this is no. +910011223344');
solverjs.isAlNum('55x');
solverjs.isAlpha('55');
solverjs.numToAscii(97);
solverjs.isDecimal('55');
solverjs.isLower('lower');
solverjs.isUpper('UPPER');
solverjs.isTitle('Title');
solverjs.isSpace('  ');
solverjs.token();
solverjs.randomInt(5, 9);
solverjs.remainder(5, 2);
solverjs.isFibonacci(5);
solverjs.max([2, 5, 6, 3]);
solverjs.min([2, 5, 6, 3]);
