export type exports = string;
declare let CHAR: string;
declare let VARCHAR: string;
declare let CLOB: string;
declare let INTEGER: string;
declare let BIGINT: string;
declare let NUMERIC: string;
declare let DOUBLE_PRECISION: string;
declare let TIMESTAMP: string;
declare let TIMESTAMP_WITH_TIME_ZONE: string;
declare let DATE: string;
export {};
