export let MAX_TREE_DEPTH: number;
export let MAX_TABLE_NAME_LENGTH: number;
export let MAX_COLUMN_NAME_LENGTH: number;
export let MAX_INDEX_NAME_LENGTH: number;
export let MAX_VFS_NAME_LENGTH: number;
export let MAX_VFS_PATH_LENGTH: number;
export let MAX_COLUMNS_PER_TABLE: number;
export let MAX_COLUMNS_PER_INDEX: number;
export let MAX_CLOB_SIZE: number;
