export = Status;
type Status = number;
declare namespace Status {
    const OK: number;
    const CREATED: number;
    const ACCEPTED: number;
    const NO_CONTENT: number;
    const RESET_CONTENT: number;
    const PARTIAL_CONTENT: number;
    const MOVED_PERMANENTLY: number;
    const FOUND: number;
    const SEE_OTHER: number;
    const NOT_MODIFIED: number;
    const TEMPORARY_REDIRECT: number;
    const PERMANENT_REDIRECT: number;
    const BAD_REQUEST: number;
    const UNAUTHORIZED: number;
    const FORBIDDEN: number;
    const NOT_FOUND: number;
    const METHOD_NOT_ALLOWED: number;
    const NOT_ACCEPTABLE: number;
    const REQUEST_TIMEOUT: number;
    const CONFLICT: number;
    const GONE: number;
    const LENGTH_REQUIRED: number;
    const PRECONDITION_FAILED: number;
    const REQUEST_ENTITY_TOO_LARGE: number;
    const UNSUPPORTED_MEDIA_TYPE: number;
    const UNPROCESSABLE_ENTITY: number;
    const INTERNAL_SERVER_ERROR: number;
    const NOT_IMPLEMENTED: number;
    const BAD_GATEWAY: number;
    const SERVICE_UNAVAILABLE: number;
    const GATEWAY_TIMEOUT: number;
}
