export = Status;
type Status = number;
declare namespace Status {
    let OK: number;
    let CREATED: number;
    let ACCEPTED: number;
    let NO_CONTENT: number;
    let RESET_CONTENT: number;
    let PARTIAL_CONTENT: number;
    let MOVED_PERMANENTLY: number;
    let FOUND: number;
    let SEE_OTHER: number;
    let NOT_MODIFIED: number;
    let TEMPORARY_REDIRECT: number;
    let PERMANENT_REDIRECT: number;
    let BAD_REQUEST: number;
    let UNAUTHORIZED: number;
    let FORBIDDEN: number;
    let NOT_FOUND: number;
    let METHOD_NOT_ALLOWED: number;
    let NOT_ACCEPTABLE: number;
    let REQUEST_TIMEOUT: number;
    let CONFLICT: number;
    let GONE: number;
    let LENGTH_REQUIRED: number;
    let PRECONDITION_FAILED: number;
    let REQUEST_ENTITY_TOO_LARGE: number;
    let UNSUPPORTED_MEDIA_TYPE: number;
    let UNPROCESSABLE_ENTITY: number;
    let INTERNAL_SERVER_ERROR: number;
    let NOT_IMPLEMENTED: number;
    let BAD_GATEWAY: number;
    let SERVICE_UNAVAILABLE: number;
    let GATEWAY_TIMEOUT: number;
}
