name: Set up scripts
description: Set up repo for running scripts

runs:
  using: composite
  steps:
    - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
      with:
        node-version: '24'
    - uses: pnpm/action-setup@08c4be7e2e672a47d11bd04269e27e5f3e8529cb # v6.0.0
      with:
        run_install: |
          - args: [--filter, ., --filter, '{./scripts}...']
