export const DISCRETE_EVENT_PRIORITY = 1;
export const CONTINUOUS_EVENT_PRIORITY = 4;
export const DEFAULT_EVENT_PRIORITY = 16;
export const IDLE_EVENT_PRIORITY = 536870912;
export const LEGACY_ROOT = 0;
export const CONCURRENT_ROOT = 1;
