export class RigidBody extends Component {
    private mCollider;
    private mInGroup;
    private mIsSleeping;
    private mSleepTime;
    private mContacts;
    private mPivot;
    private mCachedPosition;
    mPairs: Pair[];
    private mIsStatic;
    private mPosition;
    private mVelocity;
    private mForce;
    private mTransform;
    private mMass;
    private mInvMass;
    frictionAir: number;
    friction: number;
    bounce: number;
    set mass(arg: number);
    get mass(): number;
    set isStatic(arg: boolean);
    get isStatic(): boolean;
    set x(arg: number);
    get x(): number;
    set y(arg: number);
    get y(): number;
    set forceX(arg: number);
    get forceX(): number;
    set forceY(arg: number);
    get forceY(): number;
    set velocityX(arg: number);
    get velocityX(): number;
    set velocityY(arg: number);
    get velocityY(): number;
    update(): void;
    clearFlags(): void;
}
import { Component } from '../core/Component';
import { Pair } from './arcade/pairs/Pair';
