/** !CompileMembersOnly */
declare enum FindType_t {
    FIND_ANY_ORDER = 0,
    FIND_CLOSEST = 1,
    FIND_FARTHEST = 2
}

declare var FIND_UNITS_EVERYWHERE: number;

/** !CompileMembersOnly */
declare enum DOTAConnectionState_t {
  DOTA_CONNECTION_STATE_UNKNOWN = 0,
  DOTA_CONNECTION_STATE_NOT_YET_CONNECTED = 1,
  DOTA_CONNECTION_STATE_CONNECTED = 2,
  DOTA_CONNECTION_STATE_DISCONNECTED = 3,
  DOTA_CONNECTION_STATE_ABANDONED = 4,
  DOTA_CONNECTION_STATE_LOADING = 5,
  DOTA_CONNECTION_STATE_FAILED = 6,
}

/** !CompileMembersOnly */
declare enum AbilityLearnResult_t {
    ABILITY_CAN_BE_UPGRADED = 0,
    ABILITY_CANNOT_BE_UPGRADED_NOT_UPGRADABLE = 1,
    ABILITY_CANNOT_BE_UPGRADED_AT_MAX = 2,
    ABILITY_CANNOT_BE_UPGRADED_REQUIRES_LEVEL = 3,
    ABILITY_NOT_LEARNABLE = 4
}

/** !CompileMembersOnly */
declare enum AttributeDerivedStats {
    DOTA_ATTRIBUTE_STRENGTH_DAMAGE = 0,
    DOTA_ATTRIBUTE_STRENGTH_HP = 1,
    DOTA_ATTRIBUTE_STRENGTH_HP_REGEN_PERCENT = 2,
    DOTA_ATTRIBUTE_STRENGTH_STATUS_RESISTANCE_PERCENT = 3,
    DOTA_ATTRIBUTE_AGILITY_DAMAGE = 4,
    DOTA_ATTRIBUTE_AGILITY_ARMOR = 5,
    DOTA_ATTRIBUTE_AGILITY_ATTACK_SPEED = 6,
    DOTA_ATTRIBUTE_AGILITY_MOVE_SPEED_PERCENT = 7,
    DOTA_ATTRIBUTE_INTELLIGENCE_DAMAGE = 8,
    DOTA_ATTRIBUTE_INTELLIGENCE_MANA = 9,
    DOTA_ATTRIBUTE_INTELLIGENCE_MANA_REGEN_PERCENT = 10,
    DOTA_ATTRIBUTE_INTELLIGENCE_SPELL_AMP_PERCENT = 11,
    DOTA_ATTRIBUTE_INTELLIGENCE_MAGIC_RESISTANCE_PERCENT = 12
}

/** !CompileMembersOnly */
declare enum Attributes {
    DOTA_ATTRIBUTE_STRENGTH = 0,
    DOTA_ATTRIBUTE_AGILITY = 1,
    DOTA_ATTRIBUTE_INTELLECT = 2,
    DOTA_ATTRIBUTE_MAX = 3,
    DOTA_ATTRIBUTE_INVALID = -1
}

/** !CompileMembersOnly */
declare enum DAMAGE_TYPES {
    DAMAGE_TYPE_NONE = 0,
    DAMAGE_TYPE_PHYSICAL = 1,
    DAMAGE_TYPE_MAGICAL = 2,
    DAMAGE_TYPE_PURE = 4,
    DAMAGE_TYPE_HP_REMOVAL = 8,
    DAMAGE_TYPE_ALL = 7
}

/** !CompileMembersOnly */
declare enum DOTAAbilitySpeakTrigger_t {
    DOTA_ABILITY_SPEAK_START_ACTION_PHASE = 0,
    DOTA_ABILITY_SPEAK_CAST = 1
}

/** !CompileMembersOnly */
declare enum DOTADamageFlag_t {
    DOTA_DAMAGE_FLAG_NONE = 0,
    DOTA_DAMAGE_FLAG_IGNORES_MAGIC_ARMOR = 1,
    DOTA_DAMAGE_FLAG_IGNORES_PHYSICAL_ARMOR = 2,
    DOTA_DAMAGE_FLAG_BYPASSES_INVULNERABILITY = 4,
    DOTA_DAMAGE_FLAG_BYPASSES_BLOCK = 8,
    DOTA_DAMAGE_FLAG_REFLECTION = 16,
    DOTA_DAMAGE_FLAG_HPLOSS = 32,
    DOTA_DAMAGE_FLAG_NO_DIRECTOR_EVENT = 64,
    DOTA_DAMAGE_FLAG_NON_LETHAL = 128,
    DOTA_DAMAGE_FLAG_USE_COMBAT_PROFICIENCY = 256,
    DOTA_DAMAGE_FLAG_NO_DAMAGE_MULTIPLIERS = 512,
    DOTA_DAMAGE_FLAG_NO_SPELL_AMPLIFICATION = 1024,
    DOTA_DAMAGE_FLAG_DONT_DISPLAY_DAMAGE_IF_SOURCE_HIDDEN = 2048,
    DOTA_DAMAGE_FLAG_NO_SPELL_LIFESTEAL = 4096
}

/** !CompileMembersOnly */
declare enum DOTAHUDVisibility_t {
    DOTA_HUD_VISIBILITY_INVALID = -1,
    DOTA_HUD_VISIBILITY_TOP_TIMEOFDAY = 0,
    DOTA_HUD_VISIBILITY_TOP_HEROES = 1,
    DOTA_HUD_VISIBILITY_TOP_SCOREBOARD = 2,
    DOTA_HUD_VISIBILITY_ACTION_PANEL = 3,
    DOTA_HUD_VISIBILITY_ACTION_MINIMAP = 4,
    DOTA_HUD_VISIBILITY_INVENTORY_PANEL = 5,
    DOTA_HUD_VISIBILITY_INVENTORY_SHOP = 6,
    DOTA_HUD_VISIBILITY_INVENTORY_ITEMS = 7,
    DOTA_HUD_VISIBILITY_INVENTORY_QUICKBUY = 8,
    DOTA_HUD_VISIBILITY_INVENTORY_COURIER = 9,
    DOTA_HUD_VISIBILITY_INVENTORY_PROTECT = 10,
    DOTA_HUD_VISIBILITY_INVENTORY_GOLD = 11,
    DOTA_HUD_VISIBILITY_SHOP_SUGGESTEDITEMS = 12,
    DOTA_HUD_VISIBILITY_HERO_SELECTION_TEAMS = 13,
    DOTA_HUD_VISIBILITY_HERO_SELECTION_GAME_NAME = 14,
    DOTA_HUD_VISIBILITY_HERO_SELECTION_CLOCK = 15,
    DOTA_HUD_VISIBILITY_TOP_MENU_BUTTONS = 16,
    DOTA_HUD_VISIBILITY_TOP_BAR_BACKGROUND = 17,
    DOTA_HUD_VISIBILITY_TOP_BAR_RADIANT_TEAM = 18,
    DOTA_HUD_VISIBILITY_TOP_BAR_DIRE_TEAM = 19,
    DOTA_HUD_VISIBILITY_TOP_BAR_SCORE = 20,
    DOTA_HUD_VISIBILITY_ENDGAME = 21,
    DOTA_HUD_VISIBILITY_ENDGAME_CHAT = 22,
    DOTA_HUD_VISIBILITY_QUICK_STATS = 23,
    DOTA_HUD_VISIBILITY_PREGAME_STRATEGYUI = 24,
    DOTA_HUD_VISIBILITY_KILLCAM = 25,
    DOTA_HUD_VISIBILITY_TOP_BAR = 26,
    DOTA_HUD_VISIBILITY_COUNT = 27
}

/** !CompileMembersOnly */
declare enum DOTAInventoryFlags_t {
    DOTA_INVENTORY_ALLOW_NONE = 0,
    DOTA_INVENTORY_ALLOW_MAIN = 1,
    DOTA_INVENTORY_ALLOW_STASH = 2,
    DOTA_INVENTORY_ALLOW_DROP_ON_GROUND = 4,
    DOTA_INVENTORY_ALLOW_DROP_AT_FOUNTAIN = 8,
    DOTA_INVENTORY_LIMIT_DROP_ON_GROUND = 16,
    DOTA_INVENTORY_ALL_ACCESS = 3
}

/** !CompileMembersOnly */
declare enum DOTALimits_t {
    /**
     * Max number of players connected to the server including spectators.
     */
    DOTA_MAX_PLAYERS = 64,
    /**
     * Max number of players per team.
     */
    DOTA_MAX_TEAM = 24,
    /**
     * Max number of player teams supported.
     */
    DOTA_MAX_PLAYER_TEAMS = 10,
    /**
     * Max number of non-spectator players supported.
     */
    DOTA_MAX_TEAM_PLAYERS = 24,
    /**
     * How many spectators can watch.
     */
    DOTA_MAX_SPECTATOR_TEAM_SIZE = 40,
    /**
     * Max number of viewers in a spectator lobby.
     */
    DOTA_MAX_SPECTATOR_LOBBY_SIZE = 15,
    /**
     * Default number of players per team.
     */
    DOTA_DEFAULT_MAX_TEAM = 5,
    /**
     * Default number of non-spectator players supported.
     */
    DOTA_DEFAULT_MAX_TEAM_PLAYERS = 10
}

/** !CompileMembersOnly */
declare enum DOTAMinimapEvent_t {
    DOTA_MINIMAP_EVENT_ANCIENT_UNDER_ATTACK = 2,
    DOTA_MINIMAP_EVENT_BASE_UNDER_ATTACK = 4,
    DOTA_MINIMAP_EVENT_BASE_GLYPHED = 8,
    DOTA_MINIMAP_EVENT_TEAMMATE_UNDER_ATTACK = 16,
    DOTA_MINIMAP_EVENT_TEAMMATE_TELEPORTING = 32,
    DOTA_MINIMAP_EVENT_TEAMMATE_DIED = 64,
    DOTA_MINIMAP_EVENT_TUTORIAL_TASK_ACTIVE = 128,
    DOTA_MINIMAP_EVENT_TUTORIAL_TASK_FINISHED = 256,
    DOTA_MINIMAP_EVENT_HINT_LOCATION = 512,
    DOTA_MINIMAP_EVENT_ENEMY_TELEPORTING = 1024,
    DOTA_MINIMAP_EVENT_CANCEL_TELEPORTING = 2048,
    DOTA_MINIMAP_EVENT_RADAR = 4096,
    DOTA_MINIMAP_EVENT_RADAR_TARGET = 8192
}

/** !CompileMembersOnly */
declare enum DOTAModifierAttribute_t {
    MODIFIER_ATTRIBUTE_NONE = 0,
    MODIFIER_ATTRIBUTE_PERMANENT = 1,
    MODIFIER_ATTRIBUTE_MULTIPLE = 2,
    MODIFIER_ATTRIBUTE_IGNORE_INVULNERABLE = 4,
    MODIFIER_ATTRIBUTE_AURA_PRIORITY = 8
}

/** !CompileMembersOnly */
declare enum DOTAMusicStatus_t {
    DOTA_MUSIC_STATUS_NONE = 0,
    DOTA_MUSIC_STATUS_EXPLORATION = 1,
    DOTA_MUSIC_STATUS_BATTLE = 2,
    DOTA_MUSIC_STATUS_PRE_GAME_EXPLORATION = 3,
    DOTA_MUSIC_STATUS_DEAD = 4,
    DOTA_MUSIC_STATUS_LAST = 5
}

/** !CompileMembersOnly */
declare enum DOTAProjectileAttachment_t {
    DOTA_PROJECTILE_ATTACHMENT_NONE = 0,
    DOTA_PROJECTILE_ATTACHMENT_ATTACK_1 = 1,
    DOTA_PROJECTILE_ATTACHMENT_ATTACK_2 = 2,
    DOTA_PROJECTILE_ATTACHMENT_HITLOCATION = 3,
    DOTA_PROJECTILE_ATTACHMENT_ATTACK_3 = 4,
    DOTA_PROJECTILE_ATTACHMENT_ATTACK_4 = 5,
    DOTA_PROJECTILE_ATTACHMENT_LAST = 6
}

/** !CompileMembersOnly */
declare enum DOTAScriptInventorySlot_t {
    DOTA_ITEM_SLOT_1 = 0,
    DOTA_ITEM_SLOT_2 = 1,
    DOTA_ITEM_SLOT_3 = 2,
    DOTA_ITEM_SLOT_4 = 3,
    DOTA_ITEM_SLOT_5 = 4,
    DOTA_ITEM_SLOT_6 = 5,
    DOTA_ITEM_SLOT_7 = 6,
    DOTA_ITEM_SLOT_8 = 7,
    DOTA_ITEM_SLOT_9 = 8,
    DOTA_STASH_SLOT_1 = 9,
    DOTA_STASH_SLOT_2 = 10,
    DOTA_STASH_SLOT_3 = 11,
    DOTA_STASH_SLOT_4 = 12,
    DOTA_STASH_SLOT_5 = 13,
    DOTA_STASH_SLOT_6 = 14
}

/** !CompileMembersOnly */
declare enum DOTASlotType_t {
    DOTA_LOADOUT_TYPE_INVALID = -1,
    DOTA_LOADOUT_TYPE_WEAPON = 0,
    DOTA_LOADOUT_TYPE_OFFHAND_WEAPON = 1,
    DOTA_LOADOUT_TYPE_WEAPON2 = 2,
    DOTA_LOADOUT_TYPE_OFFHAND_WEAPON2 = 3,
    DOTA_LOADOUT_TYPE_HEAD = 4,
    DOTA_LOADOUT_TYPE_SHOULDER = 5,
    DOTA_LOADOUT_TYPE_ARMS = 6,
    DOTA_LOADOUT_TYPE_ARMOR = 7,
    DOTA_LOADOUT_TYPE_BELT = 8,
    DOTA_LOADOUT_TYPE_NECK = 9,
    DOTA_LOADOUT_TYPE_BACK = 10,
    DOTA_LOADOUT_TYPE_LEGS = 11,
    DOTA_LOADOUT_TYPE_GLOVES = 12,
    DOTA_LOADOUT_TYPE_TAIL = 13,
    DOTA_LOADOUT_TYPE_MISC = 14,
    DOTA_LOADOUT_TYPE_BODY_HEAD = 15,
    DOTA_LOADOUT_TYPE_MOUNT = 16,
    DOTA_LOADOUT_TYPE_SUMMON = 17,
    DOTA_LOADOUT_TYPE_SHAPESHIFT = 18,
    DOTA_LOADOUT_TYPE_TAUNT = 19,
    DOTA_LOADOUT_TYPE_AMBIENT_EFFECTS = 20,
    DOTA_LOADOUT_TYPE_ABILITY_ATTACK = 21,
    DOTA_LOADOUT_TYPE_ABILITY1 = 22,
    DOTA_LOADOUT_TYPE_ABILITY2 = 23,
    DOTA_LOADOUT_TYPE_ABILITY3 = 24,
    DOTA_LOADOUT_TYPE_ABILITY4 = 25,
    DOTA_LOADOUT_TYPE_ABILITY_ULTIMATE = 26,
    DOTA_LOADOUT_TYPE_VOICE = 27,
    DOTA_LOADOUT_TYPE_ACTION_ITEM = 28,
    DOTA_LOADOUT_TYPE_COURIER = 29,
    DOTA_LOADOUT_TYPE_ANNOUNCER = 30,
    DOTA_LOADOUT_TYPE_MEGA_KILLS = 31,
    DOTA_LOADOUT_TYPE_MUSIC = 32,
    DOTA_LOADOUT_TYPE_WARD = 33,
    DOTA_LOADOUT_TYPE_HUD_SKIN = 34,
    DOTA_LOADOUT_TYPE_LOADING_SCREEN = 35,
    DOTA_LOADOUT_TYPE_WEATHER = 36,
    DOTA_LOADOUT_TYPE_HEROIC_STATUE = 37,
    DOTA_LOADOUT_TYPE_MULTIKILL_BANNER = 38,
    DOTA_LOADOUT_TYPE_CURSOR_PACK = 39,
    DOTA_LOADOUT_TYPE_TELEPORT_EFFECT = 40,
    DOTA_LOADOUT_TYPE_BLINK_EFFECT = 41,
    DOTA_LOADOUT_TYPE_RELIC = 42,
    DOTA_LOADOUT_TYPE_TERRAIN = 43,
    DOTA_PLAYER_LOADOUT_START = 28,
    DOTA_PLAYER_LOADOUT_END = 43,
    DOTA_LOADOUT_TYPE_NONE = 44,
    DOTA_LOADOUT_TYPE_COUNT = 45
}

/** !CompileMembersOnly */
declare enum DOTASpeechType_t {
    DOTA_SPEECH_USER_INVALID = 0,
    DOTA_SPEECH_USER_SINGLE = 1,
    DOTA_SPEECH_USER_TEAM = 2,
    DOTA_SPEECH_USER_TEAM_NEARBY = 3,
    DOTA_SPEECH_USER_NEARBY = 4,
    DOTA_SPEECH_USER_ALL = 5,
    DOTA_SPEECH_GOOD_TEAM = 6,
    DOTA_SPEECH_BAD_TEAM = 7,
    DOTA_SPEECH_SPECTATOR = 8,
    DOTA_SPEECH_RECIPIENT_TYPE_MAX = 9
}

/** !CompileMembersOnly */
declare enum DOTATeam_t {
    DOTA_TEAM_FIRST = 2,
    DOTA_TEAM_GOODGUYS = 2,
    DOTA_TEAM_BADGUYS = 3,
    DOTA_TEAM_NEUTRALS = 4,
    DOTA_TEAM_NOTEAM = 5,
    DOTA_TEAM_CUSTOM_1 = 6,
    DOTA_TEAM_CUSTOM_2 = 7,
    DOTA_TEAM_CUSTOM_3 = 8,
    DOTA_TEAM_CUSTOM_4 = 9,
    DOTA_TEAM_CUSTOM_5 = 10,
    DOTA_TEAM_CUSTOM_6 = 11,
    DOTA_TEAM_CUSTOM_7 = 12,
    DOTA_TEAM_CUSTOM_8 = 13,
    DOTA_TEAM_COUNT = 14,
    DOTA_TEAM_CUSTOM_MIN = 6,
    DOTA_TEAM_CUSTOM_MAX = 13,
    DOTA_TEAM_CUSTOM_COUNT = 8
}

/** !CompileMembersOnly */
declare enum DOTAUnitAttackCapability_t {
    DOTA_UNIT_CAP_NO_ATTACK = 0,
    DOTA_UNIT_CAP_MELEE_ATTACK = 1,
    DOTA_UNIT_CAP_RANGED_ATTACK = 2
}

/** !CompileMembersOnly */
declare enum DOTAUnitMoveCapability_t {
    DOTA_UNIT_CAP_MOVE_NONE = 0,
    DOTA_UNIT_CAP_MOVE_GROUND = 1,
    DOTA_UNIT_CAP_MOVE_FLY = 2
}

/** !CompileMembersOnly */
declare enum DOTA_ABILITY_BEHAVIOR {
    DOTA_ABILITY_BEHAVIOR_NONE = 0,
    DOTA_ABILITY_BEHAVIOR_HIDDEN = 1,
    DOTA_ABILITY_BEHAVIOR_PASSIVE = 2,
    DOTA_ABILITY_BEHAVIOR_NO_TARGET = 4,
    DOTA_ABILITY_BEHAVIOR_UNIT_TARGET = 8,
    DOTA_ABILITY_BEHAVIOR_POINT = 16,
    DOTA_ABILITY_BEHAVIOR_AOE = 32,
    DOTA_ABILITY_BEHAVIOR_NOT_LEARNABLE = 64,
    DOTA_ABILITY_BEHAVIOR_CHANNELLED = 128,
    DOTA_ABILITY_BEHAVIOR_ITEM = 256,
    DOTA_ABILITY_BEHAVIOR_TOGGLE = 512,
    DOTA_ABILITY_BEHAVIOR_DIRECTIONAL = 1024,
    DOTA_ABILITY_BEHAVIOR_IMMEDIATE = 2048,
    DOTA_ABILITY_BEHAVIOR_AUTOCAST = 4096,
    DOTA_ABILITY_BEHAVIOR_OPTIONAL_UNIT_TARGET = 8192,
    DOTA_ABILITY_BEHAVIOR_OPTIONAL_POINT = 16384,
    DOTA_ABILITY_BEHAVIOR_OPTIONAL_NO_TARGET = 32768,
    DOTA_ABILITY_BEHAVIOR_AURA = 65536,
    DOTA_ABILITY_BEHAVIOR_ATTACK = 131072,
    DOTA_ABILITY_BEHAVIOR_DONT_RESUME_MOVEMENT = 262144,
    DOTA_ABILITY_BEHAVIOR_ROOT_DISABLES = 524288,
    DOTA_ABILITY_BEHAVIOR_UNRESTRICTED = 1048576,
    DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE = 2097152,
    DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL = 4194304,
    DOTA_ABILITY_BEHAVIOR_DONT_CANCEL_MOVEMENT = 8388608,
    DOTA_ABILITY_BEHAVIOR_DONT_ALERT_TARGET = 16777216,
    DOTA_ABILITY_BEHAVIOR_DONT_RESUME_ATTACK = 33554432,
    DOTA_ABILITY_BEHAVIOR_NORMAL_WHEN_STOLEN = 67108864,
    DOTA_ABILITY_BEHAVIOR_IGNORE_BACKSWING = 134217728,
    DOTA_ABILITY_BEHAVIOR_RUNE_TARGET = 268435456,
    DOTA_ABILITY_BEHAVIOR_DONT_CANCEL_CHANNEL = 536870912,
    DOTA_ABILITY_BEHAVIOR_VECTOR_TARGETING = 1073741824,
    DOTA_ABILITY_BEHAVIOR_LAST_RESORT_POINT = -2147483648,
    DOTA_ABILITY_BEHAVIOR_CAN_SELF_CAST = 0
}

/** !CompileMembersOnly */
declare enum DOTA_GameState {
    DOTA_GAMERULES_STATE_INIT = 0,
    DOTA_GAMERULES_STATE_WAIT_FOR_PLAYERS_TO_LOAD = 1,
    DOTA_GAMERULES_STATE_HERO_SELECTION = 3,
    DOTA_GAMERULES_STATE_STRATEGY_TIME = 4,
    DOTA_GAMERULES_STATE_PRE_GAME = 7,
    DOTA_GAMERULES_STATE_GAME_IN_PROGRESS = 8,
    DOTA_GAMERULES_STATE_POST_GAME = 9,
    DOTA_GAMERULES_STATE_DISCONNECT = 10,
    DOTA_GAMERULES_STATE_TEAM_SHOWCASE = 5,
    DOTA_GAMERULES_STATE_CUSTOM_GAME_SETUP = 2,
    DOTA_GAMERULES_STATE_WAIT_FOR_MAP_TO_LOAD = 6
}

/** !CompileMembersOnly */
declare enum DOTA_HeroPickState {
    DOTA_HEROPICK_STATE_NONE = 0,
    DOTA_HEROPICK_STATE_AP_SELECT = 1,
    DOTA_HEROPICK_STATE_SD_SELECT = 2,
    DOTA_HEROPICK_STATE_INTRO_SELECT_UNUSED = 3,
    DOTA_HEROPICK_STATE_RD_SELECT_UNUSED = 4,
    DOTA_HEROPICK_STATE_CM_INTRO = 5,
    DOTA_HEROPICK_STATE_CM_CAPTAINPICK = 6,
    DOTA_HEROPICK_STATE_CM_BAN1 = 7,
    DOTA_HEROPICK_STATE_CM_BAN2 = 8,
    DOTA_HEROPICK_STATE_CM_BAN3 = 9,
    DOTA_HEROPICK_STATE_CM_BAN4 = 10,
    DOTA_HEROPICK_STATE_CM_BAN5 = 11,
    DOTA_HEROPICK_STATE_CM_BAN6 = 12,
    DOTA_HEROPICK_STATE_CM_BAN7 = 13,
    DOTA_HEROPICK_STATE_CM_BAN8 = 14,
    DOTA_HEROPICK_STATE_CM_BAN9 = 15,
    DOTA_HEROPICK_STATE_CM_BAN10 = 16,
    DOTA_HEROPICK_STATE_CM_BAN11 = 17,
    DOTA_HEROPICK_STATE_CM_BAN12 = 18,
    DOTA_HEROPICK_STATE_CM_SELECT1 = 19,
    DOTA_HEROPICK_STATE_CM_SELECT2 = 20,
    DOTA_HEROPICK_STATE_CM_SELECT3 = 21,
    DOTA_HEROPICK_STATE_CM_SELECT4 = 22,
    DOTA_HEROPICK_STATE_CM_SELECT5 = 23,
    DOTA_HEROPICK_STATE_CM_SELECT6 = 24,
    DOTA_HEROPICK_STATE_CM_SELECT7 = 25,
    DOTA_HEROPICK_STATE_CM_SELECT8 = 26,
    DOTA_HEROPICK_STATE_CM_SELECT9 = 27,
    DOTA_HEROPICK_STATE_CM_SELECT10 = 28,
    DOTA_HEROPICK_STATE_CM_PICK = 29,
    DOTA_HEROPICK_STATE_AR_SELECT = 30,
    DOTA_HEROPICK_STATE_MO_SELECT = 31,
    DOTA_HEROPICK_STATE_FH_SELECT = 32,
    DOTA_HEROPICK_STATE_CD_INTRO = 33,
    DOTA_HEROPICK_STATE_CD_CAPTAINPICK = 34,
    DOTA_HEROPICK_STATE_CD_BAN1 = 35,
    DOTA_HEROPICK_STATE_CD_BAN2 = 36,
    DOTA_HEROPICK_STATE_CD_BAN3 = 37,
    DOTA_HEROPICK_STATE_CD_BAN4 = 38,
    DOTA_HEROPICK_STATE_CD_BAN5 = 39,
    DOTA_HEROPICK_STATE_CD_BAN6 = 40,
    DOTA_HEROPICK_STATE_CD_SELECT1 = 41,
    DOTA_HEROPICK_STATE_CD_SELECT2 = 42,
    DOTA_HEROPICK_STATE_CD_SELECT3 = 43,
    DOTA_HEROPICK_STATE_CD_SELECT4 = 44,
    DOTA_HEROPICK_STATE_CD_SELECT5 = 45,
    DOTA_HEROPICK_STATE_CD_SELECT6 = 46,
    DOTA_HEROPICK_STATE_CD_SELECT7 = 47,
    DOTA_HEROPICK_STATE_CD_SELECT8 = 48,
    DOTA_HEROPICK_STATE_CD_SELECT9 = 49,
    DOTA_HEROPICK_STATE_CD_SELECT10 = 50,
    DOTA_HEROPICK_STATE_CD_PICK = 51,
    DOTA_HEROPICK_STATE_BD_SELECT = 52,
    DOTA_HERO_PICK_STATE_ABILITY_DRAFT_SELECT = 53,
    DOTA_HERO_PICK_STATE_ARDM_SELECT = 54,
    DOTA_HEROPICK_STATE_ALL_DRAFT_SELECT = 55,
    DOTA_HERO_PICK_STATE_CUSTOMGAME_SELECT = 56,
    DOTA_HEROPICK_STATE_SELECT_PENALTY = 57,
    DOTA_HEROPICK_STATE_CUSTOM_PICK_RULES = 58,
    DOTA_HEROPICK_STATE_COUNT = 59
}

/** !CompileMembersOnly */
declare enum DOTA_MOTION_CONTROLLER_PRIORITY {
    DOTA_MOTION_CONTROLLER_PRIORITY_LOWEST = 0,
    DOTA_MOTION_CONTROLLER_PRIORITY_LOW = 1,
    DOTA_MOTION_CONTROLLER_PRIORITY_MEDIUM = 2,
    DOTA_MOTION_CONTROLLER_PRIORITY_HIGH = 3,
    DOTA_MOTION_CONTROLLER_PRIORITY_HIGHEST = 4
}

/** !CompileMembersOnly */
declare enum DOTA_RUNES {
    DOTA_RUNE_INVALID = -1,
    DOTA_RUNE_DOUBLEDAMAGE = 0,
    DOTA_RUNE_HASTE = 1,
    DOTA_RUNE_ILLUSION = 2,
    DOTA_RUNE_INVISIBILITY = 3,
    DOTA_RUNE_REGENERATION = 4,
    DOTA_RUNE_BOUNTY = 5,
    DOTA_RUNE_ARCANE = 6,
    DOTA_RUNE_COUNT = 7
}

/** !CompileMembersOnly */
declare enum DOTA_SHOP_TYPE {
    DOTA_SHOP_HOME = 0,
    DOTA_SHOP_SIDE = 1,
    DOTA_SHOP_SECRET = 2,
    DOTA_SHOP_GROUND = 3,
    DOTA_SHOP_SIDE2 = 4,
    DOTA_SHOP_SECRET2 = 5,
    DOTA_SHOP_CUSTOM = 6,
    DOTA_SHOP_NONE = 7
}

/** !CompileMembersOnly */
declare enum DOTA_UNIT_TARGET_FLAGS {
    DOTA_UNIT_TARGET_FLAG_NONE = 0,
    DOTA_UNIT_TARGET_FLAG_RANGED_ONLY = 2,
    DOTA_UNIT_TARGET_FLAG_MELEE_ONLY = 4,
    DOTA_UNIT_TARGET_FLAG_DEAD = 8,
    DOTA_UNIT_TARGET_FLAG_MAGIC_IMMUNE_ENEMIES = 16,
    DOTA_UNIT_TARGET_FLAG_NOT_MAGIC_IMMUNE_ALLIES = 32,
    DOTA_UNIT_TARGET_FLAG_INVULNERABLE = 64,
    DOTA_UNIT_TARGET_FLAG_FOW_VISIBLE = 128,
    DOTA_UNIT_TARGET_FLAG_NO_INVIS = 256,
    DOTA_UNIT_TARGET_FLAG_NOT_ANCIENTS = 512,
    DOTA_UNIT_TARGET_FLAG_PLAYER_CONTROLLED = 1024,
    DOTA_UNIT_TARGET_FLAG_NOT_DOMINATED = 2048,
    DOTA_UNIT_TARGET_FLAG_NOT_SUMMONED = 4096,
    DOTA_UNIT_TARGET_FLAG_NOT_ILLUSIONS = 8192,
    DOTA_UNIT_TARGET_FLAG_NOT_ATTACK_IMMUNE = 16384,
    DOTA_UNIT_TARGET_FLAG_MANA_ONLY = 32768,
    DOTA_UNIT_TARGET_FLAG_CHECK_DISABLE_HELP = 65536,
    DOTA_UNIT_TARGET_FLAG_NOT_CREEP_HERO = 131072,
    DOTA_UNIT_TARGET_FLAG_OUT_OF_WORLD = 262144,
    DOTA_UNIT_TARGET_FLAG_NOT_NIGHTMARED = 524288,
    DOTA_UNIT_TARGET_FLAG_PREFER_ENEMIES = 1048576,
    DOTA_UNIT_TARGET_FLAG_RESPECT_OBSTRUCTIONS = 2097152
}

/** !CompileMembersOnly */
declare enum DOTA_UNIT_TARGET_TEAM {
    DOTA_UNIT_TARGET_TEAM_NONE = 0,
    DOTA_UNIT_TARGET_TEAM_FRIENDLY = 1,
    DOTA_UNIT_TARGET_TEAM_ENEMY = 2,
    DOTA_UNIT_TARGET_TEAM_CUSTOM = 4,
    DOTA_UNIT_TARGET_TEAM_BOTH = 3
}

/** !CompileMembersOnly */
declare enum DOTA_UNIT_TARGET_TYPE {
    DOTA_UNIT_TARGET_NONE = 0,
    DOTA_UNIT_TARGET_HERO = 1,
    DOTA_UNIT_TARGET_CREEP = 2,
    DOTA_UNIT_TARGET_BUILDING = 4,
    DOTA_UNIT_TARGET_COURIER = 16,
    DOTA_UNIT_TARGET_OTHER = 32,
    DOTA_UNIT_TARGET_TREE = 64,
    DOTA_UNIT_TARGET_CUSTOM = 128,
    DOTA_UNIT_TARGET_BASIC = 18,
    DOTA_UNIT_TARGET_ALL = 55
}

/** !CompileMembersOnly */
declare enum DamageCategory_t {
    DOTA_DAMAGE_CATEGORY_SPELL = 0,
    DOTA_DAMAGE_CATEGORY_ATTACK = 1
}

/** !CompileMembersOnly */
declare enum DotaDefaultUIElement_t {
    DOTA_DEFAULT_UI_INVALID = -1,
    DOTA_DEFAULT_UI_TOP_TIMEOFDAY = 0,
    DOTA_DEFAULT_UI_TOP_HEROES = 1,
    DOTA_DEFAULT_UI_FLYOUT_SCOREBOARD = 2,
    DOTA_DEFAULT_UI_ACTION_PANEL = 3,
    DOTA_DEFAULT_UI_ACTION_MINIMAP = 4,
    DOTA_DEFAULT_UI_INVENTORY_PANEL = 5,
    DOTA_DEFAULT_UI_INVENTORY_SHOP = 6,
    DOTA_DEFAULT_UI_INVENTORY_ITEMS = 7,
    DOTA_DEFAULT_UI_INVENTORY_QUICKBUY = 8,
    DOTA_DEFAULT_UI_INVENTORY_COURIER = 9,
    DOTA_DEFAULT_UI_INVENTORY_PROTECT = 10,
    DOTA_DEFAULT_UI_INVENTORY_GOLD = 11,
    DOTA_DEFAULT_UI_SHOP_SUGGESTEDITEMS = 12,
    DOTA_DEFAULT_UI_HERO_SELECTION_TEAMS = 13,
    DOTA_DEFAULT_UI_HERO_SELECTION_GAME_NAME = 14,
    DOTA_DEFAULT_UI_HERO_SELECTION_CLOCK = 15,
    DOTA_DEFAULT_UI_TOP_MENU_BUTTONS = 16,
    DOTA_DEFAULT_UI_TOP_BAR_BACKGROUND = 17,
    DOTA_DEFAULT_UI_TOP_BAR_RADIANT_TEAM = 18,
    DOTA_DEFAULT_UI_TOP_BAR_DIRE_TEAM = 19,
    DOTA_DEFAULT_UI_TOP_BAR_SCORE = 20,
    DOTA_DEFAULT_UI_ENDGAME = 21,
    DOTA_DEFAULT_UI_ENDGAME_CHAT = 22,
    DOTA_DEFAULT_UI_QUICK_STATS = 23,
    DOTA_DEFAULT_UI_PREGAME_STRATEGYUI = 24,
    DOTA_DEFAULT_UI_KILLCAM = 25,
    DOTA_DEFAULT_UI_TOP_BAR = 26,
    DOTA_DEFAULT_UI_ELEMENT_COUNT = 27
}

/** !CompileMembersOnly */
declare enum EDOTA_ModifyGold_Reason {
    DOTA_ModifyGold_Unspecified = 0,
    DOTA_ModifyGold_Death = 1,
    DOTA_ModifyGold_Buyback = 2,
    DOTA_ModifyGold_PurchaseConsumable = 3,
    DOTA_ModifyGold_PurchaseItem = 4,
    DOTA_ModifyGold_AbandonedRedistribute = 5,
    DOTA_ModifyGold_SellItem = 6,
    DOTA_ModifyGold_AbilityCost = 7,
    DOTA_ModifyGold_CheatCommand = 8,
    DOTA_ModifyGold_SelectionPenalty = 9,
    DOTA_ModifyGold_GameTick = 10,
    DOTA_ModifyGold_Building = 11,
    DOTA_ModifyGold_HeroKill = 12,
    DOTA_ModifyGold_CreepKill = 13,
    DOTA_ModifyGold_RoshanKill = 14,
    DOTA_ModifyGold_CourierKill = 15,
    DOTA_ModifyGold_SharedGold = 16
}

/** !CompileMembersOnly */
declare enum EDOTA_ModifyXP_Reason {
    DOTA_ModifyXP_Unspecified = 0,
    DOTA_ModifyXP_HeroKill = 1,
    DOTA_ModifyXP_CreepKill = 2,
    DOTA_ModifyXP_RoshanKill = 3
}

/** !CompileMembersOnly */
declare enum EShareAbility {
    ITEM_FULLY_SHAREABLE = 0,
    ITEM_PARTIALLY_SHAREABLE = 1,
    ITEM_NOT_SHAREABLE = 2
}

/** !CompileMembersOnly */
declare enum GameActivity_t {
    ACT_DOTA_IDLE = 1500,
    ACT_DOTA_IDLE_RARE = 1501,
    ACT_DOTA_RUN = 1502,
    ACT_DOTA_ATTACK = 1503,
    ACT_DOTA_ATTACK2 = 1504,
    ACT_DOTA_ATTACK_EVENT = 1505,
    ACT_DOTA_DIE = 1506,
    ACT_DOTA_FLINCH = 1507,
    ACT_DOTA_FLAIL = 1508,
    ACT_DOTA_DISABLED = 1509,
    ACT_DOTA_CAST_ABILITY_1 = 1510,
    ACT_DOTA_CAST_ABILITY_2 = 1511,
    ACT_DOTA_CAST_ABILITY_3 = 1512,
    ACT_DOTA_CAST_ABILITY_4 = 1513,
    ACT_DOTA_CAST_ABILITY_5 = 1514,
    ACT_DOTA_CAST_ABILITY_6 = 1515,
    ACT_DOTA_OVERRIDE_ABILITY_1 = 1516,
    ACT_DOTA_OVERRIDE_ABILITY_2 = 1517,
    ACT_DOTA_OVERRIDE_ABILITY_3 = 1518,
    ACT_DOTA_OVERRIDE_ABILITY_4 = 1519,
    ACT_DOTA_CHANNEL_ABILITY_1 = 1520,
    ACT_DOTA_CHANNEL_ABILITY_2 = 1521,
    ACT_DOTA_CHANNEL_ABILITY_3 = 1522,
    ACT_DOTA_CHANNEL_ABILITY_4 = 1523,
    ACT_DOTA_CHANNEL_ABILITY_5 = 1524,
    ACT_DOTA_CHANNEL_ABILITY_6 = 1525,
    ACT_DOTA_CHANNEL_END_ABILITY_1 = 1526,
    ACT_DOTA_CHANNEL_END_ABILITY_2 = 1527,
    ACT_DOTA_CHANNEL_END_ABILITY_3 = 1528,
    ACT_DOTA_CHANNEL_END_ABILITY_4 = 1529,
    ACT_DOTA_CHANNEL_END_ABILITY_5 = 1530,
    ACT_DOTA_CHANNEL_END_ABILITY_6 = 1531,
    ACT_DOTA_CONSTANT_LAYER = 1532,
    ACT_DOTA_CAPTURE = 1533,
    ACT_DOTA_SPAWN = 1534,
    ACT_DOTA_KILLTAUNT = 1535,
    ACT_DOTA_TAUNT = 1536,
    ACT_DOTA_THIRST = 1537,
    ACT_DOTA_CAST_DRAGONBREATH = 1538,
    ACT_DOTA_ECHO_SLAM = 1539,
    ACT_DOTA_CAST_ABILITY_1_END = 1540,
    ACT_DOTA_CAST_ABILITY_2_END = 1541,
    ACT_DOTA_CAST_ABILITY_3_END = 1542,
    ACT_DOTA_CAST_ABILITY_4_END = 1543,
    ACT_MIRANA_LEAP_END = 1544,
    ACT_WAVEFORM_START = 1545,
    ACT_WAVEFORM_END = 1546,
    ACT_DOTA_CAST_ABILITY_ROT = 1547,
    ACT_DOTA_DIE_SPECIAL = 1548,
    ACT_DOTA_RATTLETRAP_BATTERYASSAULT = 1549,
    ACT_DOTA_RATTLETRAP_POWERCOGS = 1550,
    ACT_DOTA_RATTLETRAP_HOOKSHOT_START = 1551,
    ACT_DOTA_RATTLETRAP_HOOKSHOT_LOOP = 1552,
    ACT_DOTA_RATTLETRAP_HOOKSHOT_END = 1553,
    ACT_STORM_SPIRIT_OVERLOAD_RUN_OVERRIDE = 1554,
    ACT_DOTA_TINKER_REARM1 = 1555,
    ACT_DOTA_TINKER_REARM2 = 1556,
    ACT_DOTA_TINKER_REARM3 = 1557,
    ACT_TINY_AVALANCHE = 1558,
    ACT_TINY_TOSS = 1559,
    ACT_TINY_GROWL = 1560,
    ACT_DOTA_WEAVERBUG_ATTACH = 1561,
    ACT_DOTA_CAST_WILD_AXES_END = 1562,
    ACT_DOTA_CAST_LIFE_BREAK_START = 1563,
    ACT_DOTA_CAST_LIFE_BREAK_END = 1564,
    ACT_DOTA_NIGHTSTALKER_TRANSITION = 1565,
    ACT_DOTA_LIFESTEALER_RAGE = 1566,
    ACT_DOTA_LIFESTEALER_OPEN_WOUNDS = 1567,
    ACT_DOTA_SAND_KING_BURROW_IN = 1568,
    ACT_DOTA_SAND_KING_BURROW_OUT = 1569,
    ACT_DOTA_EARTHSHAKER_TOTEM_ATTACK = 1570,
    ACT_DOTA_WHEEL_LAYER = 1571,
    ACT_DOTA_ALCHEMIST_CHEMICAL_RAGE_START = 1572,
    ACT_DOTA_ALCHEMIST_CONCOCTION = 1573,
    ACT_DOTA_JAKIRO_LIQUIDFIRE_START = 1574,
    ACT_DOTA_JAKIRO_LIQUIDFIRE_LOOP = 1575,
    ACT_DOTA_LIFESTEALER_INFEST = 1576,
    ACT_DOTA_LIFESTEALER_INFEST_END = 1577,
    ACT_DOTA_LASSO_LOOP = 1578,
    ACT_DOTA_ALCHEMIST_CONCOCTION_THROW = 1579,
    ACT_DOTA_ALCHEMIST_CHEMICAL_RAGE_END = 1580,
    ACT_DOTA_CAST_COLD_SNAP = 1581,
    ACT_DOTA_CAST_GHOST_WALK = 1582,
    ACT_DOTA_CAST_TORNADO = 1583,
    ACT_DOTA_CAST_EMP = 1584,
    ACT_DOTA_CAST_ALACRITY = 1585,
    ACT_DOTA_CAST_CHAOS_METEOR = 1586,
    ACT_DOTA_CAST_SUN_STRIKE = 1587,
    ACT_DOTA_CAST_FORGE_SPIRIT = 1588,
    ACT_DOTA_CAST_ICE_WALL = 1589,
    ACT_DOTA_CAST_DEAFENING_BLAST = 1590,
    ACT_DOTA_VICTORY = 1591,
    ACT_DOTA_DEFEAT = 1592,
    ACT_DOTA_SPIRIT_BREAKER_CHARGE_POSE = 1593,
    ACT_DOTA_SPIRIT_BREAKER_CHARGE_END = 1594,
    ACT_DOTA_TELEPORT = 1595,
    ACT_DOTA_TELEPORT_END = 1596,
    ACT_DOTA_CAST_REFRACTION = 1597,
    ACT_DOTA_CAST_ABILITY_7 = 1598,
    ACT_DOTA_CANCEL_SIREN_SONG = 1599,
    ACT_DOTA_CHANNEL_ABILITY_7 = 1600,
    ACT_DOTA_LOADOUT = 1601,
    ACT_DOTA_FORCESTAFF_END = 1602,
    ACT_DOTA_POOF_END = 1603,
    ACT_DOTA_SLARK_POUNCE = 1604,
    ACT_DOTA_MAGNUS_SKEWER_START = 1605,
    ACT_DOTA_MAGNUS_SKEWER_END = 1606,
    ACT_DOTA_MEDUSA_STONE_GAZE = 1607,
    ACT_DOTA_RELAX_START = 1608,
    ACT_DOTA_RELAX_LOOP = 1609,
    ACT_DOTA_RELAX_END = 1610,
    ACT_DOTA_CENTAUR_STAMPEDE = 1611,
    ACT_DOTA_BELLYACHE_START = 1612,
    ACT_DOTA_BELLYACHE_LOOP = 1613,
    ACT_DOTA_BELLYACHE_END = 1614,
    ACT_DOTA_ROQUELAIRE_LAND = 1615,
    ACT_DOTA_ROQUELAIRE_LAND_IDLE = 1616,
    ACT_DOTA_GREEVIL_CAST = 1617,
    ACT_DOTA_GREEVIL_OVERRIDE_ABILITY = 1618,
    ACT_DOTA_GREEVIL_HOOK_START = 1619,
    ACT_DOTA_GREEVIL_HOOK_END = 1620,
    ACT_DOTA_GREEVIL_BLINK_BONE = 1621,
    ACT_DOTA_IDLE_SLEEPING = 1622,
    ACT_DOTA_INTRO = 1623,
    ACT_DOTA_GESTURE_POINT = 1624,
    ACT_DOTA_GESTURE_ACCENT = 1625,
    ACT_DOTA_SLEEPING_END = 1626,
    ACT_DOTA_AMBUSH = 1627,
    ACT_DOTA_ITEM_LOOK = 1628,
    ACT_DOTA_STARTLE = 1629,
    ACT_DOTA_FRUSTRATION = 1630,
    ACT_DOTA_TELEPORT_REACT = 1631,
    ACT_DOTA_TELEPORT_END_REACT = 1632,
    ACT_DOTA_SHRUG = 1633,
    ACT_DOTA_RELAX_LOOP_END = 1634,
    ACT_DOTA_PRESENT_ITEM = 1635,
    ACT_DOTA_IDLE_IMPATIENT = 1636,
    ACT_DOTA_SHARPEN_WEAPON = 1637,
    ACT_DOTA_SHARPEN_WEAPON_OUT = 1638,
    ACT_DOTA_IDLE_SLEEPING_END = 1639,
    ACT_DOTA_BRIDGE_DESTROY = 1640,
    ACT_DOTA_TAUNT_SNIPER = 1641,
    ACT_DOTA_DEATH_BY_SNIPER = 1642,
    ACT_DOTA_LOOK_AROUND = 1643,
    ACT_DOTA_CAGED_CREEP_RAGE = 1644,
    ACT_DOTA_CAGED_CREEP_RAGE_OUT = 1645,
    ACT_DOTA_CAGED_CREEP_SMASH = 1646,
    ACT_DOTA_CAGED_CREEP_SMASH_OUT = 1647,
    ACT_DOTA_IDLE_IMPATIENT_SWORD_TAP = 1648,
    ACT_DOTA_INTRO_LOOP = 1649,
    ACT_DOTA_BRIDGE_THREAT = 1650,
    ACT_DOTA_DAGON = 1651,
    ACT_DOTA_CAST_ABILITY_2_ES_ROLL_START = 1652,
    ACT_DOTA_CAST_ABILITY_2_ES_ROLL = 1653,
    ACT_DOTA_CAST_ABILITY_2_ES_ROLL_END = 1654,
    ACT_DOTA_NIAN_PIN_START = 1655,
    ACT_DOTA_NIAN_PIN_LOOP = 1656,
    ACT_DOTA_NIAN_PIN_END = 1657,
    ACT_DOTA_LEAP_STUN = 1658,
    ACT_DOTA_LEAP_SWIPE = 1659,
    ACT_DOTA_NIAN_INTRO_LEAP = 1660,
    ACT_DOTA_AREA_DENY = 1661,
    ACT_DOTA_NIAN_PIN_TO_STUN = 1662,
    ACT_DOTA_RAZE_1 = 1663,
    ACT_DOTA_RAZE_2 = 1664,
    ACT_DOTA_RAZE_3 = 1665,
    ACT_DOTA_UNDYING_DECAY = 1666,
    ACT_DOTA_UNDYING_SOUL_RIP = 1667,
    ACT_DOTA_UNDYING_TOMBSTONE = 1668,
    ACT_DOTA_WHIRLING_AXES_RANGED = 1669,
    ACT_DOTA_SHALLOW_GRAVE = 1670,
    ACT_DOTA_COLD_FEET = 1671,
    ACT_DOTA_ICE_VORTEX = 1672,
    ACT_DOTA_CHILLING_TOUCH = 1673,
    ACT_DOTA_ENFEEBLE = 1674,
    ACT_DOTA_FATAL_BONDS = 1675,
    ACT_DOTA_MIDNIGHT_PULSE = 1676,
    ACT_DOTA_ANCESTRAL_SPIRIT = 1677,
    ACT_DOTA_THUNDER_STRIKE = 1678,
    ACT_DOTA_KINETIC_FIELD = 1679,
    ACT_DOTA_STATIC_STORM = 1680,
    ACT_DOTA_MINI_TAUNT = 1681,
    ACT_DOTA_ARCTIC_BURN_END = 1682,
    ACT_DOTA_LOADOUT_RARE = 1683,
    ACT_DOTA_SWIM = 1684,
    ACT_DOTA_FLEE = 1685,
    ACT_DOTA_TROT = 1686,
    ACT_DOTA_SHAKE = 1687,
    ACT_DOTA_SWIM_IDLE = 1688,
    ACT_DOTA_WAIT_IDLE = 1689,
    ACT_DOTA_GREET = 1690,
    ACT_DOTA_TELEPORT_COOP_START = 1691,
    ACT_DOTA_TELEPORT_COOP_WAIT = 1692,
    ACT_DOTA_TELEPORT_COOP_END = 1693,
    ACT_DOTA_TELEPORT_COOP_EXIT = 1694,
    ACT_DOTA_SHOPKEEPER_PET_INTERACT = 1695,
    ACT_DOTA_ITEM_PICKUP = 1696,
    ACT_DOTA_ITEM_DROP = 1697,
    ACT_DOTA_CAPTURE_PET = 1698,
    ACT_DOTA_PET_WARD_OBSERVER = 1699,
    ACT_DOTA_PET_WARD_SENTRY = 1700,
    ACT_DOTA_PET_LEVEL = 1701,
    ACT_DOTA_CAST_BURROW_END = 1702,
    ACT_DOTA_LIFESTEALER_ASSIMILATE = 1703,
    ACT_DOTA_LIFESTEALER_EJECT = 1704,
    ACT_DOTA_ATTACK_EVENT_BASH = 1705,
    ACT_DOTA_CAPTURE_RARE = 1706,
    ACT_DOTA_AW_MAGNETIC_FIELD = 1707,
    ACT_DOTA_CAST_GHOST_SHIP = 1708,
    ACT_DOTA_FXANIM = 1709,
    ACT_DOTA_VICTORY_START = 1710,
    ACT_DOTA_DEFEAT_START = 1711,
    ACT_DOTA_DP_SPIRIT_SIPHON = 1712,
    ACT_DOTA_TRICKS_END = 1713,
    ACT_DOTA_ES_STONE_CALLER = 1714,
    ACT_DOTA_MK_STRIKE = 1715,
    ACT_DOTA_VERSUS = 1716,
    ACT_DOTA_CAPTURE_CARD = 1717,
    ACT_DOTA_MK_SPRING_SOAR = 1718,
    ACT_DOTA_MK_SPRING_END = 1719,
    ACT_DOTA_MK_TREE_SOAR = 1720,
    ACT_DOTA_MK_TREE_END = 1721,
    ACT_DOTA_MK_FUR_ARMY = 1722,
    ACT_DOTA_MK_SPRING_CAST = 1723,
    ACT_DOTA_NECRO_GHOST_SHROUD = 1724,
    ACT_DOTA_OVERRIDE_ARCANA = 1725,
    ACT_DOTA_SLIDE = 1726,
    ACT_DOTA_SLIDE_LOOP = 1727,
    ACT_DOTA_GENERIC_CHANNEL_1 = 1728
}

/** !CompileMembersOnly */
declare enum LuaModifierType {
    LUA_MODIFIER_MOTION_NONE = 0,
    LUA_MODIFIER_MOTION_HORIZONTAL = 1,
    LUA_MODIFIER_MOTION_VERTICAL = 2,
    LUA_MODIFIER_MOTION_BOTH = 3,
    LUA_MODIFIER_INVALID = 4
}

/** !CompileMembersOnly */
declare enum ParticleAttachment_t {
    PATTACH_INVALID = -1,
    PATTACH_ABSORIGIN = 0,
    PATTACH_ABSORIGIN_FOLLOW = 1,
    PATTACH_CUSTOMORIGIN = 2,
    PATTACH_CUSTOMORIGIN_FOLLOW = 3,
    PATTACH_POINT = 4,
    PATTACH_POINT_FOLLOW = 5,
    PATTACH_EYES_FOLLOW = 6,
    PATTACH_OVERHEAD_FOLLOW = 7,
    PATTACH_WORLDORIGIN = 8,
    PATTACH_ROOTBONE_FOLLOW = 9,
    PATTACH_RENDERORIGIN_FOLLOW = 10,
    PATTACH_MAIN_VIEW = 11,
    PATTACH_WATERWAKE = 12,
    PATTACH_CENTER_FOLLOW = 13,
    MAX_PATTACH_TYPES = 14
}

/** !CompileMembersOnly */
declare enum UnitFilterResult {
    UF_SUCCESS = 0,
    UF_FAIL_FRIENDLY = 1,
    UF_FAIL_ENEMY = 2,
    UF_FAIL_HERO = 3,
    UF_FAIL_CONSIDERED_HERO = 4,
    UF_FAIL_CREEP = 5,
    UF_FAIL_BUILDING = 6,
    UF_FAIL_COURIER = 7,
    UF_FAIL_OTHER = 8,
    UF_FAIL_ANCIENT = 9,
    UF_FAIL_ILLUSION = 10,
    UF_FAIL_SUMMONED = 11,
    UF_FAIL_DOMINATED = 12,
    UF_FAIL_MELEE = 13,
    UF_FAIL_RANGED = 14,
    UF_FAIL_DEAD = 15,
    UF_FAIL_MAGIC_IMMUNE_ALLY = 16,
    UF_FAIL_MAGIC_IMMUNE_ENEMY = 17,
    UF_FAIL_INVULNERABLE = 18,
    UF_FAIL_IN_FOW = 19,
    UF_FAIL_INVISIBLE = 20,
    UF_FAIL_NOT_PLAYER_CONTROLLED = 21,
    UF_FAIL_ATTACK_IMMUNE = 22,
    UF_FAIL_CUSTOM = 23,
    UF_FAIL_INVALID_LOCATION = 24,
    UF_FAIL_DISABLE_HELP = 25,
    UF_FAIL_OUT_OF_WORLD = 26,
    UF_FAIL_NIGHTMARED = 27,
    UF_FAIL_OBSTRUCTED = 28
}

/** !CompileMembersOnly */
declare enum attackfail {
    DOTA_ATTACK_RECORD_FAIL_NO = 0,
    DOTA_ATTACK_RECORD_FAIL_TERRAIN_MISS = 1,
    DOTA_ATTACK_RECORD_FAIL_SOURCE_MISS = 2,
    DOTA_ATTACK_RECORD_FAIL_TARGET_EVADED = 3,
    DOTA_ATTACK_RECORD_FAIL_TARGET_INVULNERABLE = 4,
    DOTA_ATTACK_RECORD_FAIL_TARGET_OUT_OF_RANGE = 5,
    DOTA_ATTACK_RECORD_CANNOT_FAIL = 6
}

/** !CompileMembersOnly */
declare enum modifierfunction {
    /**
     * GetModifierPreAttack_BonusDamage
     */
    MODIFIER_PROPERTY_PREATTACK_BONUS_DAMAGE = 0,
    /**
     * GetModifierPreAttack_BonusDamage_Proc
     */
    MODIFIER_PROPERTY_PREATTACK_BONUS_DAMAGE_PROC = 1,
    /**
     * GetModifierPreAttack_BonusDamagePostCrit
     */
    MODIFIER_PROPERTY_PREATTACK_BONUS_DAMAGE_POST_CRIT = 2,
    /**
     * GetModifierBaseAttack_BonusDamage
     */
    MODIFIER_PROPERTY_BASEATTACK_BONUSDAMAGE = 3,
    /**
     * GetModifierProcAttack_BonusDamage_Physical
     */
    MODIFIER_PROPERTY_PROCATTACK_BONUS_DAMAGE_PHYSICAL = 4,
    /**
     * GetModifierProcAttack_BonusDamage_Magical
     */
    MODIFIER_PROPERTY_PROCATTACK_BONUS_DAMAGE_MAGICAL = 5,
    /**
     * GetModifierProcAttack_BonusDamage_Pure
     */
    MODIFIER_PROPERTY_PROCATTACK_BONUS_DAMAGE_PURE = 6,
    /**
     * GetModifierProcAttack_Feedback
     */
    MODIFIER_PROPERTY_PROCATTACK_FEEDBACK = 7,
    /**
     * GetModifierOverrideAttackDamage
     */
    MODIFIER_PROPERTY_OVERRIDE_ATTACK_DAMAGE = 8,
    /**
     * GetModifierPreAttack
     */
    MODIFIER_PROPERTY_PRE_ATTACK = 9,
    /**
     * GetModifierInvisibilityLevel
     */
    MODIFIER_PROPERTY_INVISIBILITY_LEVEL = 10,
    /**
     * GetModifierPersistentInvisibility
     */
    MODIFIER_PROPERTY_PERSISTENT_INVISIBILITY = 11,
    /**
     * GetModifierMoveSpeedBonus_Constant
     */
    MODIFIER_PROPERTY_MOVESPEED_BONUS_CONSTANT = 12,
    /**
     * GetModifierMoveSpeedOverride
     */
    MODIFIER_PROPERTY_MOVESPEED_BASE_OVERRIDE = 13,
    /**
     * GetModifierMoveSpeedBonus_Percentage
     */
    MODIFIER_PROPERTY_MOVESPEED_BONUS_PERCENTAGE = 14,
    /**
     * GetModifierMoveSpeedBonus_Percentage_Unique
     */
    MODIFIER_PROPERTY_MOVESPEED_BONUS_PERCENTAGE_UNIQUE = 15,
    /**
     * GetModifierMoveSpeedBonus_Percentage_Unique_2
     */
    MODIFIER_PROPERTY_MOVESPEED_BONUS_PERCENTAGE_UNIQUE_2 = 16,
    /**
     * GetModifierMoveSpeedBonus_Special_Boots
     */
    MODIFIER_PROPERTY_MOVESPEED_BONUS_UNIQUE = 17,
    /**
     * GetModifierMoveSpeedBonus_Special_Boots_2
     */
    MODIFIER_PROPERTY_MOVESPEED_BONUS_UNIQUE_2 = 18,
    /**
     * GetModifierMoveSpeed_Absolute
     */
    MODIFIER_PROPERTY_MOVESPEED_ABSOLUTE = 19,
    /**
     * GetModifierMoveSpeed_AbsoluteMin
     */
    MODIFIER_PROPERTY_MOVESPEED_ABSOLUTE_MIN = 20,
    /**
     * GetModifierMoveSpeed_Limit
     */
    MODIFIER_PROPERTY_MOVESPEED_LIMIT = 21,
    /**
     * GetModifierMoveSpeed_Max
     */
    MODIFIER_PROPERTY_MOVESPEED_MAX = 22,
    /**
     * GetModifierAttackSpeedBaseOverride
     */
    MODIFIER_PROPERTY_ATTACKSPEED_BASE_OVERRIDE = 23,
    /**
     * GetModifierFixedAttackRate
     */
    MODIFIER_PROPERTY_FIXED_ATTACK_RATE = 24,
    /**
     * GetModifierAttackSpeedBonus_Constant
     */
    MODIFIER_PROPERTY_ATTACKSPEED_BONUS_CONSTANT = 25,
    /**
     * GetModifierCooldownReduction_Constant
     */
    MODIFIER_PROPERTY_COOLDOWN_REDUCTION_CONSTANT = 26,
    /**
     * GetModifierBaseAttackTimeConstant
     */
    MODIFIER_PROPERTY_BASE_ATTACK_TIME_CONSTANT = 27,
    /**
     * GetModifierAttackPointConstant
     */
    MODIFIER_PROPERTY_ATTACK_POINT_CONSTANT = 28,
    /**
     * GetModifierDamageOutgoing_Percentage
     */
    MODIFIER_PROPERTY_DAMAGEOUTGOING_PERCENTAGE = 29,
    /**
     * GetModifierDamageOutgoing_Percentage_Illusion
     */
    MODIFIER_PROPERTY_DAMAGEOUTGOING_PERCENTAGE_ILLUSION = 30,
    /**
     * GetModifierTotalDamageOutgoing_Percentage
     */
    MODIFIER_PROPERTY_TOTALDAMAGEOUTGOING_PERCENTAGE = 31,
    /**
     * GetModifierSpellAmplify_Percentage
     */
    MODIFIER_PROPERTY_SPELL_AMPLIFY_PERCENTAGE = 32,
    /**
     * GetModifierSpellAmplify_PercentageUnique
     */
    MODIFIER_PROPERTY_SPELL_AMPLIFY_PERCENTAGE_UNIQUE = 33,
    /**
     * GetModifierHPRegenAmplify_Percentage
     */
    MODIFIER_PROPERTY_HP_REGEN_AMPLIFY_PERCENTAGE = 34,
    /**
     * GetModifierMPRegenAmplify_Percentage
     */
    MODIFIER_PROPERTY_MP_REGEN_AMPLIFY_PERCENTAGE = 35,
    /**
     * GetModifierMagicDamageOutgoing_Percentage
     */
    MODIFIER_PROPERTY_MAGICDAMAGEOUTGOING_PERCENTAGE = 36,
    /**
     * GetModifierBaseDamageOutgoing_Percentage
     */
    MODIFIER_PROPERTY_BASEDAMAGEOUTGOING_PERCENTAGE = 37,
    /**
     * GetModifierBaseDamageOutgoing_PercentageUnique
     */
    MODIFIER_PROPERTY_BASEDAMAGEOUTGOING_PERCENTAGE_UNIQUE = 38,
    /**
     * GetModifierIncomingDamage_Percentage
     */
    MODIFIER_PROPERTY_INCOMING_DAMAGE_PERCENTAGE = 39,
    /**
     * GetModifierIncomingPhysicalDamage_Percentage
     */
    MODIFIER_PROPERTY_INCOMING_PHYSICAL_DAMAGE_PERCENTAGE = 40,
    /**
     * GetModifierIncomingPhysicalDamageConstant
     */
    MODIFIER_PROPERTY_INCOMING_PHYSICAL_DAMAGE_CONSTANT = 41,
    /**
     * GetModifierIncomingSpellDamageConstant
     */
    MODIFIER_PROPERTY_INCOMING_SPELL_DAMAGE_CONSTANT = 42,
    /**
     * GetModifierEvasion_Constant
     */
    MODIFIER_PROPERTY_EVASION_CONSTANT = 43,
    /**
     * GetModifierNegativeEvasion_Constant
     */
    MODIFIER_PROPERTY_NEGATIVE_EVASION_CONSTANT = 44,
    /**
     * GetModifierStatusResistance
     */
    MODIFIER_PROPERTY_STATUS_RESISTANCE = 45,
    /**
     * GetModifierStatusResistanceStacking
     */
    MODIFIER_PROPERTY_STATUS_RESISTANCE_STACKING = 46,
    /**
     * GetModifierAvoidDamage
     */
    MODIFIER_PROPERTY_AVOID_DAMAGE = 47,
    /**
     * GetModifierAvoidSpell
     */
    MODIFIER_PROPERTY_AVOID_SPELL = 48,
    /**
     * GetModifierMiss_Percentage
     */
    MODIFIER_PROPERTY_MISS_PERCENTAGE = 49,
    /**
     * GetModifierPhysicalArmorBonus
     */
    MODIFIER_PROPERTY_PHYSICAL_ARMOR_BONUS = 50,
    /**
     * GetModifierPhysicalArmorBonusUnique
     */
    MODIFIER_PROPERTY_PHYSICAL_ARMOR_BONUS_UNIQUE = 51,
    /**
     * GetModifierPhysicalArmorBonusUniqueActive
     */
    MODIFIER_PROPERTY_PHYSICAL_ARMOR_BONUS_UNIQUE_ACTIVE = 52,
    /**
     * GetModifierIgnorePhysicalArmor
     */
    MODIFIER_PROPERTY_IGNORE_PHYSICAL_ARMOR = 53,
    /**
     * GetModifierMagicalResistanceDirectModification
     */
    MODIFIER_PROPERTY_MAGICAL_RESISTANCE_DIRECT_MODIFICATION = 54,
    /**
     * GetModifierMagicalResistanceBonus
     */
    MODIFIER_PROPERTY_MAGICAL_RESISTANCE_BONUS = 55,
    /**
     * GetModifierMagicalResistanceDecrepifyUnique
     */
    MODIFIER_PROPERTY_MAGICAL_RESISTANCE_DECREPIFY_UNIQUE = 56,
    /**
     * GetModifierBaseRegen
     */
    MODIFIER_PROPERTY_BASE_MANA_REGEN = 57,
    /**
     * GetModifierConstantManaRegen
     */
    MODIFIER_PROPERTY_MANA_REGEN_CONSTANT = 58,
    /**
     * GetModifierConstantManaRegenUnique
     */
    MODIFIER_PROPERTY_MANA_REGEN_CONSTANT_UNIQUE = 59,
    /**
     * GetModifierTotalPercentageManaRegen
     */
    MODIFIER_PROPERTY_MANA_REGEN_TOTAL_PERCENTAGE = 60,
    /**
     * GetModifierConstantHealthRegen
     */
    MODIFIER_PROPERTY_HEALTH_REGEN_CONSTANT = 61,
    /**
     * GetModifierHealthRegenPercentage
     */
    MODIFIER_PROPERTY_HEALTH_REGEN_PERCENTAGE = 62,
    /**
     * GetModifierHealthRegenPercentageUnique
     */
    MODIFIER_PROPERTY_HEALTH_REGEN_PERCENTAGE_UNIQUE = 63,
    /**
     * GetModifierHealthBonus
     */
    MODIFIER_PROPERTY_HEALTH_BONUS = 64,
    /**
     * GetModifierManaBonus
     */
    MODIFIER_PROPERTY_MANA_BONUS = 65,
    /**
     * GetModifierExtraStrengthBonus
     */
    MODIFIER_PROPERTY_EXTRA_STRENGTH_BONUS = 66,
    /**
     * GetModifierExtraHealthBonus
     */
    MODIFIER_PROPERTY_EXTRA_HEALTH_BONUS = 67,
    /**
     * GetModifierExtraManaBonus
     */
    MODIFIER_PROPERTY_EXTRA_MANA_BONUS = 68,
    /**
     * GetModifierExtraHealthPercentage
     */
    MODIFIER_PROPERTY_EXTRA_HEALTH_PERCENTAGE = 69,
    /**
     * GetModifierBonusStats_Strength
     */
    MODIFIER_PROPERTY_STATS_STRENGTH_BONUS = 70,
    /**
     * GetModifierBonusStats_Agility
     */
    MODIFIER_PROPERTY_STATS_AGILITY_BONUS = 71,
    /**
     * GetModifierBonusStats_Intellect
     */
    MODIFIER_PROPERTY_STATS_INTELLECT_BONUS = 72,
    /**
     * GetModifierCastRangeBonus
     */
    MODIFIER_PROPERTY_CAST_RANGE_BONUS = 73,
    /**
     * GetModifierCastRangeBonusTarget
     */
    MODIFIER_PROPERTY_CAST_RANGE_BONUS_TARGET = 74,
    /**
     * GetModifierCastRangeBonusStacking
     */
    MODIFIER_PROPERTY_CAST_RANGE_BONUS_STACKING = 75,
    /**
     * GetModifierAttackRangeOverride
     */
    MODIFIER_PROPERTY_ATTACK_RANGE_BASE_OVERRIDE = 76,
    /**
     * GetModifierAttackRangeBonus
     */
    MODIFIER_PROPERTY_ATTACK_RANGE_BONUS = 77,
    /**
     * GetModifierAttackRangeBonusUnique
     */
    MODIFIER_PROPERTY_ATTACK_RANGE_BONUS_UNIQUE = 78,
    /**
     * GetModifierMaxAttackRange
     */
    MODIFIER_PROPERTY_MAX_ATTACK_RANGE = 79,
    /**
     * GetModifierProjectileSpeedBonus
     */
    MODIFIER_PROPERTY_PROJECTILE_SPEED_BONUS = 80,
    /**
     * GetModifierProjectileName
     */
    MODIFIER_PROPERTY_PROJECTILE_NAME = 81,
    /**
     * ReincarnateTime
     */
    MODIFIER_PROPERTY_REINCARNATION = 82,
    /**
     * GetModifierConstantRespawnTime
     */
    MODIFIER_PROPERTY_RESPAWNTIME = 83,
    /**
     * GetModifierPercentageRespawnTime
     */
    MODIFIER_PROPERTY_RESPAWNTIME_PERCENTAGE = 84,
    /**
     * GetModifierStackingRespawnTime
     */
    MODIFIER_PROPERTY_RESPAWNTIME_STACKING = 85,
    /**
     * GetModifierPercentageCooldown
     */
    MODIFIER_PROPERTY_COOLDOWN_PERCENTAGE = 86,
    /**
     * GetModifierPercentageCooldownStacking
     */
    MODIFIER_PROPERTY_COOLDOWN_PERCENTAGE_STACKING = 87,
    /**
     * GetModifierPercentageCasttime
     */
    MODIFIER_PROPERTY_CASTTIME_PERCENTAGE = 88,
    /**
     * GetModifierPercentageManacost
     */
    MODIFIER_PROPERTY_MANACOST_PERCENTAGE = 89,
    /**
     * GetModifierPercentageManacostStacking
     */
    MODIFIER_PROPERTY_MANACOST_PERCENTAGE_STACKING = 90,
    /**
     * GetModifierConstantDeathGoldCost
     */
    MODIFIER_PROPERTY_DEATHGOLDCOST = 91,
    /**
     * GetModifierPercentageExpRateBoost
     */
    MODIFIER_PROPERTY_EXP_RATE_BOOST = 92,
    /**
     * GetModifierPreAttack_CriticalStrike
     */
    MODIFIER_PROPERTY_PREATTACK_CRITICALSTRIKE = 93,
    /**
     * GetModifierPreAttack_Target_CriticalStrike
     */
    MODIFIER_PROPERTY_PREATTACK_TARGET_CRITICALSTRIKE = 94,
    /**
     * GetModifierMagical_ConstantBlock
     */
    MODIFIER_PROPERTY_MAGICAL_CONSTANT_BLOCK = 95,
    /**
     * GetModifierPhysical_ConstantBlock
     */
    MODIFIER_PROPERTY_PHYSICAL_CONSTANT_BLOCK = 96,
    /**
     * GetModifierPhysical_ConstantBlockSpecial
     */
    MODIFIER_PROPERTY_PHYSICAL_CONSTANT_BLOCK_SPECIAL = 97,
    /**
     * GetModifierPhysical_ConstantBlockUnavoidablePreArmor
     */
    MODIFIER_PROPERTY_TOTAL_CONSTANT_BLOCK_UNAVOIDABLE_PRE_ARMOR = 98,
    /**
     * GetModifierTotal_ConstantBlock
     */
    MODIFIER_PROPERTY_TOTAL_CONSTANT_BLOCK = 99,
    /**
     * GetOverrideAnimation
     */
    MODIFIER_PROPERTY_OVERRIDE_ANIMATION = 100,
    /**
     * GetOverrideAnimationWeight
     */
    MODIFIER_PROPERTY_OVERRIDE_ANIMATION_WEIGHT = 101,
    /**
     * GetOverrideAnimationRate
     */
    MODIFIER_PROPERTY_OVERRIDE_ANIMATION_RATE = 102,
    /**
     * GetAbsorbSpell
     */
    MODIFIER_PROPERTY_ABSORB_SPELL = 103,
    /**
     * GetReflectSpell
     */
    MODIFIER_PROPERTY_REFLECT_SPELL = 104,
    /**
     * GetDisableAutoAttack
     */
    MODIFIER_PROPERTY_DISABLE_AUTOATTACK = 105,
    /**
     * GetBonusDayVision
     */
    MODIFIER_PROPERTY_BONUS_DAY_VISION = 106,
    /**
     * GetBonusNightVision
     */
    MODIFIER_PROPERTY_BONUS_NIGHT_VISION = 107,
    /**
     * GetBonusNightVisionUnique
     */
    MODIFIER_PROPERTY_BONUS_NIGHT_VISION_UNIQUE = 108,
    /**
     * GetBonusVisionPercentage
     */
    MODIFIER_PROPERTY_BONUS_VISION_PERCENTAGE = 109,
    /**
     * GetFixedDayVision
     */
    MODIFIER_PROPERTY_FIXED_DAY_VISION = 110,
    /**
     * GetFixedNightVision
     */
    MODIFIER_PROPERTY_FIXED_NIGHT_VISION = 111,
    /**
     * GetMinHealth
     */
    MODIFIER_PROPERTY_MIN_HEALTH = 112,
    /**
     * GetAbsoluteNoDamagePhysical
     */
    MODIFIER_PROPERTY_ABSOLUTE_NO_DAMAGE_PHYSICAL = 113,
    /**
     * GetAbsoluteNoDamageMagical
     */
    MODIFIER_PROPERTY_ABSOLUTE_NO_DAMAGE_MAGICAL = 114,
    /**
     * GetAbsoluteNoDamagePure
     */
    MODIFIER_PROPERTY_ABSOLUTE_NO_DAMAGE_PURE = 115,
    /**
     * GetIsIllusion
     */
    MODIFIER_PROPERTY_IS_ILLUSION = 116,
    /**
     * GetModifierIllusionLabel
     */
    MODIFIER_PROPERTY_ILLUSION_LABEL = 117,
    /**
     * GetModifierSuperIllusion
     */
    MODIFIER_PROPERTY_SUPER_ILLUSION = 118,
    /**
     * GetModifierSuperIllusionWithUltimate
     */
    MODIFIER_PROPERTY_SUPER_ILLUSION_WITH_ULTIMATE = 119,
    /**
     * GetModifierTurnRate_Percentage
     */
    MODIFIER_PROPERTY_TURN_RATE_PERCENTAGE = 120,
    /**
     * GetDisableHealing
     */
    MODIFIER_PROPERTY_DISABLE_HEALING = 121,
    /**
     * GetAlwaysAllowAttack
     */
    MODIFIER_PROPERTY_ALWAYS_ALLOW_ATTACK = 122,
    /**
     * GetOverrideAttackMagical
     */
    MODIFIER_PROPERTY_OVERRIDE_ATTACK_MAGICAL = 123,
    /**
     * GetModifierUnitStatsNeedsRefresh
     */
    MODIFIER_PROPERTY_UNIT_STATS_NEEDS_REFRESH = 124,
    /**
     * GetModifierBountyCreepMultiplier
     */
    MODIFIER_PROPERTY_BOUNTY_CREEP_MULTIPLIER = 125,
    /**
     * GetModifierBountyOtherMultiplier
     */
    MODIFIER_PROPERTY_BOUNTY_OTHER_MULTIPLIER = 126,
    /**
     * GetModifierUnitDisllowUpgrading
     */
    MODIFIER_PROPERTY_UNIT_DISALLOW_UPGRADING = 127,
    /**
     * GetModifierDodgeProjectile
     */
    MODIFIER_PROPERTY_DODGE_PROJECTILE = 128,
    /**
     * OnSpellTargetReady
     */
    MODIFIER_EVENT_ON_SPELL_TARGET_READY = 129,
    /**
     * OnAttackRecord
     */
    MODIFIER_EVENT_ON_ATTACK_RECORD = 130,
    /**
     * OnAttackStart
     */
    MODIFIER_EVENT_ON_ATTACK_START = 131,
    /**
     * OnAttack
     */
    MODIFIER_EVENT_ON_ATTACK = 132,
    /**
     * OnAttackLanded
     */
    MODIFIER_EVENT_ON_ATTACK_LANDED = 133,
    /**
     * OnAttackFail
     */
    MODIFIER_EVENT_ON_ATTACK_FAIL = 134,
    /**
     * OnAttackAllied
     */
    MODIFIER_EVENT_ON_ATTACK_ALLIED = 135,
    /**
     * OnProjectileDodge
     */
    MODIFIER_EVENT_ON_PROJECTILE_DODGE = 136,
    /**
     * OnOrder
     */
    MODIFIER_EVENT_ON_ORDER = 137,
    /**
     * OnUnitMoved
     */
    MODIFIER_EVENT_ON_UNIT_MOVED = 138,
    /**
     * OnAbilityStart
     */
    MODIFIER_EVENT_ON_ABILITY_START = 139,
    /**
     * OnAbilityExecuted
     */
    MODIFIER_EVENT_ON_ABILITY_EXECUTED = 140,
    /**
     * OnAbilityFullyCast
     */
    MODIFIER_EVENT_ON_ABILITY_FULLY_CAST = 141,
    /**
     * OnBreakInvisibility
     */
    MODIFIER_EVENT_ON_BREAK_INVISIBILITY = 142,
    /**
     * OnAbilityEndChannel
     */
    MODIFIER_EVENT_ON_ABILITY_END_CHANNEL = 143,
    MODIFIER_EVENT_ON_PROCESS_UPGRADE = 144,
    MODIFIER_EVENT_ON_REFRESH = 145,
    /**
     * OnTakeDamage
     */
    MODIFIER_EVENT_ON_TAKEDAMAGE = 146,
    /**
     * OnStateChanged
     */
    MODIFIER_EVENT_ON_STATE_CHANGED = 147,
    MODIFIER_EVENT_ON_ORB_EFFECT = 148,
    /**
     * OnAttacked
     */
    MODIFIER_EVENT_ON_ATTACKED = 149,
    /**
     * OnDeath
     */
    MODIFIER_EVENT_ON_DEATH = 150,
    /**
     * OnRespawn
     */
    MODIFIER_EVENT_ON_RESPAWN = 151,
    /**
     * OnSpentMana
     */
    MODIFIER_EVENT_ON_SPENT_MANA = 152,
    /**
     * OnTeleporting
     */
    MODIFIER_EVENT_ON_TELEPORTING = 153,
    /**
     * OnTeleported
     */
    MODIFIER_EVENT_ON_TELEPORTED = 154,
    /**
     * OnSetLocation
     */
    MODIFIER_EVENT_ON_SET_LOCATION = 155,
    /**
     * OnHealthGained
     */
    MODIFIER_EVENT_ON_HEALTH_GAINED = 156,
    /**
     * OnManaGained
     */
    MODIFIER_EVENT_ON_MANA_GAINED = 157,
    /**
     * OnTakeDamageKillCredit
     */
    MODIFIER_EVENT_ON_TAKEDAMAGE_KILLCREDIT = 158,
    /**
     * OnHeroKilled
     */
    MODIFIER_EVENT_ON_HERO_KILLED = 159,
    /**
     * OnHealReceived
     */
    MODIFIER_EVENT_ON_HEAL_RECEIVED = 160,
    /**
     * OnBuildingKilled
     */
    MODIFIER_EVENT_ON_BUILDING_KILLED = 161,
    /**
     * OnModelChanged
     */
    MODIFIER_EVENT_ON_MODEL_CHANGED = 162,
    /**
     * OnModifierAdded
     */
    MODIFIER_EVENT_ON_MODIFIER_ADDED = 163,
    /**
     * OnTooltip
     */
    MODIFIER_PROPERTY_TOOLTIP = 164,
    /**
     * GetModifierModelChange
     */
    MODIFIER_PROPERTY_MODEL_CHANGE = 165,
    /**
     * GetModifierModelScale
     */
    MODIFIER_PROPERTY_MODEL_SCALE = 166,
    /**
     * GetModifierScepter
     */
    MODIFIER_PROPERTY_IS_SCEPTER = 167,
    /**
     * GetActivityTranslationModifiers
     */
    MODIFIER_PROPERTY_TRANSLATE_ACTIVITY_MODIFIERS = 168,
    /**
     * GetAttackSound
     */
    MODIFIER_PROPERTY_TRANSLATE_ATTACK_SOUND = 169,
    /**
     * GetUnitLifetimeFraction
     */
    MODIFIER_PROPERTY_LIFETIME_FRACTION = 170,
    /**
     * GetModifierProvidesFOWVision
     */
    MODIFIER_PROPERTY_PROVIDES_FOW_POSITION = 171,
    /**
     * GetModifierSpellsRequireHP
     */
    MODIFIER_PROPERTY_SPELLS_REQUIRE_HP = 172,
    /**
     * GetForceDrawOnMinimap
     */
    MODIFIER_PROPERTY_FORCE_DRAW_MINIMAP = 173,
    /**
     * GetModifierDisableTurning
     */
    MODIFIER_PROPERTY_DISABLE_TURNING = 174,
    /**
     * GetModifierIgnoreCastAngle
     */
    MODIFIER_PROPERTY_IGNORE_CAST_ANGLE = 175,
    /**
     * GetModifierChangeAbilityValue
     */
    MODIFIER_PROPERTY_CHANGE_ABILITY_VALUE = 176,
    /**
     * GetModifierAbilityLayout
     */
    MODIFIER_PROPERTY_ABILITY_LAYOUT = 177,
    /**
     * OnDominated
     */
    MODIFIER_EVENT_ON_DOMINATED = 178,
    /**
     * GetModifierTempestDouble
     */
    MODIFIER_PROPERTY_TEMPEST_DOUBLE = 179,
    /**
     * PreserveParticlesOnModelChanged
     */
    MODIFIER_PROPERTY_PRESERVE_PARTICLES_ON_MODEL_CHANGE = 180,
    /**
     * OnAttackFinished
     */
    MODIFIER_EVENT_ON_ATTACK_FINISHED = 181,
    /**
     * GetModifierIgnoreCooldown
     */
    MODIFIER_PROPERTY_IGNORE_COOLDOWN = 182,
    /**
     * GetModifierCanAttackTrees
     */
    MODIFIER_PROPERTY_CAN_ATTACK_TREES = 183,
    /**
     * GetVisualZDelta
     */
    MODIFIER_PROPERTY_VISUAL_Z_DELTA = 184,
    MODIFIER_PROPERTY_INCOMING_DAMAGE_ILLUSION = 185,
    MODIFIER_FUNCTION_LAST = 186,
    MODIFIER_FUNCTION_INVALID = 255
}

/** !CompileMembersOnly */
declare enum modifierpriority {
    MODIFIER_PRIORITY_LOW = 0,
    MODIFIER_PRIORITY_NORMAL = 1,
    MODIFIER_PRIORITY_HIGH = 2,
    MODIFIER_PRIORITY_ULTRA = 3,
    MODIFIER_PRIORITY_SUPER_ULTRA = 4
}

/** !CompileMembersOnly */
declare enum modifierremove {
    DOTA_BUFF_REMOVE_ALL = 0,
    DOTA_BUFF_REMOVE_ENEMY = 1,
    DOTA_BUFF_REMOVE_ALLY = 2
}

/** !CompileMembersOnly */
declare enum modifierstate {
    MODIFIER_STATE_ROOTED = 0,
    MODIFIER_STATE_DISARMED = 1,
    MODIFIER_STATE_ATTACK_IMMUNE = 2,
    MODIFIER_STATE_SILENCED = 3,
    MODIFIER_STATE_MUTED = 4,
    MODIFIER_STATE_STUNNED = 5,
    MODIFIER_STATE_HEXED = 6,
    MODIFIER_STATE_INVISIBLE = 7,
    MODIFIER_STATE_INVULNERABLE = 8,
    MODIFIER_STATE_MAGIC_IMMUNE = 9,
    MODIFIER_STATE_PROVIDES_VISION = 10,
    MODIFIER_STATE_NIGHTMARED = 11,
    MODIFIER_STATE_BLOCK_DISABLED = 12,
    MODIFIER_STATE_EVADE_DISABLED = 13,
    MODIFIER_STATE_UNSELECTABLE = 14,
    MODIFIER_STATE_CANNOT_TARGET_ENEMIES = 15,
    MODIFIER_STATE_CANNOT_MISS = 16,
    MODIFIER_STATE_SPECIALLY_DENIABLE = 17,
    MODIFIER_STATE_FROZEN = 18,
    MODIFIER_STATE_COMMAND_RESTRICTED = 19,
    MODIFIER_STATE_NOT_ON_MINIMAP = 20,
    MODIFIER_STATE_NOT_ON_MINIMAP_FOR_ENEMIES = 21,
    MODIFIER_STATE_LOW_ATTACK_PRIORITY = 22,
    MODIFIER_STATE_NO_HEALTH_BAR = 23,
    MODIFIER_STATE_FLYING = 24,
    MODIFIER_STATE_NO_UNIT_COLLISION = 25,
    MODIFIER_STATE_NO_TEAM_MOVE_TO = 26,
    MODIFIER_STATE_NO_TEAM_SELECT = 27,
    MODIFIER_STATE_PASSIVES_DISABLED = 28,
    MODIFIER_STATE_DOMINATED = 29,
    MODIFIER_STATE_BLIND = 30,
    MODIFIER_STATE_OUT_OF_GAME = 31,
    MODIFIER_STATE_FAKE_ALLY = 32,
    MODIFIER_STATE_FLYING_FOR_PATHING_PURPOSES_ONLY = 33,
    MODIFIER_STATE_TRUESIGHT_IMMUNE = 34,
    MODIFIER_STATE_UNTARGETABLE = 35,
    MODIFIER_STATE_LAST = 36
}

/** !CompileMembersOnly */
declare enum quest_text_replace_values_t {
    QUEST_TEXT_REPLACE_VALUE_CURRENT_VALUE = 0,
    QUEST_TEXT_REPLACE_VALUE_TARGET_VALUE = 1,
    QUEST_TEXT_REPLACE_VALUE_ROUND = 2,
    QUEST_TEXT_REPLACE_VALUE_REWARD = 3,
    QUEST_NUM_TEXT_REPLACE_VALUES = 4
}

/** !CompileMembersOnly */
declare enum subquest_text_replace_values_t {
    SUBQUEST_TEXT_REPLACE_VALUE_CURRENT_VALUE = 0,
    SUBQUEST_TEXT_REPLACE_VALUE_TARGET_VALUE = 1,
    SUBQUEST_NUM_TEXT_REPLACE_VALUES = 2
}

/** !CompileMembersOnly */
declare enum DotaUnitOrder_t {
    DOTA_UNIT_ORDER_NONE = 0,
    DOTA_UNIT_ORDER_MOVE_TO_POSITION = 1,
    DOTA_UNIT_ORDER_MOVE_TO_TARGET = 2,
    DOTA_UNIT_ORDER_ATTACK_MOVE = 3,
    DOTA_UNIT_ORDER_ATTACK_TARGET = 4,
    DOTA_UNIT_ORDER_CAST_POSITION = 5,
    DOTA_UNIT_ORDER_CAST_TARGET = 6,
    DOTA_UNIT_ORDER_CAST_TARGET_TREE = 7,
    DOTA_UNIT_ORDER_CAST_NO_TARGET = 8,
    DOTA_UNIT_ORDER_CAST_TOGGLE = 9,
    DOTA_UNIT_ORDER_HOLD_POSITION = 10,
    DOTA_UNIT_ORDER_TRAIN_ABILITY = 11,
    DOTA_UNIT_ORDER_DROP_ITEM = 12,
    DOTA_UNIT_ORDER_GIVE_ITEM = 13,
    DOTA_UNIT_ORDER_PICKUP_ITEM = 14,
    DOTA_UNIT_ORDER_PICKUP_RUNE = 15,
    DOTA_UNIT_ORDER_PURCHASE_ITEM = 16,
    DOTA_UNIT_ORDER_SELL_ITEM = 17,
    DOTA_UNIT_ORDER_DISASSEMBLE_ITEM = 18,
    DOTA_UNIT_ORDER_MOVE_ITEM = 19,
    DOTA_UNIT_ORDER_CAST_TOGGLE_AUTO = 20,
    DOTA_UNIT_ORDER_STOP = 21,
    DOTA_UNIT_ORDER_TAUNT = 22,
    DOTA_UNIT_ORDER_BUYBACK = 23,
    DOTA_UNIT_ORDER_GLYPH = 24,
    DOTA_UNIT_ORDER_EJECT_ITEM_FROM_STASH = 25,
    DOTA_UNIT_ORDER_CAST_RUNE = 26,
    DOTA_UNIT_ORDER_PING_ABILITY = 27,
    DOTA_UNIT_ORDER_MOVE_TO_DIRECTION = 28,
    DOTA_UNIT_ORDER_PATROL = 29,
    DOTA_UNIT_ORDER_VECTOR_TARGET_POSITION = 30,
    DOTA_UNIT_ORDER_RADAR = 31,
    DOTA_UNIT_ORDER_SET_ITEM_COMBINE_LOCK = 32,
    DOTA_UNIT_ORDER_CONTINUE = 33,
    DOTA_UNIT_ORDER_VECTOR_TARGET_CANCELED = 34,
    DOTA_UNIT_ORDER_CAST_RIVER_PAINT = 35
}

/** !CompileMembersOnly */
declare enum OverheadAlerts_t {
    OVERHEAD_ALERT_GOLD = 0,
    OVERHEAD_ALERT_DENY = 1,
    OVERHEAD_ALERT_CRITICAL = 2,
    OVERHEAD_ALERT_XP = 3,
    OVERHEAD_ALERT_BONUS_SPELL_DAMAGE = 4,
    OVERHEAD_ALERT_MISS = 5,
    OVERHEAD_ALERT_DAMAGE = 6,
    OVERHEAD_ALERT_EVADE = 7,
    OVERHEAD_ALERT_BLOCK = 8,
    OVERHEAD_ALERT_BONUS_POISON_DAMAGE = 9,
    OVERHEAD_ALERT_HEAL = 10,
    OVERHEAD_ALERT_MANA_ADD = 11,
    OVERHEAD_ALERT_MANA_LOSS = 12,
    OVERHEAD_ALERT_LAST_HIT_EARLY = 13,
    OVERHEAD_ALERT_LAST_HIT_CLOSE = 14,
    OVERHEAD_ALERT_LAST_HIT_MISS = 15,
    OVERHEAD_ALERT_MAGICAL_BLOCK = 16,
    OVERHEAD_ALERT_INCOMING_DAMAGE = 17,
    OVERHEAD_ALERT_OUTGOING_DAMAGE = 18,
    OVERHEAD_ALERT_DISABLE_RESIST = 19,
    OVERHEAD_ALERT_DEATH = 20,
}
