// Type definitions for react-pay-icons 1.1
// Project: https://github.com/twltwl/react-pay-icons
// Definitions by: Paulo Andrade <https://github.com/prma85

import { DetailedReactHTMLElement } from 'react';

export type IconProps = {
    className?: string;
    style?: React.CSSProperties;
};

export type ReactPayIcon = (props: IconProps, context?: any) => DetailedReactHTMLElement<IconProps, HTMLDivElement>;

export const Ach: ReactPayIcon;
export const Affirm: ReactPayIcon;
export const Afterpay: ReactPayIcon;
export const Alfamart: ReactPayIcon;
export const Alipay: ReactPayIcon;
export const Amazon: ReactPayIcon;
export const AmazonTransparent: ReactPayIcon;
export const Amex: ReactPayIcon;
export const Applepay: ReactPayIcon;
export const AtmMomo: ReactPayIcon;
export const Aura: ReactPayIcon;
export const Bacs: ReactPayIcon;
export const Bancontact: ReactPayIcon;
export const Bankaxept: ReactPayIcon;
export const Bb: ReactPayIcon;
export const BbTransparent: ReactPayIcon;
export const Benefit: ReactPayIcon;
export const Bitcoin: ReactPayIcon;
export const Blik: ReactPayIcon;
export const Boleto: ReactPayIcon;
export const BoletoTransparent: ReactPayIcon;
export const Boost: ReactPayIcon;
export const Bradesco: ReactPayIcon;
export const BradescoTransparent: ReactPayIcon;
export const Caixa: ReactPayIcon;
export const CaixaTransparent: ReactPayIcon;
export const CartesBancaires: ReactPayIcon;
export const Cielo: ReactPayIcon;
export const CieloTransparent: ReactPayIcon;
export const Cirrus: ReactPayIcon;
export const Clearpay: ReactPayIcon;
export const Dana: ReactPayIcon;
export const Dankort: ReactPayIcon;
export const Diners: ReactPayIcon;
export const DinersClub: ReactPayIcon;
export const DirectDebit: ReactPayIcon;
export const Discover: ReactPayIcon;
export const DokuWallet: ReactPayIcon;
export const Dotpay: ReactPayIcon;
export const Ebay: ReactPayIcon;
export const EftposAustralia: ReactPayIcon;
export const Elavon: ReactPayIcon;
export const ElavonTransparent: ReactPayIcon;
export const Elo: ReactPayIcon;
export const Eps: ReactPayIcon;
export const Eway: ReactPayIcon;
export const Fawry: ReactPayIcon;
export const GCash: ReactPayIcon;
export const Generic: ReactPayIcon;
export const GenericTransparent: ReactPayIcon;
export const Girocard: ReactPayIcon;
export const Giropay: ReactPayIcon;
export const Global: ReactPayIcon;
export const GlobalTransparent: ReactPayIcon;
export const Googlepay: ReactPayIcon;
export const GrabPay: ReactPayIcon;
export const Green: ReactPayIcon;
export const Hiper: ReactPayIcon;
export const Hsbc: ReactPayIcon;
export const HsbcTransparent: ReactPayIcon;
export const Ideal: ReactPayIcon;
export const InteracLogo: ReactPayIcon;
export const Itau: ReactPayIcon;
export const ItauTransparent: ReactPayIcon;
export const Jcb: ReactPayIcon;
export const KakaoPay: ReactPayIcon;
export const Klarna: ReactPayIcon;
export const Knet: ReactPayIcon;
export const Konbini: ReactPayIcon;
export const MPesa: ReactPayIcon;
export const Mada: ReactPayIcon;
export const Maestro: ReactPayIcon;
export const Mastercard: ReactPayIcon;
export const MbWay: ReactPayIcon;
export const Meeza: ReactPayIcon;
export const MobilePay: ReactPayIcon;
export const Multibanco: ReactPayIcon;
export const Naps: ReactPayIcon;
export const Omannet: ReactPayIcon;
export const Oxxo: ReactPayIcon;
export const Pagseguro: ReactPayIcon;
export const PagseguroTransparent: ReactPayIcon;
export const PayEasy: ReactPayIcon;
export const Payco: ReactPayIcon;
export const Paypal: ReactPayIcon;
export const PaypalTransparent: ReactPayIcon;
export const Paysafecard: ReactPayIcon;
export const Payshop: ReactPayIcon;
export const Paywithgoogle: ReactPayIcon;
export const Pix: ReactPayIcon;
export const Poli: ReactPayIcon;
export const Ratepay: ReactPayIcon;
export const RazerGold: ReactPayIcon;
export const Rede: ReactPayIcon;
export const RedeTransparent: ReactPayIcon;
export const Sage: ReactPayIcon;
export const SamsungPay: ReactPayIcon;
export const Santander: ReactPayIcon;
export const SantanderTransparent: ReactPayIcon;
export const Sepa: ReactPayIcon;
export const Shopify: ReactPayIcon;
export const Skrill: ReactPayIcon;
export const SkrillMoneybookers: ReactPayIcon;
export const Solo: ReactPayIcon;
export const Stone: ReactPayIcon;
export const StoneTransparent: ReactPayIcon;
export const Swish: ReactPayIcon;
export const Troy: ReactPayIcon;
export const Trustly: ReactPayIcon;
export const Twint: ReactPayIcon;
export const UnionPay: ReactPayIcon;
export const Vipps: ReactPayIcon;
export const Visa: ReactPayIcon;
export const VisaElectron: ReactPayIcon;
export const Visadankort: ReactPayIcon;
export const Vpay: ReactPayIcon;
export const Wallet: ReactPayIcon;
export const WalletTransparent: ReactPayIcon;
export const Wechatpay: ReactPayIcon;
export const Western: ReactPayIcon;
export const Worldpay: ReactPayIcon;
export const WorldpayTransparent: ReactPayIcon;
