export class Input extends System {
    static get POINTER_DOWN(): string;
    static get POINTER_MOVE(): string;
    static get POINTER_UP(): string;
    static get WHEEL(): string;
    private mViewportPosition;
    private mPointerPosition;
    private mStagePosition;
    private mDom;
    private mEventList;
    private mKeyEventList;
    private mBoundListeners;
    private mPointerQueue;
    private mKeyQueue;
    private mPressedKeys;
    private mIsPointerDown;
    private mInputListeners;
    private mTarget;
    private mTargetComponent;
    private mLockedTarget;
    private mLastInTargetComponent;
    __initialize(): void;
    private __initListeners;
    private __onKeyEvent;
    private __onPointerEventDoc;
    private __onPointerEvent;
    private __pushEvent;
    private __getPointerPos;
    private __getTouchPos;
    private __findTarget;
    private __processNativeEvent;
    private __updateKeyboard;
    get isPointerDown(): boolean;
    get pointerX(): number;
    get pointerY(): number;
    get stageX(): number;
    get stageY(): number;
    get viewportPosition(): Vector;
    get pointerPosition(): Vector;
    get stagePosition(): Vector;
    get pressedKeys(): number[];
}
import { System } from '../core/System';
import { Vector } from '../geom/Vector';
