export let DOCUMENTATION: number;
export let ENVIRONMENT: number;
export let HELP: number;
export let HIGHCHARTS: number;
export let LIBRARIES: number;
export let LOGIN: number;
export let SECURITY: number;
export let SESSION: number;
export let WIDGETS: number;
