export let DEFAULT_SEARCH_PROCESS_KEY: number;
export let DUMMY: number;
export let EMPTY_HOME_PROCESS: number;
export let ERROR_EVENTS: number;
export let MY_REPORTS: number;
export let REPORT_EDITOR: number;
export let REPORT_EXECUTOR: number;
export let SECURITY: number;
export let USER_CONFIGURATIONS: number;
