export declare const customColorProfileSetError = "$$$/ScriptingSupport/Error/DontSetColorProfileCustom=To set the document to custom color management, assign the name of the desired color profile to the 'color profile name' property";
export declare const convertToIndexedRequiresOptionsError = "$$$/ScriptingSupport/Error/ConvertToIndexedRequiresOptions=The specified conversion to indexed color mode requires conversion options.";
export declare const convertToBitmapRequiresOptionsError = "$$$/ScriptingSupport/Error/ConvertToBitmapRequiresOptions=The specified conversion to bitmap mode requires conversion options.";
export declare const cannotChangeFilterMaskParamsError = "$$$/ScriptingSupport/Error/CannotChangeFilterMaskParrams=You cannot change filter mask parameters without the filter mask";
export declare const cannotChangeLayerMaskParamsError = "$$$/ScriptingSupport/Error/CannotChangeLayerMaskParams=You cannot change layer mask parameters without the layer mask";
export declare const cannotChangeVectorMaskParamsError = "$$$/ScriptingSupport/Error/CannotChangeVectorMaskParams=You cannot change vector mask parameters without the vector mask";
export declare const cannotSetDepthTo1BitError = "$$$/ScriptingSupport/Error/CannotSetDepthTo1Bit=You cannot set the bit depth property to one bit. To change a document to one bit, change the document mode to Bitmap.";
export declare const cannotSetDepthTo32BitError = "$$$/ScriptingSupport/Error/CannotSetDepthTo32Bit=You cannot set the bit depth property to thirty two bit. To change a document to thirty two bit, change the document mode to Grayscale or RGB.";
export declare const specificKeyDoesNotExistError = "$$$/ScriptingSupport/Error/SpecifiedKeyDoesNotExist=The requested property does not exist.";
export declare const noWorkAreaForLocalDocumentError = "$$$/ScriptingSupport/Error/NoWorkAreaForLocalDocumentError=Only cloud documents have the cloudWorkAreaDirectory property.";
export declare const resizeWResampleNoneTooManyArgsError = "$$$/ScriptingSupport/Error/ResizeWResampleNoneTooManyArgs=If you don't resample, you may only specify one of 'width', 'height' or 'resolution'";
export declare const resizeWResampleNonePixelsError = "$$$/ScriptingSupport/Error/ResizeWResampleNonePixels=You may use pixels to specify 'height' and 'width' only when resampling";
export declare const duplicateToDocumentPosWrongError = "$$$/ScriptingSupport/Error/DuplicateToDocumentPosWrong=When duplicating a layer to a document, you may only specify ElementPlacement.PLACEATBEGINNING or ElementPlacement.PLACEATEND.";
export declare const duplicateLayerSetInsideLayerSetError = "$$$/ScriptingSupport/Error/DuplicateLayerSetInsideLayerSet=You cannot duplicate a layer set to inside another layer set.";
export declare const duplicateLayerAtTopBottomLayerError = "$$$/CT/MultiScript/Error/IllegalArgument=You cannot specify ElementPlacement.PLACEATBEGINNING or ElementPlacement.PLACEATEND if target layer is an art layer.";
export declare const duplicateToInsideLayerError = "$$$/ScriptingSupport/Error/DuplicateToInsideArtLayer=You cannot duplicate to inside an art layer.";
export declare const tryingToLinkLayersAcrossDocumentsError = "$$$/ScriptingSupport/Error/TryingToLinkLayersAcrossDocuments=You cannot link to a layer that is in a different document.";
export declare const passThroughOnlyAvailableForGroupLayers = "$$$/ScriptingSupport/Error/PassThroughOnlyAvailableForLayerSets=The 'Pass Through' blend mode is only available for layer sets.";
export declare const notValidForComponentChannelError = "$$$/ScriptingSupport/Error/NotValidForComponentChannel=The operation is not valid for channels of type component.";
export declare const youCanOnlyMergeSpotChannelsError = "$$$/ScriptingSupport/Error/YouCanOnlyMergeSpotChannels=Only spot channels can be merged.";
export declare const histogramRequiresVisibleError = "$$$/ScriptingSupport/Error/HistogramRequiresVisible=You can only get a histogram for visible channels.";
export declare const cannotDeleteLastChannelError = "$$$/ScriptingSupport/Error/CannotDeleteLastChannel=You cannot delete the last channel in a document.";
export declare const cannotConvertToComponentChannelError = "$$$/ScriptingSupport/Error/CannotConvertToComponentChannel=You cannot convert a channel into a component channel.";
export declare const cannotConvertFromComponentChannelError = "$$$/ScriptingSupport/Error/CannotConvertFromComponentChannel=You cannot convert a component channel into another channel";
export declare const cannotConvertSpotChannelError = "$$$/ScriptingSupport/Error/CannotConvertSpotChannel=You cannot convert a spot channel into another channel";
