/* tslint:disable-next-line:no-unnecessary-class */
export class Ease {
    static linear(k: number): number;
    static quadraticIn(k: number): number;
    static quadraticOut(k: number): number;
    static quadraticInOut(k: number): number;
    static cubicIn(k: number): number;
    static cubicOut(k: number): number;
    static cubicInOut(k: number): number;
    static quarticIn(k: number): number;
    static quarticOut(k: number): number;
    static quarticInOut(k: number): number;
    static quinticIn(k: number): number;
    static quinticOut(k: number): number;
    static quinticInOut(k: number): number;
    static sinusoidalIn(k: number): number;
    static sinusoidalOut(k: number): number;
    static sinusoidalInOut(k: number): number;
    static exponentialIn(k: number): number;
    static exponentialOut(k: number): number;
    static exponentialInOut(k: number): number;
    static circularIn(k: number): number;
    static circularOut(k: number): number;
    static circularInOut(k: number): number;
    static elasticIn(k: number): number;
    static elasticOut(k: number): number;
    static elasticInOut(k: number): number;
    static backIn(k: number): number;
    static backOut(k: number): number;
    static backInOut(k: number): number;
    static bounceIn(k: number): number;
    static bounceOut(k: number): number;
    static bounceInOut(k: number): number;
    static smootherStep(k: number): number;
}
