import HDKey = require("hdkey");
const hdKey = new HDKey();
hdKey.derive("m/1/42");
hdKey.privateKey;
hdKey.publicKey;
hdKey.publicExtendedKey;
const priv = hdKey.privateExtendedKey || "hello world";
HDKey.fromExtendedKey(priv);
const sign = hdKey.sign(Buffer.from("hello world"));
hdKey.verify(Buffer.from("hello world"), sign);
hdKey.wipePrivateData();
hdKey.chainCode;
hdKey.toJSON();
HDKey.fromJSON({ xpriv: "", xpub: "" });
HDKey.fromMasterSeed(Buffer.from("hello world"));
HDKey.fromMasterSeed(Buffer.from("hello world"), { private: 0x043587cf, public: 0x04358394 });
hdKey.versions;
hdKey.depth;
hdKey.index;
hdKey.fingerprint;
hdKey.parentFingerprint;
hdKey.identifier;
hdKey.parentFingerprint;
hdKey.pubKeyHash;
hdKey.deriveChild(27);
HDKey.HARDENED_OFFSET;
