export const connection: import('../lib/connection/Connection.js');
export const database: import('../lib/database/Database.js');
export const dbCache: import('../lib/database/DBCache.js');
export const engine: import('../lib/engine/Engine.js');
export const request: import('../lib/http/Request.js');
export const response: import('../lib/http/Response.js');
export const session: import('../lib/session/Session.js');
export const tempDB: import('../lib/ido/IdoDB.js');
export const vendor: {
    name: string;
    legalName: string;
    siteUrl: string;
    systemName: string;
    logoUrl: string | number;
    logoTitle: string;
    footerLogoUrl: string | number;
    footerLogoTitle: string;
    mainMenuLogoUrl: string;
    faviconUrl: string;
    colors: import('./vendor.js').ThemeColors;
};
