import {
    DEFAULT_MEDIA_QUERY,
    DEFAULT_WIDTH,
    LARGER_DISPLAY_MEDIA_QUERY,
    LARGER_DISPLAY_WIDTH,
    LARGE_DISPLAY_MEDIA_QUERY,
    LARGE_DISPLAY_WIDTH,
    MIN_DEFAULT_MEDIA_QUERY,
    MIN_LARGER_DISPLAY_MEDIA_QUERY,
    MIN_LARGE_DISPLAY_MEDIA_QUERY,
    MIN_MOBILE_MEDIA_QUERY,
    MIN_TABLET_MEDIA_QUERY,
    MOBILE_MEDIA_QUERY,
    MOBILE_WIDTH,
    TABLET_MEDIA_QUERY,
    TABLET_WIDTH,
} from 'typography-breakpoint-constants';

function testString(value: string): void {}

testString(DEFAULT_MEDIA_QUERY);
testString(DEFAULT_WIDTH);
testString(LARGER_DISPLAY_MEDIA_QUERY);
testString(LARGER_DISPLAY_WIDTH);
testString(LARGE_DISPLAY_MEDIA_QUERY);
testString(LARGE_DISPLAY_WIDTH);
testString(MIN_DEFAULT_MEDIA_QUERY);
testString(MIN_LARGER_DISPLAY_MEDIA_QUERY);
testString(MIN_LARGE_DISPLAY_MEDIA_QUERY);
testString(MIN_MOBILE_MEDIA_QUERY);
testString(MIN_TABLET_MEDIA_QUERY);
testString(MOBILE_MEDIA_QUERY);
testString(MOBILE_WIDTH);
testString(TABLET_MEDIA_QUERY);
testString(TABLET_WIDTH);
