import MapBrowserEvent from '../MapBrowserEvent';

export type Condition = (this: any, p0: MapBrowserEvent<UIEvent>) => boolean;
export const always: (mapBrowserEvent: MapBrowserEvent<UIEvent>) => boolean;
export const never: (mapBrowserEvent: MapBrowserEvent<UIEvent>) => boolean;
export function all(...var_args: Condition[]): Condition;
export function altKeyOnly(mapBrowserEvent: MapBrowserEvent<UIEvent>): boolean;
export function altShiftKeysOnly(mapBrowserEvent: MapBrowserEvent<UIEvent>): boolean;
export function click(mapBrowserEvent: MapBrowserEvent<UIEvent>): boolean;
export function doubleClick(mapBrowserEvent: MapBrowserEvent<UIEvent>): boolean;
export function focus(event: MapBrowserEvent<UIEvent>): boolean;
export function focusWithTabindex(event: MapBrowserEvent<UIEvent>): boolean;
export function mouseActionButton(mapBrowserEvent: MapBrowserEvent<UIEvent>): boolean;
export function mouseOnly(mapBrowserEvent: MapBrowserEvent<UIEvent>): boolean;
export function noModifierKeys(mapBrowserEvent: MapBrowserEvent<UIEvent>): boolean;
export function penOnly(mapBrowserEvent: MapBrowserEvent<UIEvent>): boolean;
export function platformModifierKeyOnly(mapBrowserEvent: MapBrowserEvent<UIEvent>): boolean;
export function pointerMove(mapBrowserEvent: MapBrowserEvent<UIEvent>): boolean;
export function primaryAction(mapBrowserEvent: MapBrowserEvent<UIEvent>): boolean;
export function shiftKeyOnly(mapBrowserEvent: MapBrowserEvent<UIEvent>): boolean;
export function singleClick(mapBrowserEvent: MapBrowserEvent<UIEvent>): boolean;
export function targetNotEditable(mapBrowserEvent: MapBrowserEvent<UIEvent>): boolean;
export function touchOnly(mapBrowserEvent: MapBrowserEvent<UIEvent>): boolean;
