import insert = require('voca/insert');
import latinise = require('voca/latinise');
import pad = require('voca/pad');
import padLeft = require('voca/pad_left');
import padRight = require('voca/pad_right');
import repeat = require('voca/repeat');
import replace = require('voca/replace');
import replaceAll = require('voca/replace_all');
import reverse = require('voca/reverse');
import reverseGrapheme = require('voca/reverse_grapheme');
import slugify = require('voca/slugify');
import splice = require('voca/splice');
import tr = require('voca/tr');
import trim = require('voca/trim');
import trimLeft = require('voca/trim_left');
import trimRight = require('voca/trim_right');
import wordWrap = require('voca/word_wrap');

insert();
latinise();
pad();
padLeft();
padRight();
repeat();
replace();
replaceAll();
reverse();
reverseGrapheme();
slugify();
splice();
tr();
trim();
trimLeft();
trimRight();
wordWrap();
