export { default as applyTo } from './applyTo';
export { default as compose2 } from './compose2';
export { default as composeB } from './composeB';
export { default as constant } from './constant';
export { default as converge } from './converge';
export { default as flip } from './flip';
export { default as identity } from './identity';
export { default as psi } from './psi';
export { default as substitution } from './substitution';
