declare module goog {
    function require(name: 'goog.dom.TagName'): typeof goog.dom.TagName;
}

declare module goog.dom {

    /**
     * Enum of all html tag names specified by the W3C HTML4.01 and HTML5
     * specifications.
     * @enum {string}
     */
    type TagName = string;
    var TagName: {
        A: TagName;
        ABBR: TagName;
        ACRONYM: TagName;
        ADDRESS: TagName;
        APPLET: TagName;
        AREA: TagName;
        ARTICLE: TagName;
        ASIDE: TagName;
        AUDIO: TagName;
        B: TagName;
        BASE: TagName;
        BASEFONT: TagName;
        BDI: TagName;
        BDO: TagName;
        BIG: TagName;
        BLOCKQUOTE: TagName;
        BODY: TagName;
        BR: TagName;
        BUTTON: TagName;
        CANVAS: TagName;
        CAPTION: TagName;
        CENTER: TagName;
        CITE: TagName;
        CODE: TagName;
        COL: TagName;
        COLGROUP: TagName;
        COMMAND: TagName;
        DATA: TagName;
        DATALIST: TagName;
        DD: TagName;
        DEL: TagName;
        DETAILS: TagName;
        DFN: TagName;
        DIALOG: TagName;
        DIR: TagName;
        DIV: TagName;
        DL: TagName;
        DT: TagName;
        EM: TagName;
        EMBED: TagName;
        FIELDSET: TagName;
        FIGCAPTION: TagName;
        FIGURE: TagName;
        FONT: TagName;
        FOOTER: TagName;
        FORM: TagName;
        FRAME: TagName;
        FRAMESET: TagName;
        H1: TagName;
        H2: TagName;
        H3: TagName;
        H4: TagName;
        H5: TagName;
        H6: TagName;
        HEAD: TagName;
        HEADER: TagName;
        HGROUP: TagName;
        HR: TagName;
        HTML: TagName;
        I: TagName;
        IFRAME: TagName;
        IMG: TagName;
        INPUT: TagName;
        INS: TagName;
        ISINDEX: TagName;
        KBD: TagName;
        KEYGEN: TagName;
        LABEL: TagName;
        LEGEND: TagName;
        LI: TagName;
        LINK: TagName;
        MAP: TagName;
        MARK: TagName;
        MATH: TagName;
        MENU: TagName;
        META: TagName;
        METER: TagName;
        NAV: TagName;
        NOFRAMES: TagName;
        NOSCRIPT: TagName;
        OBJECT: TagName;
        OL: TagName;
        OPTGROUP: TagName;
        OPTION: TagName;
        OUTPUT: TagName;
        P: TagName;
        PARAM: TagName;
        PRE: TagName;
        PROGRESS: TagName;
        Q: TagName;
        RP: TagName;
        RT: TagName;
        RUBY: TagName;
        S: TagName;
        SAMP: TagName;
        SCRIPT: TagName;
        SECTION: TagName;
        SELECT: TagName;
        SMALL: TagName;
        SOURCE: TagName;
        SPAN: TagName;
        STRIKE: TagName;
        STRONG: TagName;
        STYLE: TagName;
        SUB: TagName;
        SUMMARY: TagName;
        SUP: TagName;
        SVG: TagName;
        TABLE: TagName;
        TBODY: TagName;
        TD: TagName;
        TEXTAREA: TagName;
        TFOOT: TagName;
        TH: TagName;
        THEAD: TagName;
        TIME: TagName;
        TITLE: TagName;
        TR: TagName;
        TRACK: TagName;
        TT: TagName;
        U: TagName;
        UL: TagName;
        VAR: TagName;
        VIDEO: TagName;
        WBR: TagName;
    };
}
