// Generated by typings
// Project: https://github.com/datadog/node-dogstatsd
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped

declare module "node-dogstatsd" {

	interface StatsDOptions {
		global_tags?: string[];
	}

	class StatsD {
		constructor(host: string, port?: number, socket?: string, options?: StatsDOptions);

		timing(stat: string, time: number, sample_rate?: number, tags?: string[]): void;

		increment(stat: string, sample_rate?: number, tags?: string[]): void;
		incrementBy(stat: string, value: number, tags?: string[]): void;

		decrement(stat: string, sample_rate?: number, tags?: string[]): void;
		decrementBy(stat: string, value: number, tags?: string[]): void;

		gauge(stat: string, value: number, sample_rate?: number, tags?: string[]): void;

		histogram(stat: string, time: number, sample_rate?: number, tags?: string[]): void;

		set(stat: string, time: number, sample_rate?: number, tags?: string[]): void;

		update_stats(stats: string[], delta: number, sample_rate?: number, tags?: string[]): void;

		close(): void;
	}

	export = StatsD;
}
