declare module goog {
    function require(name: 'goog.events.EventType'): typeof goog.events.EventType;
}

declare module goog.events {

    /**
     * Constants for event names.
     * @enum {string}
     */
    type EventType = string;
    var EventType: {
        CLICK: EventType;
        RIGHTCLICK: EventType;
        DBLCLICK: EventType;
        MOUSEDOWN: EventType;
        MOUSEUP: EventType;
        MOUSEOVER: EventType;
        MOUSEOUT: EventType;
        MOUSEMOVE: EventType;
        MOUSEENTER: EventType;
        MOUSELEAVE: EventType;
        SELECTSTART: EventType;
        WHEEL: EventType;
        KEYPRESS: EventType;
        KEYDOWN: EventType;
        KEYUP: EventType;
        BLUR: EventType;
        FOCUS: EventType;
        DEACTIVATE: EventType;
        FOCUSIN: EventType;
        FOCUSOUT: EventType;
        CHANGE: EventType;
        SELECT: EventType;
        SUBMIT: EventType;
        INPUT: EventType;
        PROPERTYCHANGE: EventType;
        DRAGSTART: EventType;
        DRAG: EventType;
        DRAGENTER: EventType;
        DRAGOVER: EventType;
        DRAGLEAVE: EventType;
        DROP: EventType;
        DRAGEND: EventType;
        TOUCHSTART: EventType;
        TOUCHMOVE: EventType;
        TOUCHEND: EventType;
        TOUCHCANCEL: EventType;
        BEFOREUNLOAD: EventType;
        CONSOLEMESSAGE: EventType;
        CONTEXTMENU: EventType;
        DOMCONTENTLOADED: EventType;
        ERROR: EventType;
        HELP: EventType;
        LOAD: EventType;
        LOSECAPTURE: EventType;
        ORIENTATIONCHANGE: EventType;
        READYSTATECHANGE: EventType;
        RESIZE: EventType;
        SCROLL: EventType;
        UNLOAD: EventType;
        HASHCHANGE: EventType;
        PAGEHIDE: EventType;
        PAGESHOW: EventType;
        POPSTATE: EventType;
        COPY: EventType;
        PASTE: EventType;
        CUT: EventType;
        BEFORECOPY: EventType;
        BEFORECUT: EventType;
        BEFOREPASTE: EventType;
        ONLINE: EventType;
        OFFLINE: EventType;
        MESSAGE: EventType;
        CONNECT: EventType;
        ANIMATIONSTART: EventType;
        ANIMATIONEND: EventType;
        ANIMATIONITERATION: EventType;
        TRANSITIONEND: EventType;
        POINTERDOWN: EventType;
        POINTERUP: EventType;
        POINTERCANCEL: EventType;
        POINTERMOVE: EventType;
        POINTEROVER: EventType;
        POINTEROUT: EventType;
        POINTERENTER: EventType;
        POINTERLEAVE: EventType;
        GOTPOINTERCAPTURE: EventType;
        LOSTPOINTERCAPTURE: EventType;
        MSGESTURECHANGE: EventType;
        MSGESTUREEND: EventType;
        MSGESTUREHOLD: EventType;
        MSGESTURESTART: EventType;
        MSGESTURETAP: EventType;
        MSGOTPOINTERCAPTURE: EventType;
        MSINERTIASTART: EventType;
        MSLOSTPOINTERCAPTURE: EventType;
        MSPOINTERCANCEL: EventType;
        MSPOINTERDOWN: EventType;
        MSPOINTERENTER: EventType;
        MSPOINTERHOVER: EventType;
        MSPOINTERLEAVE: EventType;
        MSPOINTERMOVE: EventType;
        MSPOINTEROUT: EventType;
        MSPOINTEROVER: EventType;
        MSPOINTERUP: EventType;
        TEXT: EventType;
        TEXTINPUT: EventType;
        COMPOSITIONSTART: EventType;
        COMPOSITIONUPDATE: EventType;
        COMPOSITIONEND: EventType;
        EXIT: EventType;
        LOADABORT: EventType;
        LOADCOMMIT: EventType;
        LOADREDIRECT: EventType;
        LOADSTART: EventType;
        LOADSTOP: EventType;
        RESPONSIVE: EventType;
        SIZECHANGED: EventType;
        UNRESPONSIVE: EventType;
        VISIBILITYCHANGE: EventType;
        STORAGE: EventType;
        DOMSUBTREEMODIFIED: EventType;
        DOMNODEINSERTED: EventType;
        DOMNODEREMOVED: EventType;
        DOMNODEREMOVEDFROMDOCUMENT: EventType;
        DOMNODEINSERTEDINTODOCUMENT: EventType;
        DOMATTRMODIFIED: EventType;
        DOMCHARACTERDATAMODIFIED: EventType;
    };
}
