// Type definitions for mui-phone-input-ssr 1.0
// Project: https://github.com/braxex/mui-phone-input-ssr
// Definitions by: Jonathan Jayet <https://github.com/jjayet>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped

import * as React from 'react';

import { StandardTextFieldProps } from '@material-ui/core/TextField';

type Region =
    | 'america'
    | 'europe'
    | 'asia'
    | 'oceania'
    | 'africa'
    | 'north-america'
    | 'south-america'
    | 'central-america'
    | 'carribean'
    | 'european-union'
    | 'ex-ussr'
    | 'middle-east'
    | 'north-africa';

export type Localization = Record<string, string>;

export enum Country {
    Afghanistan = 'af',
    Albania = 'al',
    Algeria = 'dz',
    'American Samoa' = 'as',
    Andorra = 'ad',
    Angola = 'ao',
    Anguilla = 'ai',
    'Antigua and Barbuda' = 'ag',
    Argentina = 'ar',
    Armenia = 'am',
    Aruba = 'aw',
    Australia = 'au',
    Austria = 'at',
    Azerbaijan = 'az',
    Bahamas = 'bs',
    Bahrain = 'bh',
    Bangladesh = 'bd',
    Barbados = 'bb',
    Belarus = 'by',
    Belgium = 'be',
    Belize = 'bz',
    Benin = 'bj',
    Bermuda = 'bm',
    Bhutan = 'bt',
    Bolivia = 'bo',
    'Bosnia and Herzegovina' = 'ba',
    Botswana = 'bw',
    Brazil = 'br',
    'British Indian Ocean Territory' = 'io',
    'British Virgin Islands' = 'vg',
    Brunei = 'bn',
    Bulgaria = 'bg',
    'Burkina Faso' = 'bf',
    Burundi = 'bi',
    Cambodia = 'kh',
    Cameroon = 'cm',
    Canada = 'ca',
    'Cape Verde' = 'cv',
    'Caribbean Netherlands' = 'bq',
    'Cayman Islands' = 'ky',
    'Central African Republic' = 'cf',
    Chad = 'td',
    Chile = 'cl',
    China = 'cn',
    Colombia = 'co',
    Comoros = 'km',
    CongoCd = 'cd',
    Congo = 'cg',
    'Cook Islands' = 'ck',
    'Costa Rica' = 'cr',
    'Côte d’Ivoire' = 'ci',
    Croatia = 'hr',
    Cuba = 'cu',
    Curaçao = 'cw',
    Cyprus = 'cy',
    'Czech Republic' = 'cz',
    Denmark = 'dk',
    Djibouti = 'dj',
    Dominica = 'dm',
    'Dominican Republic' = 'do',
    Ecuador = 'ec',
    Egypt = 'eg',
    'El Salvador' = 'sv',
    'Equatorial Guinea' = 'gq',
    Eritrea = 'er',
    Estonia = 'ee',
    Ethiopia = 'et',
    'Falkland Islands' = 'fk',
    'Faroe Islands' = 'fo',
    Fiji = 'fj',
    Finland = 'fi',
    France = 'fr',
    'French Guiana' = 'gf',
    'French Polynesia' = 'pf',
    Gabon = 'ga',
    Gambia = 'gm',
    Georgia = 'ge',
    Germany = 'de',
    Ghana = 'gh',
    Gibraltar = 'gi',
    Greece = 'gr',
    Greenland = 'gl',
    Grenada = 'gd',
    Guadeloupe = 'gp',
    Guam = 'gu',
    Guatemala = 'gt',
    Guinea = 'gn',
    'Guinea-Bissau' = 'gw',
    Guyana = 'gy',
    Haiti = 'ht',
    Honduras = 'hn',
    'Hong Kong' = 'hk',
    Hungary = 'hu',
    Iceland = 'is',
    India = 'in',
    Indonesia = 'id',
    Iran = 'ir',
    Iraq = 'iq',
    Ireland = 'ie',
    Israel = 'il',
    Italy = 'it',
    Jamaica = 'jm',
    Japan = 'jp',
    Jordan = 'jo',
    Kazakhstan = 'kz',
    Kenya = 'ke',
    Kiribati = 'ki',
    Kuwait = 'kw',
    Kyrgyzstan = 'kg',
    Laos = 'la',
    Latvia = 'lv',
    Lebanon = 'lb',
    Lesotho = 'ls',
    Liberia = 'lr',
    Libya = 'ly',
    Liechtenstein = 'li',
    Lithuania = 'lt',
    Luxembourg = 'lu',
    Macau = 'mo',
    Macedonia = 'mk',
    Madagascar = 'mg',
    Malawi = 'mw',
    Malaysia = 'my',
    Maldives = 'mv',
    Mali = 'ml',
    Malta = 'mt',
    'Marshall Islands' = 'mh',
    Martinique = 'mq',
    Mauritania = 'mr',
    Mauritius = 'mu',
    Mexico = 'mx',
    Micronesia = 'fm',
    Moldova = 'md',
    Monaco = 'mc',
    Mongolia = 'mn',
    Montenegro = 'me',
    Montserrat = 'ms',
    Morocco = 'ma',
    Mozambique = 'mz',
    Myanmar = 'mm',
    Namibia = 'na',
    Nauru = 'nr',
    Nepal = 'np',
    Netherlands = 'nl',
    'New Caledonia' = 'nc',
    'New Zealand' = 'nz',
    Nicaragua = 'ni',
    Niger = 'ne',
    Nigeria = 'ng',
    Niue = 'nu',
    'Norfolk Island' = 'nf',
    'North Korea' = 'kp',
    'Northern Mariana Islands' = 'mp',
    Norway = 'no',
    Oman = 'om',
    Pakistan = 'pk',
    Palau = 'pw',
    Palestine = 'ps',
    Panama = 'pa',
    'Papua New Guinea' = 'pg',
    Paraguay = 'py',
    Peru = 'pe',
    Philippines = 'ph',
    Poland = 'pl',
    Portugal = 'pt',
    'Puerto Rico' = 'pr',
    Qatar = 'qa',
    Réunion = 're',
    Romania = 'ro',
    Russia = 'ru',
    Rwanda = 'rw',
    'Saint Barthélemy' = 'bl',
    'Saint Helena' = 'sh',
    'Saint Kitts and Nevis' = 'kn',
    'Saint Lucia' = 'lc',
    'Saint Martin' = 'mf',
    'Saint Pierre and Miquelon' = 'pm',
    'Saint Vincent and the Grenadines' = 'vc',
    Samoa = 'ws',
    'San Marino' = 'sm',
    'São Tomé and Príncipe' = 'st',
    'Saudi Arabia' = 'sa',
    Senegal = 'sn',
    Serbia = 'rs',
    Seychelles = 'sc',
    'Sierra Leone' = 'sl',
    Singapore = 'sg',
    'Sint Maarten' = 'sx',
    Slovakia = 'sk',
    Slovenia = 'si',
    'Solomon Islands' = 'sb',
    Somalia = 'so',
    'South Africa' = 'za',
    'South Korea' = 'kr',
    'South Sudan' = 'ss',
    Spain = 'es',
    'Sri Lanka' = 'lk',
    Sudan = 'sd',
    Suriname = 'sr',
    Swaziland = 'sz',
    Sweden = 'se',
    Switzerland = 'ch',
    Syria = 'sy',
    Taiwan = 'tw',
    Tajikistan = 'tj',
    Tanzania = 'tz',
    Thailand = 'th',
    'Timor-Leste' = 'tl',
    Togo = 'tg',
    Tokelau = 'tk',
    Tonga = 'to',
    'Trinidad and Tobago' = 'tt',
    Tunisia = 'tn',
    Turkey = 'tr',
    Turkmenistan = 'tm',
    'Turks and Caicos Islands' = 'tc',
    Tuvalu = 'tv',
    'U.S. Virgin Islands' = 'vi',
    Uganda = 'ug',
    Ukraine = 'ua',
    'United Arab Emirates' = 'ae',
    'United Kingdom' = 'gb',
    'United States' = 'us',
    Uruguay = 'uy',
    Uzbekistan = 'uz',
    Vanuatu = 'vu',
    'Vatican City' = 'va',
    Venezuela = 've',
    Vietnam = 'vn',
    'Wallis and Futuna' = 'wf',
    Yemen = 'ye',
    Zambia = 'zm',
    Zimbabwe = 'zw',
}

export interface Options {
    excludeCountries?: Country[];
    onlyCountries?: Country[];
    preferredCountries?: Country[];
    defaultCountry?: Country;
    inputClass?: string;
    dropdownClass?: string;
    autoFormat?: boolean; // default true
    disableAreaCodes?: boolean;
    disableCountryCode?: boolean; // default false
    disableDropdown?: boolean; // default false
    enableLongNumbers?: boolean; // default false
    countryCodeEditable?: boolean; // default true
    regions?: Region[];
    localization?: Localization;
}

export function MuiPhoneNumber(props: Options & StandardTextFieldProps): JSX.Element;
