import ES2020 = require("./es2020");

interface ES2021 {
    readonly "Abstract Equality Comparison": typeof import("./2021/AbstractEqualityComparison");
    readonly "Abstract Relational Comparison": typeof import("./2021/AbstractRelationalComparison");
    readonly "Strict Equality Comparison": typeof import("./2021/StrictEqualityComparison");
    readonly AddEntriesFromIterable: typeof import("./2021/AddEntriesFromIterable");
    readonly AdvanceStringIndex: typeof import("./2021/AdvanceStringIndex");
    readonly ArrayCreate: typeof import("./2021/ArrayCreate");
    readonly ArraySetLength: typeof import("./2021/ArraySetLength");
    readonly ArraySpeciesCreate: typeof import("./2021/ArraySpeciesCreate");
    readonly BigIntBitwiseOp: typeof import("./2021/BigIntBitwiseOp");
    readonly BinaryAnd: typeof import("./2021/BinaryAnd");
    readonly BinaryOr: typeof import("./2021/BinaryOr");
    readonly BinaryXor: typeof import("./2021/BinaryXor");
    readonly Call: typeof import("./2021/Call");
    readonly CanonicalNumericIndexString: typeof import("./2021/CanonicalNumericIndexString");
    readonly clamp: typeof import("./2021/clamp");
    readonly CodePointAt: typeof import("./2021/CodePointAt");
    readonly CodePointsToString: typeof import("./2021/CodePointsToString");
    readonly CompletePropertyDescriptor: typeof import("./2021/CompletePropertyDescriptor");
    readonly CopyDataProperties: typeof import("./2021/CopyDataProperties");
    readonly CreateDataProperty: typeof import("./2021/CreateDataProperty");
    readonly CreateDataPropertyOrThrow: typeof import("./2021/CreateDataPropertyOrThrow");
    readonly CreateHTML: typeof import("./2021/CreateHTML");
    readonly CreateIterResultObject: typeof import("./2021/CreateIterResultObject");
    readonly CreateListFromArrayLike: typeof import("./2021/CreateListFromArrayLike");
    readonly CreateMethodProperty: typeof import("./2021/CreateMethodProperty");
    readonly CreateRegExpStringIterator: typeof import("./2021/CreateRegExpStringIterator");
    readonly DateFromTime: typeof import("./2021/DateFromTime");
    readonly DateString: typeof import("./2021/DateString");
    readonly Day: typeof import("./2021/Day");
    readonly DayFromYear: typeof import("./2021/DayFromYear");
    readonly DaysInYear: typeof import("./2021/DaysInYear");
    readonly DayWithinYear: typeof import("./2021/DayWithinYear");
    readonly DefinePropertyOrThrow: typeof import("./2021/DefinePropertyOrThrow");
    readonly DeletePropertyOrThrow: typeof import("./2021/DeletePropertyOrThrow");
    readonly EnumerableOwnPropertyNames: typeof import("./2021/EnumerableOwnPropertyNames");
    readonly FlattenIntoArray: typeof import("./2021/FlattenIntoArray");
    readonly FromPropertyDescriptor: typeof import("./2021/FromPropertyDescriptor");
    readonly Get: typeof import("./2021/Get");
    readonly GetIterator: typeof import("./2021/GetIterator");
    readonly GetMethod: typeof import("./2021/GetMethod");
    readonly GetOwnPropertyKeys: typeof import("./2021/GetOwnPropertyKeys");
    readonly GetPrototypeFromConstructor: typeof import("./2021/GetPrototypeFromConstructor");
    readonly GetSubstitution: typeof import("./2021/GetSubstitution");
    readonly GetV: typeof import("./2021/GetV");
    readonly HasOwnProperty: typeof import("./2021/HasOwnProperty");
    readonly HasProperty: typeof import("./2021/HasProperty");
    readonly HourFromTime: typeof import("./2021/HourFromTime");
    readonly InLeapYear: typeof import("./2021/InLeapYear");
    readonly InstanceofOperator: typeof import("./2021/InstanceofOperator");
    readonly Invoke: typeof import("./2021/Invoke");
    readonly IsAccessorDescriptor: typeof import("./2021/IsAccessorDescriptor");
    readonly IsArray: typeof import("./2021/IsArray");
    readonly IsCallable: typeof import("./2021/IsCallable");
    readonly IsConcatSpreadable: typeof import("./2021/IsConcatSpreadable");
    readonly IsConstructor: typeof import("./2021/IsConstructor");
    readonly IsDataDescriptor: typeof import("./2021/IsDataDescriptor");
    readonly IsExtensible: typeof import("./2021/IsExtensible");
    readonly IsGenericDescriptor: typeof import("./2021/IsGenericDescriptor");
    readonly IsIntegralNumber: typeof import("./2021/IsIntegralNumber");
    readonly IsPromise: typeof import("./2021/IsPromise");
    readonly IsPropertyKey: typeof import("./2021/IsPropertyKey");
    readonly IsRegExp: typeof import("./2021/IsRegExp");
    readonly IsStringPrefix: typeof import("./2021/IsStringPrefix");
    readonly IterableToList: typeof import("./2021/IterableToList");
    readonly IteratorClose: typeof import("./2021/IteratorClose");
    readonly IteratorComplete: typeof import("./2021/IteratorComplete");
    readonly IteratorNext: typeof import("./2021/IteratorNext");
    readonly IteratorStep: typeof import("./2021/IteratorStep");
    readonly IteratorValue: typeof import("./2021/IteratorValue");
    readonly LengthOfArrayLike: typeof import("./2021/LengthOfArrayLike");
    readonly MakeDate: typeof import("./2021/MakeDate");
    readonly MakeDay: typeof import("./2021/MakeDay");
    readonly MakeTime: typeof import("./2021/MakeTime");
    readonly MinFromTime: typeof import("./2021/MinFromTime");
    readonly modulo: typeof import("./2021/modulo");
    readonly MonthFromTime: typeof import("./2021/MonthFromTime");
    readonly msFromTime: typeof import("./2021/msFromTime");
    readonly NumberBitwiseOp: typeof import("./2021/NumberBitwiseOp");
    readonly NumberToBigInt: typeof import("./2021/NumberToBigInt");
    readonly OrdinaryDefineOwnProperty: typeof import("./2021/OrdinaryDefineOwnProperty");
    readonly OrdinaryGetOwnProperty: typeof import("./2021/OrdinaryGetOwnProperty");
    readonly OrdinaryGetPrototypeOf: typeof import("./2021/OrdinaryGetPrototypeOf");
    readonly OrdinaryHasInstance: typeof import("./2021/OrdinaryHasInstance");
    readonly OrdinaryHasProperty: typeof import("./2021/OrdinaryHasProperty");
    readonly OrdinaryObjectCreate: typeof import("./2021/OrdinaryObjectCreate");
    readonly OrdinarySetPrototypeOf: typeof import("./2021/OrdinarySetPrototypeOf");
    readonly PromiseResolve: typeof import("./2021/PromiseResolve");
    readonly RegExpExec: typeof import("./2021/RegExpExec");
    readonly RequireObjectCoercible: typeof import("./2021/RequireObjectCoercible");
    readonly SameValue: typeof import("./2021/SameValue");
    readonly SameValueNonNumeric: typeof import("./2021/SameValueNonNumeric");
    readonly SameValueZero: typeof import("./2021/SameValueZero");
    readonly SecFromTime: typeof import("./2021/SecFromTime");
    readonly Set: typeof import("./2021/Set");
    readonly SetFunctionName: typeof import("./2021/SetFunctionName");
    readonly SetIntegrityLevel: typeof import("./2021/SetIntegrityLevel");
    readonly SpeciesConstructor: typeof import("./2021/SpeciesConstructor");
    readonly StrictEqualityComparison: typeof import("./2021/StrictEqualityComparison");
    readonly StringIndexOf: typeof import("./2021/StringIndexOf");
    readonly StringPad: typeof import("./2021/StringPad");
    readonly StringToBigInt: typeof import("./2021/StringToBigInt");
    readonly StringToCodePoints: typeof import("./2021/StringToCodePoints");
    readonly substring: typeof import("./2021/substring");
    readonly SymbolDescriptiveString: typeof import("./2021/SymbolDescriptiveString");
    readonly TestIntegrityLevel: typeof import("./2021/TestIntegrityLevel");
    readonly thisBigIntValue: typeof import("./2021/thisBigIntValue");
    readonly thisBooleanValue: typeof import("./2021/thisBooleanValue");
    readonly thisNumberValue: typeof import("./2021/thisNumberValue");
    readonly thisStringValue: typeof import("./2021/thisStringValue");
    readonly thisSymbolValue: typeof import("./2021/thisSymbolValue");
    readonly thisTimeValue: typeof import("./2021/thisTimeValue");
    readonly TimeClip: typeof import("./2021/TimeClip");
    readonly TimeFromYear: typeof import("./2021/TimeFromYear");
    readonly TimeString: typeof import("./2021/TimeString");
    readonly TimeWithinDay: typeof import("./2021/TimeWithinDay");
    readonly ToBigInt: typeof import("./2021/ToBigInt");
    readonly ToBigInt64: typeof import("./2021/ToBigInt64");
    readonly ToBigUint64: typeof import("./2021/ToBigUint64");
    readonly ToBoolean: typeof import("./2021/ToBoolean");
    readonly ToDateString: typeof import("./2021/ToDateString");
    readonly ToIndex: typeof import("./2021/ToIndex");
    readonly ToInt16: typeof import("./2021/ToInt16");
    readonly ToInt32: typeof import("./2021/ToInt32");
    readonly ToInt8: typeof import("./2021/ToInt8");
    readonly ToIntegerOrInfinity: typeof import("./2021/ToIntegerOrInfinity");
    readonly ToLength: typeof import("./2021/ToLength");
    readonly ToNumber: typeof import("./2021/ToNumber");
    readonly ToNumeric: typeof import("./2021/ToNumeric");
    readonly ToObject: typeof import("./2021/ToObject");
    readonly ToPrimitive: typeof import("./2021/ToPrimitive");
    readonly ToPropertyDescriptor: typeof import("./2021/ToPropertyDescriptor");
    readonly ToPropertyKey: typeof import("./2021/ToPropertyKey");
    readonly ToString: typeof import("./2021/ToString");
    readonly ToUint16: typeof import("./2021/ToUint16");
    readonly ToUint32: typeof import("./2021/ToUint32");
    readonly ToUint8: typeof import("./2021/ToUint8");
    readonly ToUint8Clamp: typeof import("./2021/ToUint8Clamp");
    readonly TrimString: typeof import("./2021/TrimString");
    readonly Type: typeof import("./2021/Type");
    readonly ValidateAndApplyPropertyDescriptor: typeof import("./2021/ValidateAndApplyPropertyDescriptor");
    readonly WeekDay: typeof import("./2021/WeekDay");
    readonly YearFromTime: typeof import("./2021/YearFromTime");
}

declare namespace ES2021 {
    // Re-export types from previous versions
    // - ES2015:
    type PropertyKey = ES2020.PropertyKey;

    // - ES5:
    type GenericDescriptor = ES2020.GenericDescriptor;
    type AccessorDescriptor<T = unknown> = ES2020.AccessorDescriptor<T>;
    type DataDescriptor<T = unknown> = ES2020.DataDescriptor<T>;
    type PropertyDescriptor<T = unknown> = ES2020.PropertyDescriptor<T>;
}

declare const ES2021: ES2021;
export = ES2021;
