export type FrappeFieldType =
    | "Attach"
    | "Attach Image"
    | "Autocomplete"
    | "Barcode"
    | "Check"
    | "Code"
    | "Color"
    | "Currency"
    | "Data"
    | "Date Range"
    | "Date"
    | "Datetime"
    | "Dynamic Link"
    | "Float"
    | "Geolocation"
    | "HTML Editor"
    | "Int"
    | "Link"
    | "Markdown Editor"
    | "MultiCheck"
    | "MultiSelect"
    | "Password"
    | "Rating"
    | "Select"
    | "Signature"
    | "Text Editor"
    | "Time"
    | "Button"
    | "Icon";

export default FrappeFieldType;
