// import assert = require('assert');  // TODO: this brings in ../types/assert
import base32 = require('base32');
import base64 = require('base64');
import base64vlq = require('base64vlq');
// import bson = require('bson'); // TODO: this brings in ../types/bson
import console = require('console');
import constants = require('constants');
import coroutine = require('coroutine');
import crypto = require('crypto');
import db = require('db');
import dgram = require('dgram');
import dns = require('dns');
// import encoding = require('encoding');
import fs = require('fs');
import gd = require('gd');
// import global = require('global');
import gui = require('gui');
import hash = require('hash');
import hex = require('hex');
import http = require('http');
// import iconv = require('iconv'); // TODO: this brings in ../types/iconv
import io = require('io');
import json = require('json');
import mq = require('mq');
import net = require('net');
import os = require('os');
import path = require('path');
import path_posix = require('path_posix');
import path_win32 = require('path_win32');
import process = require('process');
import profiler = require('profiler');
import punycode = require('punycode');
import querystring = require('querystring');
import registry = require('registry');
import ssl = require('ssl');
import string_decoder = require('string_decoder');
// import test = require('test');
import timers = require('timers');
import tty = require('tty');
import url = require('url');
import util = require('util');
// import uuid = require('uuid');  // TODO: this brings in ../types/uuid
import vm = require('vm');
// import ws = require('ws'); // TODO: this brings in ../types/ws
// import xml = require('xml'); // TODO: this brings in ../types/xml
import zip = require('zip');
import zlib = require('zlib');
// import zmq = require('zmq'); // TODO: this brings in ../types/zmq
