// Since all the definitions are auto generated from jsdoc doclets and internally tested through application,
// add some basic tests here.
import { ojAccordion } from "oraclejet/ojaccordion";
import AnimationUtils = require("oraclejet/ojanimation");
import ArrayDataProvider = require("oraclejet/ojarraydataprovider");
import ArrayTreeDataProvider = require("oraclejet/ojarraytreedataprovider");
import { AttributeGroupHandler, ColorAttributeGroupHandler, ShapeAttributeGroupHandler } from 'oraclejet/ojattributegrouphandler';
import { ojAvatar } from "oraclejet/ojavatar";
import { ojButton, ojButtonsetMany, ojButtonsetOne } from "oraclejet/ojbutton";
import { ojChart, ojChartGroup, ojChartItem, ojChartSeries, ojSparkChart, ojSparkChartItem } from "oraclejet/ojchart";
import { ojCheckboxset } from "oraclejet/ojcheckboxset";
import { ojCollapsible } from "oraclejet/ojcollapsible";
import CollectionDataprovider = require("oraclejet/ojcollectiondataprovider");
import Color = require("oraclejet/ojcolor");
import { ojColorPalette } from "oraclejet/ojcolorpalette";
import { ojColorSpectrum } from "oraclejet/ojcolorspectrum";
import Components = require("oraclejet/ojcomponentcore");
import Composite = require("oraclejet/ojcomposite");
import Config = require('oraclejet/ojconfig');
import Context = require("oraclejet/ojcontext");
import { ojConveyorBelt } from "oraclejet/ojconveyorbelt";
import { ojDataGrid } from "oraclejet/ojdatagrid";
import { DataMapping, DataProvider, DataProviderAddOperationEventDetail, DataProviderMutationEventDetail, DataProviderOperationEventDetail } from "oraclejet/ojdataprovider";
import { ojDatePicker, ojDateTimePicker, ojInputDate, ojInputDateTime, ojInputTime } from "oraclejet/ojdatetimepicker";
import { ojDefer } from "oraclejet/ojdefer";
import DeferredDataprovider = require("oraclejet/ojdeferreddataprovider");
import { ojDiagram, ojDiagramLink, ojDiagramNode } from "oraclejet/ojdiagram";
import { ojDialog } from "oraclejet/ojdialog";
import { dvtBaseComponent } from "oraclejet/ojdvt-base";
import { editableValue } from "oraclejet/ojeditablevalue";
import ExpressionUtils = require('oraclejet/ojexpressionutils');
import { ojFilePicker, FileUploadTransport } from "oraclejet/ojfilepicker";
import { ojFilmStrip } from "oraclejet/ojfilmstrip";
import { ojFormLayout } from "oraclejet/ojformlayout";
import { ojGantt, ojGanttRow, ojGanttTask, ojGanttDependency } from "oraclejet/ojgantt";
import GanttUtils = require ('oraclejet/ojganttutils');
import { ojLedGauge, ojRatingGauge, ojStatusMeterGauge } from "oraclejet/ojgauge";
import { ojInputNumber } from "oraclejet/ojinputnumber";
import { ojInputPassword, ojInputText, ojTextArea } from "oraclejet/ojinputtext";
import { KeySet, ExpandAllKeySet, ExpandedKeySet } from "oraclejet/ojkeyset";
import { ObservableExpandedKeySet } from "oraclejet/ojknockout-keyset";
import KnockoutUtils = require("oraclejet/ojknockout-model");
import KnockoutTemplateUtils = require('oraclejet/ojknockouttemplateutils');
import { ojLabel } from "oraclejet/ojlabel";
import { ojLabelValue } from "oraclejet/ojlabelvalue";
import { ojLegend } from "oraclejet/ojlegend";
import ListDataProviderView = require("oraclejet/ojlistdataproviderview");
import { ojListView } from "oraclejet/ojlistview";
import LocaleData = require('oraclejet/ojlocaledata');
import Logger = require('oraclejet/ojlogger');
import { ojMasonryLayout } from "oraclejet/ojmasonrylayout";
import { ojMenu } from "oraclejet/ojmenu";
import { ojMenuSelectMany } from "oraclejet/ojmenuselectmany";
import { ojMessages } from "oraclejet/ojmessages";
import { ojMessage } from "oraclejet/ojmessage";
import Message = require("oraclejet/ojmessaging");
import { Collection, Model, URLError, OAuth } from "oraclejet/ojmodel";
import { ojModule } from "oraclejet/ojmodule-element";
import ModuleElementUtils = require("oraclejet/ojmodule-element-utils");
import ModuleAnimations = require("oraclejet/ojmoduleanimations") ;
import { ojNavigationList, ojTabBar } from "oraclejet/ojnavigationlist";
import { ojNBox } from "oraclejet/ojnbox";
import { ojOptgroup } from "oraclejet/ojoptgroup";
import { ojOption } from "oraclejet/ojoption";
import { ojPictoChart, ojPictoChartItem } from "oraclejet/ojpictochart";
import { ojPopup } from "oraclejet/ojpopup";
import { ojProgress } from "oraclejet/ojprogress";
import { ojProgressList, ProgressItem } from "oraclejet/ojprogresslist";
import PullToRefreshUtils = require("oraclejet/ojpulltorefresh");
import { ojRadioset } from "oraclejet/ojradioset";
import { ojRefresher } from "oraclejet/ojrefresher";
import ResponsiveKnockoutUtils = require('oraclejet/ojresponsiveknockoututils');
import ResponsiveUtils = require('oraclejet/ojresponsiveutils');
import Router = require("oraclejet/ojrouter");
import { ojComboboxOne, ojComboboxMany, ojSelectOne, ojSelectMany } from "oraclejet/ojselectcombobox";
import { ojSlider } from "oraclejet/ojslider";
import { ojSunburst } from "oraclejet/ojsunburst";
import { ojSwipeActions } from "oraclejet/ojswipeactions";
import SwipeToRevealUtils = require("oraclejet/ojswipetoreveal");
import { ojSwitch } from "oraclejet/ojswitch";
import { ojSwitcher } from "oraclejet/ojswitcher";
import { ojTable } from "oraclejet/ojtable";
import { ojTagCloud } from "oraclejet/ojtagcloud";
import { ojThematicMap } from "oraclejet/ojthematicmap";
import ThemeUtils = require('oraclejet/ojthemeutils');
import { dvtTimeComponent } from "oraclejet/ojtime-base";
import { ojTimeAxis } from "oraclejet/ojtimeaxis";
import TimeUtils = require("oraclejet/ojtimeutils");
import { ojToolbar } from "oraclejet/ojtoolbar";
import { ojTrain } from "oraclejet/ojtrain";
import Translations = require("oraclejet/ojtranslation");
import TreeDataProvider = require("oraclejet/ojtreedataprovider");
import { ojTreemap } from "oraclejet/ojtreemap";
import { Validation, Validator, ValidatorError, ValidatorFactory,
    AsyncValidator, LengthValidator, LengthValidatorFactory, RegExpValidator, RegExpValidatorFactory, RequiredValidator, RequiredValidatorFactory } from "oraclejet/ojvalidation-base";
import { DateRestrictionValidator, DateRestrictionValidatorFactory, DateTimeRangeValidator, DateTimeRangeValidatorFactory } from "oraclejet/ojvalidation-datetime";
import { NumberRangeValidator, NumberRangeValidatorFactory } from "oraclejet/ojvalidation-number";
import { ojValidationGroup } from "oraclejet/ojvalidationgroup";

const onChangedCallback = (event: CustomEvent) => {
};
const myHTMLElement = document.getElementById('myelement');
const accordionElement =  myHTMLElement as ojAccordion;
accordionElement.multiple = true;
accordionElement.onMultipleChanged = onChangedCallback;

const avatarElement = myHTMLElement as ojAvatar;
avatarElement.size = "xxs";
avatarElement.set("initials", "I");
avatarElement.unset("src");

const button = myHTMLElement as ojButtonsetOne;
button.chroming = 'half';
