jobs:
    dprint-check:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
        - run: $(npx dprint check | grep "Found * not formatted file*.") >> "$GITHUB_STEP_SUMMARY"

name: Format Check

on: pull_request

permissions:
  contents: read
