# This is a basic workflow to help you get started with Actions

name: On Main Push

# Controls when the workflow will run
on:
    # Triggers the workflow on push into the main branch
    push:
        branches: [main]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    echo-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 14
            - run: echo "bla bla bla bla"
