name: Update CODEOWNERs

# For testing
# on: push

# For production
on:
  schedule:
    # https://crontab.guru/#5_8_*_*_1
    - cron: '5 8 * * 1'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  update:
    permissions:
      contents: write # for Git to git push
    runs-on: ubuntu-latest
    if: github.repository == 'DefinitelyTyped/DefinitelyTyped'

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup-for-scripts

      - run: git config --global user.email "290192711+typescript-automation[bot]@users.noreply.github.com"
      - run: git config --global user.name "typescript-automation[bot]"

      - run: pnpm run update-codeowners

      - uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7.2.0
        with:
          commit_author: 'typescript-automation[bot] <290192711+typescript-automation[bot]@users.noreply.github.com>'
          commit_message: '🤖 Update CODEOWNERS'
          commit_user_email: '290192711+typescript-automation[bot]@users.noreply.github.com'
          commit_user_name: 'typescript-automation[bot]'
